// "기초 영어회화" 도구의 목차. 챕터 하나 = 상황 하나. 새 챕터는 이 배열에 항목만
// 추가하면 목차 화면과 화면 등록(index.js)에 자동으로 반영된다 — 다른 곳을 고칠 필요 없다.
//
// 일상대화 위주로 구성했다(어린이 애니메이션 참고, D-65) — 뽀로로/타요/페파피그류가 매번
// "아침에 일어나기", "친구랑 놀기", "밥 먹기", "잠자리" 같은 하루 일과 하나를 에피소드로
// 삼는 것과 같은 결. 단어 암기(This is a rabbit)보다 그 상황에서 실제로 주고받는 말
// (Let's play! / Can I have more?)을 우선했다.
export const CHAPTERS = [
  {
    id: "greeting",
    title: "인사 · 기분 표현",
    emoji: "👋",
    sentences: [
      { id: "hello", text: "Hello!", ko: "안녕!" },
      { id: "good-morning", text: "Good morning!", ko: "좋은 아침이에요!" },
      { id: "good-night", text: "Good night!", ko: "잘 자요!" },
      { id: "how-are-you", text: "How are you?", ko: "어떻게 지내요?" },
      { id: "happy", text: "I'm happy.", ko: "나는 기뻐요." },
      { id: "sad", text: "I'm sad.", ko: "나는 슬퍼요." },
      { id: "angry", text: "I'm angry.", ko: "나는 화나요." },
      { id: "tired", text: "I'm tired.", ko: "나는 피곤해요." },
      { id: "hungry", text: "I'm hungry.", ko: "나는 배고파요." },
      { id: "thirsty", text: "I'm thirsty.", ko: "나는 목말라요." },
      { id: "sleepy", text: "I'm sleepy.", ko: "나는 졸려요." },
      { id: "scared", text: "I'm scared.", ko: "나는 무서워요." },
      { id: "excited", text: "I'm excited.", ko: "나는 신나요." },
      { id: "surprised", text: "I'm surprised.", ko: "나는 놀랐어요." },
      { id: "bored", text: "I'm bored.", ko: "나는 심심해요." },
      { id: "okay", text: "I'm okay.", ko: "나는 괜찮아요." },
      { id: "nice-to-meet-you", text: "Nice to meet you.", ko: "만나서 반가워요." },
      { id: "whats-your-name", text: "What's your name?", ko: "이름이 뭐예요?" },
      { id: "my-name-is", text: "My name is Tom.", ko: "내 이름은 톰이에요." },
      { id: "see-you-later", text: "See you later!", ko: "나중에 봐요!" },
      { id: "see-you-tomorrow", text: "See you tomorrow!", ko: "내일 봐요!" },
      { id: "thank-you", text: "Thank you!", ko: "고마워요!" },
      { id: "youre-welcome", text: "You're welcome!", ko: "천만에요!" },
      { id: "sorry", text: "I'm sorry.", ko: "미안해요." },
      { id: "its-okay", text: "It's okay.", ko: "괜찮아요." },
      { id: "excuse-me", text: "Excuse me.", ko: "실례합니다." },
      { id: "please", text: "Please.", ko: "부탁해요." },
      { id: "yes", text: "Yes!", ko: "네!" },
      { id: "no", text: "No.", ko: "아니요." },
      { id: "bye", text: "Goodbye!", ko: "안녕히 가세요!" },
    ],
  },
  {
    id: "morning-routine",
    title: "아침 일과",
    emoji: "☀️",
    sentences: [
      { id: "wake-up", text: "Wake up!", ko: "일어나요!" },
      { id: "brush-teeth", text: "Let's brush our teeth.", ko: "이 닦자." },
      { id: "wash-face", text: "Wash your face.", ko: "세수하세요." },
      { id: "get-dressed", text: "Get dressed!", ko: "옷 입자!" },
      { id: "eat-breakfast", text: "Let's eat breakfast.", ko: "아침 먹자." },
      { id: "wheres-my-shoes", text: "Where are my shoes?", ko: "내 신발 어디 있어요?" },
      { id: "im-ready", text: "I'm ready!", ko: "준비 다 됐어요!" },
      { id: "lets-go", text: "Let's go!", ko: "가자!" },
    ],
  },
  {
    id: "family",
    title: "가족 이야기",
    emoji: "👨‍👩‍👧",
    sentences: [
      { id: "this-is-mom", text: "This is my mom.", ko: "이 사람은 우리 엄마예요." },
      { id: "this-is-dad", text: "This is my dad.", ko: "이 사람은 우리 아빠예요." },
      { id: "i-love-you", text: "I love you.", ko: "사랑해요." },
      { id: "can-you-help-me", text: "Can you help me?", ko: "도와줄 수 있어요?" },
      { id: "read-together", text: "Let's read a book together.", ko: "같이 책 읽자." },
      { id: "i-miss-you", text: "I miss you.", ko: "보고 싶어요." },
      { id: "give-me-a-hug", text: "Give me a hug.", ko: "안아 주세요." },
      { id: "wheres-grandma", text: "Where is grandma?", ko: "할머니 어디 계세요?" },
    ],
  },
  {
    id: "playing-with-friends",
    title: "친구랑 놀기",
    emoji: "🎈",
    sentences: [
      { id: "lets-play", text: "Let's play!", ko: "같이 놀자!" },
      { id: "can-i-play-too", text: "Can I play too?", ko: "나도 같이 놀아도 돼요?" },
      { id: "my-turn", text: "It's my turn!", ko: "내 차례예요!" },
      { id: "watch-this", text: "Watch this!", ko: "이거 봐!" },
      { id: "so-much-fun", text: "That's so much fun!", ko: "진짜 재밌다!" },
      { id: "lets-be-friends", text: "Let's be friends.", ko: "우리 친구하자." },
      { id: "can-i-borrow-this", text: "Can I borrow this?", ko: "이거 빌려도 돼요?" },
      { id: "lets-share", text: "Let's share.", ko: "같이 나눠 쓰자." },
      { id: "tag-youre-it", text: "Tag, you're it!", ko: "잡았다, 네 차례야!" },
      { id: "lets-race", text: "Let's race!", ko: "우리 달리기 하자!" },
    ],
  },
  {
    id: "meal-time",
    title: "밥 먹을 때",
    emoji: "🍽️",
    sentences: [
      { id: "im-hungry", text: "I'm hungry.", ko: "배고파요." },
      { id: "lets-eat", text: "Let's eat!", ko: "먹자!" },
      { id: "this-is-yummy", text: "This is yummy!", ko: "이거 맛있어요!" },
      { id: "i-dont-like-this", text: "I don't like this.", ko: "이거 안 좋아해요." },
      { id: "can-i-have-more", text: "Can I have more?", ko: "더 먹어도 돼요?" },
      { id: "im-full", text: "I'm full.", ko: "배불러요." },
      { id: "cheers", text: "Cheers!", ko: "건배!" },
      { id: "thank-you-for-the-food", text: "Thank you for the food.", ko: "잘 먹겠습니다." },
    ],
  },
  {
    id: "bath-bedtime",
    title: "목욕 · 잠자리",
    emoji: "🛁",
    sentences: [
      { id: "bath-time", text: "Bath time!", ko: "목욕할 시간이에요!" },
      { id: "water-is-warm", text: "The water is warm.", ko: "물이 따뜻해요." },
      { id: "wash-your-hair", text: "Let's wash your hair.", ko: "머리 감자." },
      { id: "put-on-pajamas", text: "Put on your pajamas.", ko: "잠옷 입자." },
      { id: "brush-teeth-again", text: "Brush your teeth.", ko: "이 닦자." },
      { id: "bedtime-story", text: "Let's read a bedtime story.", ko: "자기 전에 책 읽어 줄게." },
      { id: "sweet-dreams", text: "Sweet dreams!", ko: "좋은 꿈 꿔!" },
      { id: "good-night-again", text: "Good night!", ko: "잘 자요!" },
    ],
  },
  {
    id: "weather",
    title: "날씨 이야기",
    emoji: "⛅",
    sentences: [
      { id: "sunny-today", text: "It's sunny today.", ko: "오늘은 맑아요." },
      { id: "its-raining", text: "It's raining.", ko: "비가 와요." },
      { id: "its-snowing", text: "It's snowing!", ko: "눈이 와요!" },
      { id: "its-windy", text: "It's windy.", ko: "바람이 불어요." },
      { id: "hot-today", text: "It's hot today.", ko: "오늘 더워요." },
      { id: "cold-outside", text: "It's cold outside.", ko: "밖이 추워요." },
      { id: "bring-umbrella", text: "Bring an umbrella.", ko: "우산 챙기세요." },
      { id: "beautiful-day", text: "What a beautiful day!", ko: "날씨 정말 좋다!" },
    ],
  },
  {
    id: "self-intro",
    title: "자기소개",
    emoji: "🙋",
    sentences: [
      { id: "name-is-amy", text: "My name is Amy.", ko: "내 이름은 에이미예요." },
      { id: "seven-years-old", text: "I am seven years old.", ko: "나는 일곱 살이에요." },
      { id: "live-in-seoul", text: "I live in Seoul.", ko: "나는 서울에 살아요." },
      { id: "have-big-brother", text: "I have a big brother.", ko: "나는 형(오빠)이 있어요." },
      { id: "like-drawing", text: "I like drawing.", ko: "나는 그림 그리기를 좋아해요." },
      { id: "favorite-color", text: "My favorite color is blue.", ko: "내가 제일 좋아하는 색은 파란색이에요." },
      { id: "am-a-student", text: "I am a student.", ko: "나는 학생이에요." },
      { id: "nice-to-meet-you-too", text: "Nice to meet you too!", ko: "저도 만나서 반가워요!" },
    ],
  },
];
