// "기초 영어회화" 도구의 목차. 챕터 하나 = 상황 하나. 새 챕터는 이 배열에 항목만
// 추가하면 목차 화면과 화면 등록(index.js)에 자동으로 반영된다 — 다른 곳을 고칠 필요 없다.
//
// 일상대화 위주로 구성했다(어린이 애니메이션 참고, D-65) — 뽀로로/타요/페파피그류가 매번
// "아침에 일어나기", "친구랑 놀기", "밥 먹기", "잠자리" 같은 하루 일과 하나를 에피소드로
// 삼는 것과 같은 결. 단어 암기(This is a rabbit)보다 그 상황에서 실제로 주고받는 말
// (Let's play! / Can I have more?)을 우선했다.
//
// 챕터는 잘게 쪼개지 않고 묶는다(D-66) — 하루 일과처럼 시간 순으로 자연스럽게 이어지는
// 상황이나, 가족·자기소개처럼 소재가 겹치는 상황은 챕터 하나로 합쳐서 문항 수를 키운다.
// 새 상황이 생기면 새 챕터부터 만들지 말고, 기존 챕터 중 붙일 자리가 있는지 먼저 본다 —
// 챕터가 잘게 계속 늘어나면 목차 자체가 또 하나의 목록이 돼서 "하나의 공부 도구"라는
// 원래 취지(D-62·D-63)가 흐려진다.
//
// 문장에는 `level`이 있을 수 있다(D-70, D-71). 없으면 "기본"(입문 생존 표현), `"intermediate"`면
// "중급"(짧은 질문·요청 위주로 기본보다 조금 긴 문장), `"advanced"`면 "심화"(의견·이유·비교·협상이
// 들어간, 원어민 7세 정도의 문장). 각 챕터 안에서 기본을 전부 배열한 다음 중급, 심화 순으로
// 뒤에 잇는다 — 같은 상황을 계속 반복하며 단계만 올라가는 흐름이라, 단계용으로 새 챕터를 또
// 만들지 않는다. 챕터를 클릭하면 이 세 단계 중 하나를 고르는 화면이 먼저 뜬다(D-71) —
// screens.js의 renderLevelSelect. 진짜 다중 턴 대화(질문→대답→되묻기)는 이 앱의 "문장 하나
// 듣고 따라 말하기" 채점 구조와 안 맞아서 지금은 만들지 않는다 — 나중에 별도 대화형 도구로
// 다룰 계획(`docs/learning-architecture.md` §3-5).
export const LEVEL_LABELS = { basic: "기본", intermediate: "중급", advanced: "심화" };
export const CHAPTERS = [
  {
    id: "greeting",
    title: "인사 · 기분 표현",
    emoji: "👋",
    sentences: [
      { id: "hello", text: "Hello!", ko: "안녕!" },
      { id: "good-morning", text: "Good morning!", ko: "좋은 아침이에요!" },
      { id: "good-night", text: "Good night!", ko: "잘 자요!" },
      { id: "how-are-you", text: "How are you?", ko: "어떻게 지내요?" },
      { id: "happy", text: "I'm happy.", ko: "나는 기뻐요." },
      { id: "sad", text: "I'm sad.", ko: "나는 슬퍼요." },
      { id: "angry", text: "I'm angry.", ko: "나는 화나요." },
      { id: "tired", text: "I'm tired.", ko: "나는 피곤해요." },
      { id: "hungry", text: "I'm hungry.", ko: "나는 배고파요." },
      { id: "thirsty", text: "I'm thirsty.", ko: "나는 목말라요." },
      { id: "sleepy", text: "I'm sleepy.", ko: "나는 졸려요." },
      { id: "scared", text: "I'm scared.", ko: "나는 무서워요." },
      { id: "excited", text: "I'm excited.", ko: "나는 신나요." },
      { id: "surprised", text: "I'm surprised.", ko: "나는 놀랐어요." },
      { id: "bored", text: "I'm bored.", ko: "나는 심심해요." },
      { id: "okay", text: "I'm okay.", ko: "나는 괜찮아요." },
      { id: "nice-to-meet-you", text: "Nice to meet you.", ko: "만나서 반가워요." },
      { id: "whats-your-name", text: "What's your name?", ko: "이름이 뭐예요?" },
      { id: "my-name-is", text: "My name is Tom.", ko: "내 이름은 톰이에요." },
      { id: "see-you-later", text: "See you later!", ko: "나중에 봐요!" },
      { id: "see-you-tomorrow", text: "See you tomorrow!", ko: "내일 봐요!" },
      { id: "thank-you", text: "Thank you!", ko: "고마워요!" },
      { id: "youre-welcome", text: "You're welcome!", ko: "천만에요!" },
      { id: "sorry", text: "I'm sorry.", ko: "미안해요." },
      { id: "its-okay", text: "It's okay.", ko: "괜찮아요." },
      { id: "excuse-me", text: "Excuse me.", ko: "실례합니다." },
      { id: "please", text: "Please.", ko: "부탁해요." },
      { id: "yes", text: "Yes!", ko: "네!" },
      { id: "no", text: "No.", ko: "아니요." },
      { id: "bye", text: "Goodbye!", ko: "안녕히 가세요!" },
      { id: "how-was-your-day", text: "How was your day?", ko: "오늘 하루 어땠어요?", level: "intermediate" },
      { id: "im-doing-great", text: "I'm doing great today.", ko: "오늘 진짜 좋아요.", level: "intermediate" },
      { id: "whats-wrong", text: "What's wrong?", ko: "무슨 일이에요?", level: "intermediate" },
      { id: "i-had-a-good-dream", text: "I had a good dream.", ko: "좋은 꿈을 꿨어요.", level: "intermediate" },
      { id: "can-you-say-that-again", text: "Can you say that again?", ko: "다시 한번 말해줄래요?", level: "intermediate" },
      { id: "i-dont-understand", text: "I don't understand.", ko: "이해가 안 돼요.", level: "intermediate" },
      { id: "thats-a-good-idea", text: "That's a good idea!", ko: "그거 좋은 생각이에요!", level: "intermediate" },
      { id: "im-proud-of-you", text: "I'm proud of you.", ko: "네가 자랑스러워요.", level: "intermediate" },
      { id: "take-care", text: "Take care!", ko: "몸조심해요!", level: "intermediate" },
      { id: "have-a-nice-day", text: "Have a nice day!", ko: "좋은 하루 보내요!", level: "intermediate" },
      { id: "whats-the-matter", text: "What's the matter?", ko: "무슨 일 있어요?", level: "intermediate" },
      { id: "im-here-for-you", text: "I'm here for you.", ko: "내가 곁에 있을게요.", level: "intermediate" },
      { id: "how-do-you-feel-now", text: "How do you feel now?", ko: "지금 기분이 어때요?", level: "intermediate" },
      { id: "im-feeling-better", text: "I'm feeling better now.", ko: "이제 좀 나아졌어요.", level: "intermediate" },
      { id: "dont-worry-about-it", text: "Don't worry about it.", ko: "걱정하지 마세요.", level: "intermediate" },
      { id: "can-i-tell-you-a-secret", text: "Can I tell you a secret?", ko: "비밀 하나 말해줄까요?", level: "intermediate" },
      { id: "i-missed-you-today", text: "I missed you today.", ko: "오늘 보고 싶었어요.", level: "intermediate" },
      { id: "its-nice-to-see-you-again", text: "It's nice to see you again.", ko: "다시 만나서 반가워요.", level: "intermediate" },
      { id: "how-have-you-been", text: "How have you been?", ko: "그동안 잘 지냈어요?", level: "intermediate" },
      { id: "long-time-no-see", text: "Long time no see!", ko: "오랜만이에요!", level: "intermediate" },
      { id: "whats-new", text: "What's new?", ko: "뭐 새로운 거 있어요?", level: "intermediate" },
      { id: "nothing-much", text: "Nothing much.", ko: "별일 없어요.", level: "intermediate" },
      { id: "can-i-sit-next-to-you", text: "Can I sit next to you?", ko: "옆에 앉아도 돼요?", level: "intermediate" },
      { id: "i-had-a-bad-day", text: "I had a bad day.", ko: "오늘 힘든 하루였어요.", level: "intermediate" },
      { id: "thanks-for-helping-me", text: "Thanks for helping me.", ko: "도와줘서 고마워요.", level: "intermediate" },
      { id: "sorry-im-late", text: "Sorry I'm late.", ko: "늦어서 미안해요.", level: "intermediate" },
      { id: "no-problem-at-all", text: "No problem at all!", ko: "전혀 문제없어요!", level: "intermediate" },
      { id: "see-you-soon", text: "See you soon!", ko: "곧 봐요!", level: "intermediate" },
      { id: "take-your-time", text: "Take your time.", ko: "천천히 해요.", level: "intermediate" },
      { id: "im-glad-youre-here", text: "I'm glad you're here.", ko: "네가 여기 있어서 좋아요.", level: "intermediate" },
      { id: "happy-because", text: "I'm happy because it's my birthday.", ko: "오늘 제 생일이라서 기뻐요.", level: "advanced" },
      { id: "little-nervous", text: "I feel a little nervous.", ko: "조금 긴장돼요.", level: "advanced" },
      { id: "dont-feel-good", text: "I don't feel good today.", ko: "오늘 몸이 안 좋아요.", level: "advanced" },
      { id: "why-are-you-sad", text: "Why are you sad?", ko: "왜 슬퍼요?", level: "advanced" },
      { id: "not-angry-anymore", text: "I'm not angry anymore.", ko: "이제 화 안 났어요.", level: "advanced" },
      { id: "made-me-happy", text: "That made me really happy.", ko: "그거 때문에 진짜 기뻤어요.", level: "advanced" },
      { id: "happy-and-excited", text: "I feel happy and excited at the same time!", ko: "기쁘고 신나는 게 동시에 느껴져요!", level: "advanced" },
      { id: "shy-around-new-people", text: "I'm a little shy around new people.", ko: "새로운 사람들 앞에서는 조금 수줍어요.", level: "advanced" },
      { id: "scared-but-now-okay", text: "I was scared, but now I'm okay.", ko: "무서웠는데 이제는 괜찮아요.", level: "advanced" },
      { id: "can-we-talk-about-it", text: "Can we talk about it?", ko: "그거에 대해 이야기해볼까요?", level: "advanced" },
      { id: "dont-want-to-talk-right-now", text: "I don't want to talk right now.", ko: "지금은 말하고 싶지 않아요.", level: "advanced" },
      { id: "it-helps-when-you-listen", text: "It helps when you listen to me.", ko: "내 말을 들어주면 도움이 돼요.", level: "advanced" },
      { id: "i-was-worried-about-you", text: "I was worried about you.", ko: "당신이 걱정됐어요.", level: "advanced" },
      { id: "everyone-feels-sad-sometimes", text: "Everyone feels sad sometimes.", ko: "누구나 가끔 슬플 때가 있어요.", level: "advanced" },
      { id: "feel-better-when-i-talk-about-it", text: "I feel better when I talk about it.", ko: "이야기하면 기분이 나아져요.", level: "advanced" },
      { id: "sorry-i-hurt-your-feelings", text: "I'm sorry I hurt your feelings.", ko: "마음 상하게 해서 미안해요.", level: "advanced" },
      { id: "i-forgive-you", text: "I forgive you.", ko: "용서할게요.", level: "advanced" },
      { id: "lets-be-friends-again", text: "Let's be friends again.", ko: "우리 다시 친구하자.", level: "advanced" },
      { id: "i-was-just-joking", text: "I was just joking.", ko: "그냥 농담이었어요.", level: "advanced" },
      { id: "that-wasnt-very-nice", text: "That wasn't very nice.", ko: "그건 별로 좋지 않았어요.", level: "advanced" },
      { id: "can-you-explain-why", text: "Can you explain why?", ko: "왜 그런지 설명해줄래요?", level: "advanced" },
      { id: "i-understand-how-you-feel", text: "I understand how you feel.", ko: "그 기분 이해해요.", level: "advanced" },
      { id: "feel-proud-of-myself", text: "I feel proud of myself.", ko: "제 자신이 자랑스러워요.", level: "advanced" },
      { id: "made-me-a-little-sad", text: "It made me a little sad.", ko: "그것 때문에 좀 슬펐어요.", level: "advanced" },
      { id: "more-excited-than-scared", text: "I was more excited than scared.", ko: "무서운 것보다 신나는 게 더 컸어요.", level: "advanced" },
      { id: "lets-talk-about-something-happy", text: "Let's talk about something happy.", ko: "즐거운 이야기를 해보자.", level: "advanced" },
      { id: "hope-you-feel-better-soon", text: "I hope you feel better soon.", ko: "빨리 나아지길 바라요.", level: "advanced" },
      { id: "thank-you-for-understanding", text: "Thank you for understanding.", ko: "이해해줘서 고마워요.", level: "advanced" },
      { id: "i-changed-my-mind", text: "I changed my mind.", ko: "마음이 바뀌었어요.", level: "advanced" },
      { id: "not-angry-just-surprised", text: "I'm not angry, I was just surprised.", ko: "화난 게 아니라 그냥 놀랐던 거예요.", level: "advanced" },
    ],
  },
  {
    // 옛 morning-routine + meal-time + bath-bedtime을 하나로. 아침에 일어나서 밥 먹고
    // 놀다가 씻고 잠드는 하루 흐름을 그대로 시간순으로 이었다.
    id: "daily-routine",
    title: "하루 일과",
    emoji: "🌅",
    sentences: [
      { id: "wake-up", text: "Wake up!", ko: "일어나요!" },
      { id: "brush-teeth", text: "Let's brush our teeth.", ko: "이 닦자." },
      { id: "wash-face", text: "Wash your face.", ko: "세수하세요." },
      { id: "get-dressed", text: "Get dressed!", ko: "옷 입자!" },
      { id: "eat-breakfast", text: "Let's eat breakfast.", ko: "아침 먹자." },
      { id: "wheres-my-shoes", text: "Where are my shoes?", ko: "내 신발 어디 있어요?" },
      { id: "im-ready", text: "I'm ready!", ko: "준비 다 됐어요!" },
      { id: "lets-go", text: "Let's go!", ko: "가자!" },
      { id: "im-hungry", text: "I'm hungry.", ko: "배고파요." },
      { id: "lets-eat", text: "Let's eat!", ko: "먹자!" },
      { id: "this-is-yummy", text: "This is yummy!", ko: "이거 맛있어요!" },
      { id: "i-dont-like-this", text: "I don't like this.", ko: "이거 안 좋아해요." },
      { id: "can-i-have-more", text: "Can I have more?", ko: "더 먹어도 돼요?" },
      { id: "can-i-have-a-cookie", text: "Can I have a cookie?", ko: "쿠키 먹어도 돼요?" },
      { id: "want-milk", text: "I want milk.", ko: "우유 주세요." },
      { id: "want-juice", text: "I want juice.", ko: "주스 주세요." },
      { id: "want-water", text: "I want water.", ko: "물 주세요." },
      { id: "im-full", text: "I'm full.", ko: "배불러요." },
      { id: "cheers", text: "Cheers!", ko: "건배!" },
      { id: "thank-you-for-the-food", text: "Thank you for the food.", ko: "잘 먹겠습니다." },
      { id: "bath-time", text: "Bath time!", ko: "목욕할 시간이에요!" },
      { id: "water-is-warm", text: "The water is warm.", ko: "물이 따뜻해요." },
      { id: "wash-your-hair", text: "Let's wash your hair.", ko: "머리 감자." },
      { id: "put-on-pajamas", text: "Put on your pajamas.", ko: "잠옷 입자." },
      { id: "brush-teeth-again", text: "Brush your teeth.", ko: "이 닦자." },
      { id: "bedtime-story", text: "Let's read a bedtime story.", ko: "자기 전에 책 읽어 줄게." },
      { id: "sweet-dreams", text: "Sweet dreams!", ko: "좋은 꿈 꿔!" },
      { id: "good-night-again", text: "Good night!", ko: "잘 자요!" },
      { id: "wash-your-hands", text: "Wash your hands.", ko: "손을 씻자." },
      { id: "cover-your-mouth", text: "Cover your mouth.", ko: "입을 가리세요." },
      { id: "go-potty", text: "I need to go potty.", ko: "화장실 가고 싶어요." },
      { id: "wipe-your-mouth", text: "Wipe your mouth.", ko: "입을 닦자." },
      { id: "time-to-wake-up", text: "It's time to wake up.", ko: "일어날 시간이에요.", level: "intermediate" },
      { id: "did-you-sleep-well", text: "Did you sleep well?", ko: "잘 잤어요?", level: "intermediate" },
      { id: "what-do-you-want-for-breakfast", text: "What do you want for breakfast?", ko: "아침으로 뭐 먹고 싶어요?", level: "intermediate" },
      { id: "hurry-up-were-late", text: "Hurry up, we're late.", ko: "서둘러요, 늦었어요.", level: "intermediate" },
      { id: "can-you-pass-the-spoon", text: "Can you pass me the spoon?", ko: "숟가락 좀 건네줄래요?", level: "intermediate" },
      { id: "i-need-to-wash-my-hands-first", text: "I need to wash my hands first.", ko: "먼저 손을 씻어야 해요.", level: "intermediate" },
      { id: "lets-pick-out-your-clothes", text: "Let's pick out your clothes.", ko: "옷을 골라보자.", level: "intermediate" },
      { id: "its-almost-bedtime", text: "It's almost bedtime.", ko: "이제 잘 시간이 다 됐어요.", level: "intermediate" },
      { id: "did-you-brush-your-teeth", text: "Did you brush your teeth?", ko: "이 닦았어요?", level: "intermediate" },
      { id: "the-water-is-too-hot", text: "The water is too hot.", ko: "물이 너무 뜨거워요.", level: "intermediate" },
      { id: "lets-turn-off-the-light", text: "Let's turn off the light.", ko: "불을 끄자.", level: "intermediate" },
      { id: "one-more-story-please", text: "One more story, please.", ko: "이야기 하나만 더 해주세요.", level: "intermediate" },
      { id: "can-you-help-me-get-dressed", text: "Can you help me get dressed?", ko: "옷 입는 거 도와줄래요?", level: "intermediate" },
      { id: "cant-find-my-socks", text: "I can't find my socks.", ko: "양말을 못 찾겠어요.", level: "intermediate" },
      { id: "lets-make-the-bed", text: "Let's make the bed.", ko: "침대 정리하자.", level: "intermediate" },
      { id: "what-time-is-it", text: "What time is it?", ko: "지금 몇 시예요?", level: "intermediate" },
      { id: "we-need-to-leave-soon", text: "We need to leave soon.", ko: "우리 곧 출발해야 해요.", level: "intermediate" },
      { id: "can-i-have-seconds", text: "Can I have seconds?", ko: "한 그릇 더 먹어도 돼요?", level: "intermediate" },
      { id: "is-dinner-ready-yet", text: "Is dinner ready yet?", ko: "저녁 아직 안 됐어요?", level: "intermediate" },
      { id: "lets-set-the-table", text: "Let's set the table.", ko: "상 차리자.", level: "intermediate" },
      { id: "can-you-cut-this-for-me", text: "Can you cut this for me?", ko: "이거 잘라줄래요?", level: "intermediate" },
      { id: "i-spilled-my-water", text: "I spilled my water.", ko: "물을 쏟았어요.", level: "intermediate" },
      { id: "lets-dry-off-first", text: "Let's dry off first.", ko: "먼저 몸부터 말리자.", level: "intermediate" },
      { id: "can-i-pick-my-pajamas", text: "Can I pick my pajamas?", ko: "잠옷 제가 골라도 돼요?", level: "intermediate" },
      { id: "lets-turn-down-the-bed", text: "Let's turn down the bed.", ko: "이불 펴자.", level: "intermediate" },
      { id: "can-you-tuck-me-in", text: "Can you tuck me in?", ko: "이불 덮어줄래요?", level: "intermediate" },
      { id: "i-need-a-nightlight", text: "I need a nightlight.", ko: "취침등이 필요해요.", level: "intermediate" },
      { id: "lets-hang-up-your-towel", text: "Let's hang up your towel.", ko: "수건 걸어놓자.", level: "intermediate" },
      { id: "did-you-wash-behind-your-ears", text: "Did you wash behind your ears?", ko: "귀 뒤도 씻었어요?", level: "intermediate" },
      { id: "lets-check-tomorrows-weather", text: "Let's check tomorrow's weather.", ko: "내일 날씨 확인해보자.", level: "intermediate" },
      { id: "watch-tv-after", text: "Can I watch TV after breakfast?", ko: "아침 먹고 티비 봐도 돼요?", level: "advanced" },
      { id: "dont-want-bath-yet", text: "I don't want to take a bath yet.", ko: "아직 목욕하기 싫어요.", level: "advanced" },
      { id: "five-more-minutes", text: "Just five more minutes, please.", ko: "딱 5분만 더요.", level: "advanced" },
      { id: "already-brushed", text: "I already brushed my teeth.", ko: "저 이미 이 닦았어요.", level: "advanced" },
      { id: "whats-for-dinner", text: "What's for dinner tonight?", ko: "오늘 저녁 뭐예요?", level: "advanced" },
      { id: "clean-up-first", text: "I'll clean up my toys first.", ko: "장난감부터 치울게요.", level: "advanced" },
      { id: "woke-up-because-of-a-noise", text: "I woke up because of a loud noise.", ko: "시끄러운 소리 때문에 깼어요.", level: "advanced" },
      { id: "can-i-sleep-a-little-longer", text: "Can I sleep a little longer?", ko: "조금만 더 자도 돼요?", level: "advanced" },
      { id: "picked-this-shirt-because-i-like-it", text: "I picked this shirt because I like the color.", ko: "색깔이 마음에 들어서 이 옷을 골랐어요.", level: "advanced" },
      { id: "breakfast-is-the-best-meal", text: "I think breakfast is the best meal.", ko: "저는 아침이 제일 좋은 식사인 것 같아요.", level: "advanced" },
      { id: "dont-like-vegetables-but-eat-them", text: "I don't like vegetables, but I eat them anyway.", ko: "채소는 안 좋아하지만 그래도 먹어요.", level: "advanced" },
      { id: "can-we-eat-outside-today", text: "Can we eat outside today?", ko: "오늘 밖에서 먹어도 돼요?", level: "advanced" },
      { id: "helped-set-the-table-today", text: "I helped set the table today.", ko: "오늘 상 차리는 거 도왔어요.", level: "advanced" },
      { id: "soup-too-hot-to-eat", text: "The soup is too hot to eat right now.", ko: "국이 너무 뜨거워서 지금은 못 먹겠어요.", level: "advanced" },
      { id: "want-a-bubble-bath-tonight", text: "I want a bubble bath tonight.", ko: "오늘 밤엔 거품 목욕 하고 싶어요.", level: "advanced" },
      { id: "can-wash-my-own-hair-now", text: "I can wash my own hair now.", ko: "이제 제가 머리를 감을 수 있어요.", level: "advanced" },
      { id: "dont-want-to-sleep-not-tired", text: "I don't want to go to bed because I'm not tired.", ko: "안 졸려서 자기 싫어요.", level: "advanced" },
      { id: "can-we-read-two-stories-tonight", text: "Can we read two stories tonight?", ko: "오늘 밤엔 이야기 두 개 읽어도 돼요?", level: "advanced" },
      { id: "had-a-scary-dream-last-night", text: "I had a scary dream last night.", ko: "어젯밤에 무서운 꿈을 꿨어요.", level: "advanced" },
      { id: "can-you-leave-the-door-open", text: "Can you leave the door open a little?", ko: "문을 조금 열어놔줄래요?", level: "advanced" },
      { id: "finished-breakfast-by-myself", text: "I finished my breakfast all by myself.", ko: "아침을 혼자서 다 먹었어요.", level: "advanced" },
      { id: "should-brush-longer", text: "I think I should brush my teeth longer.", ko: "이 좀 더 오래 닦아야 할 것 같아요.", level: "advanced" },
      { id: "can-we-have-pancakes-instead", text: "Can we have pancakes instead?", ko: "대신 팬케이크 먹으면 안 돼요?", level: "advanced" },
      { id: "want-to-choose-my-own-clothes-today", text: "I want to choose my own clothes today.", ko: "오늘은 제가 옷을 고르고 싶어요.", level: "advanced" },
      { id: "getting-ready-faster-than-yesterday", text: "I'm getting ready faster than yesterday.", ko: "어제보다 더 빨리 준비하고 있어요.", level: "advanced" },
      { id: "can-i-stay-up-a-little-later-tonight", text: "Can I stay up a little later tonight?", ko: "오늘 밤엔 조금만 더 늦게 자도 돼요?", level: "advanced" },
      { id: "promise-ill-clean-up-after-dinner", text: "I promise I'll clean up after dinner.", ko: "저녁 먹고 꼭 치울게요.", level: "advanced" },
      { id: "water-was-cold-then-warm", text: "The water was cold at first, but then it got warm.", ko: "물이 처음엔 차가웠는데 나중엔 따뜻해졌어요.", level: "advanced" },
      { id: "like-getting-ready-for-bed-with-you", text: "I like getting ready for bed with you.", ko: "당신이랑 같이 잘 준비하는 게 좋아요.", level: "advanced" },
      { id: "can-we-make-breakfast-together-tomorrow", text: "Can we make breakfast together tomorrow?", ko: "내일은 같이 아침 만들어도 돼요?", level: "advanced" },
    ],
  },
  {
    // 옛 self-intro + family를 하나로. 나를 소개하는 문장과 우리 가족을 소개하는 문장은
    // 소재가 이어져 있어 굳이 나눌 이유가 없었다.
    id: "family-and-me",
    title: "가족 · 자기소개",
    emoji: "👨‍👩‍👧",
    sentences: [
      { id: "name-is-amy", text: "My name is Amy.", ko: "내 이름은 에이미예요." },
      { id: "seven-years-old", text: "I am seven years old.", ko: "나는 일곱 살이에요." },
      { id: "live-in-seoul", text: "I live in Seoul.", ko: "나는 서울에 살아요." },
      { id: "like-drawing", text: "I like drawing.", ko: "나는 그림 그리기를 좋아해요." },
      { id: "like-singing", text: "I like singing.", ko: "나는 노래하기를 좋아해요." },
      { id: "like-soccer", text: "I like soccer.", ko: "나는 축구를 좋아해요." },
      { id: "like-ice-cream", text: "I like ice cream.", ko: "나는 아이스크림을 좋아해요." },
      { id: "favorite-color", text: "My favorite color is blue.", ko: "내가 제일 좋아하는 색은 파란색이에요." },
      { id: "am-a-student", text: "I am a student.", ko: "나는 학생이에요." },
      { id: "nice-to-meet-you-too", text: "Nice to meet you too!", ko: "저도 만나서 반가워요!" },
      { id: "this-is-mom", text: "This is my mom.", ko: "이 사람은 우리 엄마예요." },
      { id: "this-is-dad", text: "This is my dad.", ko: "이 사람은 우리 아빠예요." },
      { id: "this-is-sister", text: "This is my sister.", ko: "이 사람은 우리 언니(누나)예요." },
      { id: "this-is-grandpa", text: "This is my grandpa.", ko: "이 사람은 우리 할아버지예요." },
      { id: "have-big-brother", text: "I have a big brother.", ko: "나는 형(오빠)이 있어요." },
      { id: "wheres-grandma", text: "Where is grandma?", ko: "할머니 어디 계세요?" },
      { id: "i-love-you", text: "I love you.", ko: "사랑해요." },
      { id: "i-miss-you", text: "I miss you.", ko: "보고 싶어요." },
      { id: "give-me-a-hug", text: "Give me a hug.", ko: "안아 주세요." },
      { id: "can-you-help-me", text: "Can you help me?", ko: "도와줄 수 있어요?" },
      { id: "read-together", text: "Let's read a book together.", ko: "같이 책 읽자." },
      { id: "color-red", text: "It's red.", ko: "빨간색이에요." },
      { id: "color-yellow", text: "It's yellow.", ko: "노란색이에요." },
      { id: "color-green", text: "It's green.", ko: "초록색이에요." },
      { id: "have-a-dog", text: "I have a dog.", ko: "나는 강아지가 있어요." },
      { id: "have-a-cat", text: "I have a cat.", ko: "나는 고양이가 있어요." },
      { id: "my-birthday", text: "My birthday is in May.", ko: "내 생일은 5월이에요." },
      { id: "go-to-school", text: "I go to school.", ko: "나는 학교에 다녀요." },
      { id: "this-is-my-toy", text: "This is my toy.", ko: "이건 내 장난감이에요." },
      { id: "hair-is-black", text: "My hair is black.", ko: "내 머리는 까매요." },
      { id: "how-old-are-you", text: "How old are you?", ko: "몇 살이에요?", level: "intermediate" },
      { id: "where-do-you-live", text: "Where do you live?", ko: "어디 살아요?", level: "intermediate" },
      { id: "do-you-have-any-siblings", text: "Do you have any siblings?", ko: "형제자매 있어요?", level: "intermediate" },
      { id: "my-mom-is-a-teacher", text: "My mom is a teacher.", ko: "우리 엄마는 선생님이에요.", level: "intermediate" },
      { id: "my-dad-works-hard", text: "My dad works hard.", ko: "우리 아빠는 열심히 일해요.", level: "intermediate" },
      { id: "i-am-the-youngest", text: "I am the youngest.", ko: "나는 막내예요.", level: "intermediate" },
      { id: "whats-your-favorite-food", text: "What's your favorite food?", ko: "제일 좋아하는 음식이 뭐예요?", level: "intermediate" },
      { id: "i-want-to-learn-piano", text: "I want to learn piano.", ko: "저는 피아노를 배우고 싶어요.", level: "intermediate" },
      { id: "can-we-visit-grandma", text: "Can we visit grandma this weekend?", ko: "이번 주말에 할머니 댁 가도 돼요?", level: "intermediate" },
      { id: "my-family-is-important-to-me", text: "My family is important to me.", ko: "우리 가족은 저한테 중요해요.", level: "intermediate" },
      { id: "i-look-just-like-my-dad", text: "I look just like my dad.", ko: "저는 아빠를 꼭 닮았어요.", level: "intermediate" },
      { id: "do-you-like-my-drawing", text: "Do you like my drawing?", ko: "내 그림 마음에 들어요?", level: "intermediate" },
      { id: "whats-your-favorite-subject", text: "What's your favorite subject at school?", ko: "제일 좋아하는 과목이 뭐예요?", level: "intermediate" },
      { id: "have-two-best-friends", text: "I have two best friends.", ko: "저는 가장 친한 친구가 두 명 있어요.", level: "intermediate" },
      { id: "grandpa-tells-funny-stories", text: "My grandpa tells funny stories.", ko: "할아버지는 재밌는 이야기를 해주세요.", level: "intermediate" },
      { id: "do-you-have-a-pet", text: "Do you have a pet?", ko: "반려동물 있어요?", level: "intermediate" },
      { id: "what-does-your-mom-do", text: "What does your mom do?", ko: "엄마는 무슨 일을 하세요?", level: "intermediate" },
      { id: "i-want-to-show-you-something", text: "I want to show you something.", ko: "보여줄 게 있어요.", level: "intermediate" },
      { id: "can-i-invite-my-friend-over", text: "Can I invite my friend over?", ko: "제 친구 초대해도 돼요?", level: "intermediate" },
      { id: "sister-and-i-share-a-room", text: "My sister and I share a room.", ko: "언니(누나)랑 저는 방을 같이 써요.", level: "intermediate" },
      { id: "whats-your-family-like", text: "What's your family like?", ko: "가족이 어떤 사람들이에요?", level: "intermediate" },
      { id: "i-help-my-mom-at-home", text: "I help my mom at home.", ko: "저는 집에서 엄마를 도와요.", level: "intermediate" },
      { id: "do-you-live-near-here", text: "Do you live near here?", ko: "여기 근처에 살아요?", level: "intermediate" },
      { id: "uncle-visits-us-a-lot", text: "My uncle visits us a lot.", ko: "삼촌이 우리집에 자주 와요.", level: "intermediate" },
      { id: "whats-your-last-name", text: "What's your last name?", ko: "성이 뭐예요?", level: "intermediate" },
      { id: "born-in-seoul", text: "I was born in Seoul.", ko: "저는 서울에서 태어났어요.", level: "intermediate" },
      { id: "can-you-tell-me-about-your-family", text: "Can you tell me about your family?", ko: "가족에 대해 얘기해줄래요?", level: "intermediate" },
      { id: "cousin-same-age-as-me", text: "My cousin is the same age as me.", ko: "사촌이 저랑 동갑이에요.", level: "intermediate" },
      { id: "eat-dinner-together-every-day", text: "We eat dinner together every day.", ko: "우리는 매일 같이 저녁을 먹어요.", level: "intermediate" },
      { id: "family-likes-camping", text: "My family likes to go camping.", ko: "우리 가족은 캠핑 가는 걸 좋아해요.", level: "intermediate" },
      { id: "dogs-cuter", text: "I think dogs are cuter than cats.", ko: "저는 강아지가 고양이보다 더 귀여운 것 같아요.", level: "advanced" },
      { id: "brother-older", text: "My brother is older than me.", ko: "형(오빠)이 저보다 나이가 많아요.", level: "advanced" },
      { id: "want-to-be-doctor", text: "I want to be a doctor when I grow up.", ko: "저는 커서 의사가 되고 싶어요.", level: "advanced" },
      { id: "good-at-drawing-not-singing", text: "I'm good at drawing, but not at singing.", ko: "저는 그림은 잘 그리는데 노래는 못해요.", level: "advanced" },
      { id: "guess-how-old", text: "Can you guess how old I am?", ko: "제가 몇 살인지 맞혀보세요.", level: "advanced" },
      { id: "look-like-mom", text: "I look like my mom.", ko: "저는 엄마를 닮았어요.", level: "advanced" },
      { id: "more-like-mom-than-dad", text: "I think I'm more like my mom than my dad.", ko: "저는 아빠보다 엄마를 더 닮은 것 같아요.", level: "advanced" },
      { id: "sister-and-i-dont-always-agree", text: "My sister and I don't always agree.", ko: "언니(누나)랑 저는 항상 의견이 같지는 않아요.", level: "advanced" },
      { id: "want-a-little-sibling", text: "I want a little brother or sister.", ko: "저는 동생이 있었으면 좋겠어요.", level: "advanced" },
      { id: "parents-met-a-long-time-ago", text: "My parents met a long time ago.", ko: "부모님은 오래 전에 만나셨어요.", level: "advanced" },
      { id: "help-because-i-love-my-family", text: "I help because I love my family.", ko: "가족을 사랑해서 도와요.", level: "advanced" },
      { id: "grandma-best-cook-i-know", text: "My grandma is the best cook I know.", ko: "할머니가 제가 아는 사람 중에 요리를 제일 잘해요.", level: "advanced" },
      { id: "look-like-dad-act-like-mom", text: "I look more like my dad, but I act like my mom.", ko: "얼굴은 아빠를 닮았는데 성격은 엄마를 닮았어요.", level: "advanced" },
      { id: "fight-sometimes-still-love", text: "My brother and I fight sometimes, but we still love each other.", ko: "형(오빠)이랑 가끔 싸우지만 그래도 서로 사랑해요.", level: "advanced" },
      { id: "want-to-be-just-like-dad", text: "I want to be just like my dad someday.", ko: "저는 언젠가 아빠처럼 되고 싶어요.", level: "advanced" },
      { id: "family-small-but-enough", text: "My family is small, but it's enough for me.", ko: "우리 가족은 작지만 저한테는 충분해요.", level: "advanced" },
      { id: "big-family-would-be-fun", text: "I think having a big family would be fun.", ko: "대가족이면 재밌을 것 같아요.", level: "advanced" },
      { id: "mom-says-im-just-like-her", text: "My mom says I'm just like her when she was young.", ko: "엄마는 제가 어릴 때 엄마랑 똑같대요.", level: "advanced" },
      { id: "can-do-more-by-myself-now", text: "I can do more things by myself now.", ko: "이제 혼자 할 수 있는 게 많아졌어요.", level: "advanced" },
      { id: "want-to-learn-what-dad-does", text: "I want to learn what my dad does at work.", ko: "아빠가 회사에서 뭘 하는지 배우고 싶어요.", level: "advanced" },
      { id: "favorite-thing-we-laugh-a-lot", text: "My favorite thing about my family is that we laugh a lot.", ko: "우리 가족의 제일 좋은 점은 많이 웃는다는 거예요.", level: "advanced" },
      { id: "good-at-taking-care-of-cousin", text: "I think I'm good at taking care of my little cousin.", ko: "저는 어린 사촌을 잘 돌보는 것 같아요.", level: "advanced" },
      { id: "different-but-still-a-family", text: "Even though we're different, we're still a family.", ko: "서로 다르지만 우리는 여전히 가족이에요.", level: "advanced" },
      { id: "grandpa-older-than-grandma", text: "My grandpa is older than my grandma.", ko: "할아버지가 할머니보다 나이가 많아요.", level: "advanced" },
      { id: "share-toys-with-siblings", text: "I share my toys with my siblings.", ko: "저는 형제자매랑 장난감을 나눠 써요.", level: "advanced" },
      { id: "parents-work-hard-for-us", text: "My parents work hard so we can have a good life.", ko: "부모님은 우리가 잘 지낼 수 있도록 열심히 일하세요.", level: "advanced" },
      { id: "family-understands-me-the-best", text: "I think my family understands me the best.", ko: "우리 가족이 저를 제일 잘 이해하는 것 같아요.", level: "advanced" },
      { id: "would-choose-my-family-again", text: "I would choose my family again if I could.", ko: "다시 태어나도 우리 가족을 선택할 거예요.", level: "advanced" },
      { id: "cousin-copies-everything-i-do", text: "My little cousin copies everything I do.", ko: "사촌 동생이 제가 하는 걸 다 따라해요.", level: "advanced" },
      { id: "being-part-of-family-makes-me-happy", text: "Being part of this family makes me happy.", ko: "이 가족의 일원인 게 저를 행복하게 해요.", level: "advanced" },
    ],
  },
  {
    // 옛 playing-with-friends + weather를 하나로. 밖에서 노는 동안 날씨 얘기가 자연스럽게
    // 섞여 나오는 상황이라 같이 뒀다.
    id: "playground",
    title: "놀이터에서",
    emoji: "🎈",
    sentences: [
      { id: "lets-play", text: "Let's play!", ko: "같이 놀자!" },
      { id: "can-i-play-too", text: "Can I play too?", ko: "나도 같이 놀아도 돼요?" },
      { id: "my-turn", text: "It's my turn!", ko: "내 차례예요!" },
      { id: "watch-this", text: "Watch this!", ko: "이거 봐!" },
      { id: "so-much-fun", text: "That's so much fun!", ko: "진짜 재밌다!" },
      { id: "lets-be-friends", text: "Let's be friends.", ko: "우리 친구하자." },
      { id: "can-i-borrow-this", text: "Can I borrow this?", ko: "이거 빌려도 돼요?" },
      { id: "lets-share", text: "Let's share.", ko: "같이 나눠 쓰자." },
      { id: "tag-youre-it", text: "Tag, you're it!", ko: "잡았다, 네 차례야!" },
      { id: "lets-race", text: "Let's race!", ko: "우리 달리기 하자!" },
      { id: "lets-play-tag", text: "Let's play tag.", ko: "우리 술래잡기 하자." },
      { id: "lets-play-hide-and-seek", text: "Let's play hide and seek.", ko: "우리 숨바꼭질 하자." },
      { id: "lets-play-soccer", text: "Let's play soccer.", ko: "우리 축구하자." },
      { id: "sunny-today", text: "It's sunny today.", ko: "오늘은 맑아요." },
      { id: "its-raining", text: "It's raining.", ko: "비가 와요." },
      { id: "its-snowing", text: "It's snowing!", ko: "눈이 와요!" },
      { id: "its-windy", text: "It's windy.", ko: "바람이 불어요." },
      { id: "hot-today", text: "It's hot today.", ko: "오늘 더워요." },
      { id: "cold-outside", text: "It's cold outside.", ko: "밖이 추워요." },
      { id: "cloudy-today", text: "It's cloudy today.", ko: "오늘 흐려요." },
      { id: "bring-umbrella", text: "Bring an umbrella.", ko: "우산 챙기세요." },
      { id: "beautiful-day", text: "What a beautiful day!", ko: "날씨 정말 좋다!" },
      { id: "go-to-the-park", text: "Can we go to the park?", ko: "우리 공원 가도 돼요?" },
      { id: "want-to-swing", text: "I want to swing.", ko: "그네 타고 싶어요." },
      { id: "build-sandcastle", text: "Let's build a sandcastle.", ko: "모래성 만들자." },
      { id: "one-two-three-go", text: "One, two, three, go!", ko: "하나, 둘, 셋, 출발!" },
      { id: "look-at-that", text: "Look at that!", ko: "저것 좀 봐!" },
      { id: "im-it", text: "I'm it!", ko: "내가 술래야!" },
      { id: "can-i-go-on-the-slide", text: "Can I go on the slide?", ko: "미끄럼틀 타도 돼요?" },
      { id: "lets-climb-up-here", text: "Let's climb up here.", ko: "여기 올라가자." },
      { id: "can-i-join-you", text: "Can I join you?", ko: "나도 같이 껴도 돼요?", level: "intermediate" },
      { id: "whose-turn-is-it", text: "Whose turn is it?", ko: "누구 차례예요?", level: "intermediate" },
      { id: "lets-play-together", text: "Let's play together.", ko: "같이 놀자.", level: "intermediate" },
      { id: "be-careful", text: "Be careful!", ko: "조심해요!", level: "intermediate" },
      { id: "are-you-okay", text: "Are you okay?", ko: "괜찮아요?", level: "intermediate" },
      { id: "that-was-close", text: "That was close!", ko: "아슬아슬했다!", level: "intermediate" },
      { id: "can-you-push-me-on-the-swing", text: "Can you push me on the swing?", ko: "그네 좀 밀어줄래요?", level: "intermediate" },
      { id: "lets-go-down-the-slide-together", text: "Let's go down the slide together.", ko: "같이 미끄럼틀 타자.", level: "intermediate" },
      { id: "i-need-a-break", text: "I need a break.", ko: "저 좀 쉴게요.", level: "intermediate" },
      { id: "should-we-bring-a-snack", text: "Should we bring a snack?", ko: "간식 챙겨갈까요?", level: "intermediate" },
      { id: "the-sun-is-so-bright", text: "The sun is so bright.", ko: "햇빛이 진짜 밝다.", level: "intermediate" },
      { id: "lets-play-here-again-next-time", text: "Let's play here again next time.", ko: "다음에 또 여기서 놀자.", level: "intermediate" },
      { id: "can-we-play-a-different-game", text: "Can we play a different game?", ko: "다른 게임 하면 안 돼요?", level: "intermediate" },
      { id: "lets-count-to-ten", text: "Let's count to ten.", ko: "열까지 세자.", level: "intermediate" },
      { id: "who-wants-to-go-first", text: "Who wants to go first?", ko: "누가 먼저 할래요?", level: "intermediate" },
      { id: "i-can-do-it-by-myself", text: "I can do it by myself.", ko: "저 혼자 할 수 있어요.", level: "intermediate" },
      { id: "can-you-catch-me", text: "Can you catch me?", ko: "저 좀 잡아줄래요?", level: "intermediate" },
      { id: "lets-play-on-the-seesaw", text: "Let's play on the seesaw.", ko: "시소 타자.", level: "intermediate" },
      { id: "can-we-stay-a-little-longer", text: "Can we stay a little longer?", ko: "조금만 더 있어도 돼요?", level: "intermediate" },
      { id: "i-want-to-try-that-too", text: "I want to try that too.", ko: "저도 그거 해보고 싶어요.", level: "intermediate" },
      { id: "lets-make-a-team", text: "Let's make a team.", ko: "우리 팀 만들자.", level: "intermediate" },
      { id: "can-i-have-a-turn-next", text: "Can I have a turn next?", ko: "다음엔 제 차례예요?", level: "intermediate" },
      { id: "lets-go-a-little-higher", text: "Let's go a little higher.", ko: "조금 더 높이 가자.", level: "intermediate" },
      { id: "is-it-my-turn-yet", text: "Is it my turn yet?", ko: "이제 제 차례예요?", level: "intermediate" },
      { id: "lets-play-something-new", text: "Let's play something new.", ko: "새로운 거 하자.", level: "intermediate" },
      { id: "can-we-bring-our-bikes-next-time", text: "Can we bring our bikes next time?", ko: "다음엔 자전거 가져와도 돼요?", level: "intermediate" },
      { id: "lets-clean-up-before-we-go", text: "Let's clean up before we go.", ko: "가기 전에 정리하자.", level: "intermediate" },
      { id: "i-want-to-play-with-the-ball", text: "I want to play with the ball.", ko: "저 공 가지고 놀고 싶어요.", level: "intermediate" },
      { id: "can-you-show-me-how-to-do-that", text: "Can you show me how to do that?", ko: "그거 어떻게 하는지 보여줄래요?", level: "intermediate" },
      { id: "lets-see-who-can-jump-higher", text: "Let's see who can jump higher.", ko: "누가 더 높이 뛰나 보자.", level: "intermediate" },
      { id: "play-something-else", text: "Can we play something else?", ko: "우리 다른 거 하면 안 돼요?", level: "advanced" },
      { id: "not-fair", text: "That's not fair!", ko: "그건 불공평해요!", level: "advanced" },
      { id: "go-first-this-time", text: "I want to go first this time.", ko: "이번엔 제가 먼저 하고 싶어요.", level: "advanced" },
      { id: "take-turns", text: "Let's take turns.", ko: "우리 번갈아 하자.", level: "advanced" },
      { id: "fell-down-okay", text: "I fell down, but I'm okay.", ko: "넘어졌는데 저 괜찮아요.", level: "advanced" },
      { id: "come-back-tomorrow", text: "Can we come back tomorrow?", ko: "우리 내일 또 와도 돼요?", level: "advanced" },
      { id: "more-fun-than-yesterday", text: "I think we're having more fun than yesterday.", ko: "어제보다 오늘 더 재밌는 것 같아요.", level: "advanced" },
      { id: "play-together-different-teams", text: "Can we play together even though we're on different teams?", ko: "팀이 달라도 같이 놀 수 있어요?", level: "advanced" },
      { id: "sad-when-you-didnt-share", text: "I was a little sad when you didn't share.", ko: "안 나눠줘서 조금 슬펐어요.", level: "advanced" },
      { id: "lets-make-up-a-new-game", text: "Let's make up a new game together.", ko: "우리 같이 새로운 놀이를 만들어보자.", level: "advanced" },
      { id: "more-fun-with-more-friends", text: "I think it would be more fun with more friends.", ko: "친구가 더 많으면 더 재밌을 것 같아요.", level: "advanced" },
      { id: "can-we-agree-on-the-rules-first", text: "Can we agree on the rules first?", ko: "먼저 규칙을 정하는 게 어때요?", level: "advanced" },
      { id: "didnt-mean-to-push-you", text: "I didn't mean to push you.", ko: "밀려고 한 게 아니었어요.", level: "advanced" },
      { id: "lets-say-sorry-and-keep-playing", text: "Let's say sorry and keep playing.", ko: "미안하다고 하고 계속 놀자.", level: "advanced" },
      { id: "you-are-really-good-at-this-game", text: "I think you are really good at this game.", ko: "너 이 게임 진짜 잘하는 것 같아.", level: "advanced" },
      { id: "can-we-switch-teams-so-its-fair", text: "Can we switch teams so it's fair?", ko: "공평하게 팀을 바꿔도 돼요?", level: "advanced" },
      { id: "scared-when-i-fell-but-okay-now", text: "I was scared when I fell, but I'm okay now.", ko: "넘어졌을 때 무서웠는데 지금은 괜찮아요.", level: "advanced" },
      { id: "lets-let-younger-kids-go-first", text: "Let's let the younger kids go first.", ko: "어린 친구들 먼저 하게 해주자.", level: "advanced" },
      { id: "waiting-is-hard-but-im-trying", text: "Waiting for my turn is hard, but I'm trying.", ko: "차례 기다리는 게 힘들지만 노력하고 있어요.", level: "advanced" },
      { id: "game-that-everyone-can-join", text: "Can we play a game that everyone can join?", ko: "다 같이 할 수 있는 게임 하면 안 돼요?", level: "advanced" },
      { id: "noticed-you-playing-alone", text: "I noticed you were playing alone, so I came to join you.", ko: "혼자 노는 것 같아서 같이 하려고 왔어요.", level: "advanced" },
      { id: "wasnt-fair-i-didnt-get-a-turn", text: "It wasn't fair that I didn't get a turn.", ko: "제 차례가 없었던 건 불공평했어요.", level: "advanced" },
      { id: "lets-forget-about-it-have-fun-again", text: "Let's forget about it and have fun again.", ko: "그건 잊고 다시 재밌게 놀자.", level: "advanced" },
      { id: "best-day-at-the-playground-so-far", text: "I think this is the best day at the playground so far.", ko: "지금까지 놀이터에서 제일 재밌었던 날인 것 같아요.", level: "advanced" },
      { id: "wait-for-me-im-almost-there", text: "Can you wait for me? I'm almost there.", ko: "기다려줄래요? 거의 다 왔어요.", level: "advanced" },
      { id: "rather-play-hide-and-seek-than-tag", text: "I would rather play hide and seek than tag.", ko: "술래잡기보다 숨바꼭질이 더 하고 싶어요.", level: "advanced" },
      { id: "lets-take-a-break-then-play-again", text: "Let's take a break and then play again.", ko: "잠깐 쉬었다가 다시 놀자.", level: "advanced" },
      { id: "everyone-choose-a-game-once", text: "I think we should let everyone choose a game once.", ko: "다 같이 돌아가면서 게임을 골랐으면 좋겠어요.", level: "advanced" },
      { id: "even-if-i-lose-still-had-fun", text: "Even if I lose, I still had fun.", ko: "져도 그래도 재밌었어요.", level: "advanced" },
      { id: "can-we-be-partners-for-this-game", text: "Can we be partners for this game?", ko: "이 게임에서 짝이 되어줄래요?", level: "advanced" },
    ],
  },
];
