// "기초 영어회화" 도구의 목차. 챕터 하나 = 상황 하나. 새 챕터는 이 배열에 항목만
// 추가하면 목차 화면과 화면 등록(index.js)에 자동으로 반영된다 — 다른 곳을 고칠 필요 없다.
//
// 일상대화 위주로 구성했다(어린이 애니메이션 참고, D-65) — 뽀로로/타요/페파피그류가 매번
// "아침에 일어나기", "친구랑 놀기", "밥 먹기", "잠자리" 같은 하루 일과 하나를 에피소드로
// 삼는 것과 같은 결. 단어 암기(This is a rabbit)보다 그 상황에서 실제로 주고받는 말
// (Let's play! / Can I have more?)을 우선했다.
//
// 챕터는 잘게 쪼개지 않고 묶는다(D-66) — 하루 일과처럼 시간 순으로 자연스럽게 이어지는
// 상황이나, 가족·자기소개처럼 소재가 겹치는 상황은 챕터 하나로 합쳐서 문항 수를 키운다.
// 새 상황이 생기면 새 챕터부터 만들지 말고, 기존 챕터 중 붙일 자리가 있는지 먼저 본다 —
// 챕터가 잘게 계속 늘어나면 목차 자체가 또 하나의 목록이 돼서 "하나의 공부 도구"라는
// 원래 취지(D-62·D-63)가 흐려진다.
//
// 문장에는 `level`이 있을 수 있다(D-70). 없으면 "기초"(입문 생존 표현), `"advanced"`면
// "심화"(의견·이유·비교·협상이 들어간, 원어민 7세 정도의 문장). 각 챕터 안에서 기초를
// 전부 배열한 다음 심화를 뒤에 잇는다 — 같은 상황을 계속 반복하며 단계만 올라가는
// 흐름이라, 심화용으로 새 챕터를 또 만들지 않는다. 진짜 다중 턴 대화(질문→대답→되묻기)는
// 이 앱의 "문장 하나 듣고 따라 말하기" 채점 구조와 안 맞아서 지금은 만들지 않는다 — 나중에
// 별도 대화형 도구로 다룰 계획(`docs/learning-architecture.md` §3-5).
export const CHAPTERS = [
  {
    id: "greeting",
    title: "인사 · 기분 표현",
    emoji: "👋",
    sentences: [
      { id: "hello", text: "Hello!", ko: "안녕!" },
      { id: "good-morning", text: "Good morning!", ko: "좋은 아침이에요!" },
      { id: "good-night", text: "Good night!", ko: "잘 자요!" },
      { id: "how-are-you", text: "How are you?", ko: "어떻게 지내요?" },
      { id: "happy", text: "I'm happy.", ko: "나는 기뻐요." },
      { id: "sad", text: "I'm sad.", ko: "나는 슬퍼요." },
      { id: "angry", text: "I'm angry.", ko: "나는 화나요." },
      { id: "tired", text: "I'm tired.", ko: "나는 피곤해요." },
      { id: "hungry", text: "I'm hungry.", ko: "나는 배고파요." },
      { id: "thirsty", text: "I'm thirsty.", ko: "나는 목말라요." },
      { id: "sleepy", text: "I'm sleepy.", ko: "나는 졸려요." },
      { id: "scared", text: "I'm scared.", ko: "나는 무서워요." },
      { id: "excited", text: "I'm excited.", ko: "나는 신나요." },
      { id: "surprised", text: "I'm surprised.", ko: "나는 놀랐어요." },
      { id: "bored", text: "I'm bored.", ko: "나는 심심해요." },
      { id: "okay", text: "I'm okay.", ko: "나는 괜찮아요." },
      { id: "nice-to-meet-you", text: "Nice to meet you.", ko: "만나서 반가워요." },
      { id: "whats-your-name", text: "What's your name?", ko: "이름이 뭐예요?" },
      { id: "my-name-is", text: "My name is Tom.", ko: "내 이름은 톰이에요." },
      { id: "see-you-later", text: "See you later!", ko: "나중에 봐요!" },
      { id: "see-you-tomorrow", text: "See you tomorrow!", ko: "내일 봐요!" },
      { id: "thank-you", text: "Thank you!", ko: "고마워요!" },
      { id: "youre-welcome", text: "You're welcome!", ko: "천만에요!" },
      { id: "sorry", text: "I'm sorry.", ko: "미안해요." },
      { id: "its-okay", text: "It's okay.", ko: "괜찮아요." },
      { id: "excuse-me", text: "Excuse me.", ko: "실례합니다." },
      { id: "please", text: "Please.", ko: "부탁해요." },
      { id: "yes", text: "Yes!", ko: "네!" },
      { id: "no", text: "No.", ko: "아니요." },
      { id: "bye", text: "Goodbye!", ko: "안녕히 가세요!" },
      { id: "happy-because", text: "I'm happy because it's my birthday.", ko: "오늘 제 생일이라서 기뻐요.", level: "advanced" },
      { id: "little-nervous", text: "I feel a little nervous.", ko: "조금 긴장돼요.", level: "advanced" },
      { id: "dont-feel-good", text: "I don't feel good today.", ko: "오늘 몸이 안 좋아요.", level: "advanced" },
      { id: "why-are-you-sad", text: "Why are you sad?", ko: "왜 슬퍼요?", level: "advanced" },
      { id: "not-angry-anymore", text: "I'm not angry anymore.", ko: "이제 화 안 났어요.", level: "advanced" },
      { id: "made-me-happy", text: "That made me really happy.", ko: "그거 때문에 진짜 기뻤어요.", level: "advanced" },
    ],
  },
  {
    // 옛 morning-routine + meal-time + bath-bedtime을 하나로. 아침에 일어나서 밥 먹고
    // 놀다가 씻고 잠드는 하루 흐름을 그대로 시간순으로 이었다.
    id: "daily-routine",
    title: "하루 일과",
    emoji: "🌅",
    sentences: [
      { id: "wake-up", text: "Wake up!", ko: "일어나요!" },
      { id: "brush-teeth", text: "Let's brush our teeth.", ko: "이 닦자." },
      { id: "wash-face", text: "Wash your face.", ko: "세수하세요." },
      { id: "get-dressed", text: "Get dressed!", ko: "옷 입자!" },
      { id: "eat-breakfast", text: "Let's eat breakfast.", ko: "아침 먹자." },
      { id: "wheres-my-shoes", text: "Where are my shoes?", ko: "내 신발 어디 있어요?" },
      { id: "im-ready", text: "I'm ready!", ko: "준비 다 됐어요!" },
      { id: "lets-go", text: "Let's go!", ko: "가자!" },
      { id: "im-hungry", text: "I'm hungry.", ko: "배고파요." },
      { id: "lets-eat", text: "Let's eat!", ko: "먹자!" },
      { id: "this-is-yummy", text: "This is yummy!", ko: "이거 맛있어요!" },
      { id: "i-dont-like-this", text: "I don't like this.", ko: "이거 안 좋아해요." },
      { id: "can-i-have-more", text: "Can I have more?", ko: "더 먹어도 돼요?" },
      { id: "can-i-have-a-cookie", text: "Can I have a cookie?", ko: "쿠키 먹어도 돼요?" },
      { id: "want-milk", text: "I want milk.", ko: "우유 주세요." },
      { id: "want-juice", text: "I want juice.", ko: "주스 주세요." },
      { id: "want-water", text: "I want water.", ko: "물 주세요." },
      { id: "im-full", text: "I'm full.", ko: "배불러요." },
      { id: "cheers", text: "Cheers!", ko: "건배!" },
      { id: "thank-you-for-the-food", text: "Thank you for the food.", ko: "잘 먹겠습니다." },
      { id: "bath-time", text: "Bath time!", ko: "목욕할 시간이에요!" },
      { id: "water-is-warm", text: "The water is warm.", ko: "물이 따뜻해요." },
      { id: "wash-your-hair", text: "Let's wash your hair.", ko: "머리 감자." },
      { id: "put-on-pajamas", text: "Put on your pajamas.", ko: "잠옷 입자." },
      { id: "brush-teeth-again", text: "Brush your teeth.", ko: "이 닦자." },
      { id: "bedtime-story", text: "Let's read a bedtime story.", ko: "자기 전에 책 읽어 줄게." },
      { id: "sweet-dreams", text: "Sweet dreams!", ko: "좋은 꿈 꿔!" },
      { id: "good-night-again", text: "Good night!", ko: "잘 자요!" },
      { id: "wash-your-hands", text: "Wash your hands.", ko: "손을 씻자." },
      { id: "cover-your-mouth", text: "Cover your mouth.", ko: "입을 가리세요." },
      { id: "go-potty", text: "I need to go potty.", ko: "화장실 가고 싶어요." },
      { id: "wipe-your-mouth", text: "Wipe your mouth.", ko: "입을 닦자." },
      { id: "watch-tv-after", text: "Can I watch TV after breakfast?", ko: "아침 먹고 티비 봐도 돼요?", level: "advanced" },
      { id: "dont-want-bath-yet", text: "I don't want to take a bath yet.", ko: "아직 목욕하기 싫어요.", level: "advanced" },
      { id: "five-more-minutes", text: "Just five more minutes, please.", ko: "딱 5분만 더요.", level: "advanced" },
      { id: "already-brushed", text: "I already brushed my teeth.", ko: "저 이미 이 닦았어요.", level: "advanced" },
      { id: "whats-for-dinner", text: "What's for dinner tonight?", ko: "오늘 저녁 뭐예요?", level: "advanced" },
      { id: "clean-up-first", text: "I'll clean up my toys first.", ko: "장난감부터 치울게요.", level: "advanced" },
    ],
  },
  {
    // 옛 self-intro + family를 하나로. 나를 소개하는 문장과 우리 가족을 소개하는 문장은
    // 소재가 이어져 있어 굳이 나눌 이유가 없었다.
    id: "family-and-me",
    title: "가족 · 자기소개",
    emoji: "👨‍👩‍👧",
    sentences: [
      { id: "name-is-amy", text: "My name is Amy.", ko: "내 이름은 에이미예요." },
      { id: "seven-years-old", text: "I am seven years old.", ko: "나는 일곱 살이에요." },
      { id: "live-in-seoul", text: "I live in Seoul.", ko: "나는 서울에 살아요." },
      { id: "like-drawing", text: "I like drawing.", ko: "나는 그림 그리기를 좋아해요." },
      { id: "like-singing", text: "I like singing.", ko: "나는 노래하기를 좋아해요." },
      { id: "like-soccer", text: "I like soccer.", ko: "나는 축구를 좋아해요." },
      { id: "like-ice-cream", text: "I like ice cream.", ko: "나는 아이스크림을 좋아해요." },
      { id: "favorite-color", text: "My favorite color is blue.", ko: "내가 제일 좋아하는 색은 파란색이에요." },
      { id: "am-a-student", text: "I am a student.", ko: "나는 학생이에요." },
      { id: "nice-to-meet-you-too", text: "Nice to meet you too!", ko: "저도 만나서 반가워요!" },
      { id: "this-is-mom", text: "This is my mom.", ko: "이 사람은 우리 엄마예요." },
      { id: "this-is-dad", text: "This is my dad.", ko: "이 사람은 우리 아빠예요." },
      { id: "this-is-sister", text: "This is my sister.", ko: "이 사람은 우리 언니(누나)예요." },
      { id: "this-is-grandpa", text: "This is my grandpa.", ko: "이 사람은 우리 할아버지예요." },
      { id: "have-big-brother", text: "I have a big brother.", ko: "나는 형(오빠)이 있어요." },
      { id: "wheres-grandma", text: "Where is grandma?", ko: "할머니 어디 계세요?" },
      { id: "i-love-you", text: "I love you.", ko: "사랑해요." },
      { id: "i-miss-you", text: "I miss you.", ko: "보고 싶어요." },
      { id: "give-me-a-hug", text: "Give me a hug.", ko: "안아 주세요." },
      { id: "can-you-help-me", text: "Can you help me?", ko: "도와줄 수 있어요?" },
      { id: "read-together", text: "Let's read a book together.", ko: "같이 책 읽자." },
      { id: "color-red", text: "It's red.", ko: "빨간색이에요." },
      { id: "color-yellow", text: "It's yellow.", ko: "노란색이에요." },
      { id: "color-green", text: "It's green.", ko: "초록색이에요." },
      { id: "dogs-cuter", text: "I think dogs are cuter than cats.", ko: "저는 강아지가 고양이보다 더 귀여운 것 같아요.", level: "advanced" },
      { id: "brother-older", text: "My brother is older than me.", ko: "형(오빠)이 저보다 나이가 많아요.", level: "advanced" },
      { id: "want-to-be-doctor", text: "I want to be a doctor when I grow up.", ko: "저는 커서 의사가 되고 싶어요.", level: "advanced" },
      { id: "good-at-drawing-not-singing", text: "I'm good at drawing, but not at singing.", ko: "저는 그림은 잘 그리는데 노래는 못해요.", level: "advanced" },
      { id: "guess-how-old", text: "Can you guess how old I am?", ko: "제가 몇 살인지 맞혀보세요.", level: "advanced" },
      { id: "look-like-mom", text: "I look like my mom.", ko: "저는 엄마를 닮았어요.", level: "advanced" },
    ],
  },
  {
    // 옛 playing-with-friends + weather를 하나로. 밖에서 노는 동안 날씨 얘기가 자연스럽게
    // 섞여 나오는 상황이라 같이 뒀다.
    id: "playground",
    title: "놀이터에서",
    emoji: "🎈",
    sentences: [
      { id: "lets-play", text: "Let's play!", ko: "같이 놀자!" },
      { id: "can-i-play-too", text: "Can I play too?", ko: "나도 같이 놀아도 돼요?" },
      { id: "my-turn", text: "It's my turn!", ko: "내 차례예요!" },
      { id: "watch-this", text: "Watch this!", ko: "이거 봐!" },
      { id: "so-much-fun", text: "That's so much fun!", ko: "진짜 재밌다!" },
      { id: "lets-be-friends", text: "Let's be friends.", ko: "우리 친구하자." },
      { id: "can-i-borrow-this", text: "Can I borrow this?", ko: "이거 빌려도 돼요?" },
      { id: "lets-share", text: "Let's share.", ko: "같이 나눠 쓰자." },
      { id: "tag-youre-it", text: "Tag, you're it!", ko: "잡았다, 네 차례야!" },
      { id: "lets-race", text: "Let's race!", ko: "우리 달리기 하자!" },
      { id: "lets-play-tag", text: "Let's play tag.", ko: "우리 술래잡기 하자." },
      { id: "lets-play-hide-and-seek", text: "Let's play hide and seek.", ko: "우리 숨바꼭질 하자." },
      { id: "lets-play-soccer", text: "Let's play soccer.", ko: "우리 축구하자." },
      { id: "sunny-today", text: "It's sunny today.", ko: "오늘은 맑아요." },
      { id: "its-raining", text: "It's raining.", ko: "비가 와요." },
      { id: "its-snowing", text: "It's snowing!", ko: "눈이 와요!" },
      { id: "its-windy", text: "It's windy.", ko: "바람이 불어요." },
      { id: "hot-today", text: "It's hot today.", ko: "오늘 더워요." },
      { id: "cold-outside", text: "It's cold outside.", ko: "밖이 추워요." },
      { id: "cloudy-today", text: "It's cloudy today.", ko: "오늘 흐려요." },
      { id: "bring-umbrella", text: "Bring an umbrella.", ko: "우산 챙기세요." },
      { id: "beautiful-day", text: "What a beautiful day!", ko: "날씨 정말 좋다!" },
      { id: "go-to-the-park", text: "Can we go to the park?", ko: "우리 공원 가도 돼요?" },
      { id: "want-to-swing", text: "I want to swing.", ko: "그네 타고 싶어요." },
      { id: "build-sandcastle", text: "Let's build a sandcastle.", ko: "모래성 만들자." },
      { id: "one-two-three-go", text: "One, two, three, go!", ko: "하나, 둘, 셋, 출발!" },
      { id: "play-something-else", text: "Can we play something else?", ko: "우리 다른 거 하면 안 돼요?", level: "advanced" },
      { id: "not-fair", text: "That's not fair!", ko: "그건 불공평해요!", level: "advanced" },
      { id: "go-first-this-time", text: "I want to go first this time.", ko: "이번엔 제가 먼저 하고 싶어요.", level: "advanced" },
      { id: "take-turns", text: "Let's take turns.", ko: "우리 번갈아 하자.", level: "advanced" },
      { id: "fell-down-okay", text: "I fell down, but I'm okay.", ko: "넘어졌는데 저 괜찮아요.", level: "advanced" },
      { id: "come-back-tomorrow", text: "Can we come back tomorrow?", ko: "우리 내일 또 와도 돼요?", level: "advanced" },
    ],
  },
];
