// 어원 사전 — 이 도구의 연상암기법 뼈대다(사용자 지시: "어원 우선").
//
// **왜 단어마다 연상을 하나씩 짓지 않고 사전을 두나**: 목표가 8000단어라, 단어 하나에
// 연상 하나를 붙이면 8000개를 각각 외워야 한다. 어근은 수십 단어에 되풀이돼서(tain 하나로
// attain·maintain·obtain·pertain·retain···) 저작량과 학습량이 동시에 줄고, 처음 보는
// 단어도 쪼개서 짐작할 수 있게 된다.
//
// 어원이 뚜렷하지 않은 단어에는 **억지 어원을 붙이지 않는다** — 그런 단어는 roots를 비우고
// 소리연상(sound)만 쓴다(D-94에서 정한 "억지 데이터는 신호가 없는 것보다 나쁘다").
//
// 쓰이지 않는 항목을 남기지 않는다 — test/learning.vocab.test.js가 (1) 단어가 가리키는
// 어근이 실재하는지, (2) 어느 단어도 안 쓰는 죽은 어근이 있는지 둘 다 검사한다
// (elementary-conversation의 grammarPoints 검사와 같은 규칙).
//
// form은 화면 표시용 대표 철자, ko는 뜻, note는 변형(자음 동화·이형태)이다.
export const ROOTS = [
  // ── 접두사 ──────────────────────────────────────────────
  { id: "ab", kind: "prefix", form: "ab-", ko: "떨어져, 멀리" },
  { id: "ad", kind: "prefix", form: "ad-", ko: "~쪽으로, ~에", note: "뒤 자음에 붙어 ac·af·ag·al·ap·as·at로 바뀐다" },
  { id: "ambi", kind: "prefix", form: "ambi-", ko: "양쪽, 둘레" },
  { id: "ante", kind: "prefix", form: "ante-", ko: "미리, 앞서", note: "anti-로도 쓴다" },
  { id: "auto", kind: "prefix", form: "auto-", ko: "스스로" },
  { id: "bene", kind: "prefix", form: "bene-", ko: "좋은, 잘" },
  { id: "com", kind: "prefix", form: "com-", ko: "함께, 완전히", note: "co·col·con·cor로 바뀐다" },
  { id: "contra", kind: "prefix", form: "contra-", ko: "반대로, 맞서" },
  { id: "de", kind: "prefix", form: "de-", ko: "아래로 · 떨어져 · 완전히(강조)" },
  { id: "di-two", kind: "prefix", form: "di-", ko: "둘", note: "위의 dis-(따로)와 철자가 겹쳐 뜻으로 갈라 본다" },
  { id: "dis", kind: "prefix", form: "dis-", ko: "따로, 떨어져, 아닌", note: "di·dif로도 쓴다" },
  { id: "epi", kind: "prefix", form: "epi-", ko: "위에, 사이에" },
  { id: "ex", kind: "prefix", form: "ex-", ko: "밖으로", note: "e·ef로도 쓴다" },
  { id: "in", kind: "prefix", form: "in-", ko: "안으로 · ~하게 만들다", note: "en·em·il·im·ir로 바뀐다" },
  { id: "in-neg", kind: "prefix", form: "in-", ko: "아닌(부정)", note: "위의 in-과 철자가 같아 뜻으로 갈라 본다" },
  { id: "infra", kind: "prefix", form: "infra-", ko: "아래" },
  { id: "inter", kind: "prefix", form: "inter-", ko: "사이에, 서로" },
  { id: "mal", kind: "prefix", form: "mal-", ko: "나쁜" },
  { id: "ob", kind: "prefix", form: "ob-", ko: "~쪽으로, 맞은편에, 위에서", note: "oc·op로 바뀐다" },
  { id: "over", kind: "prefix", form: "over-", ko: "위로, 넘어서" },
  { id: "para", kind: "prefix", form: "para-", ko: "나란히, 옆에" },
  { id: "per", kind: "prefix", form: "per-", ko: "완전히, 통과해" },
  { id: "post", kind: "prefix", form: "post-", ko: "뒤에, 나중에" },
  { id: "pre", kind: "prefix", form: "pre-", ko: "미리, 앞서" },
  { id: "pro", kind: "prefix", form: "pro-", ko: "앞으로, 앞에", note: "pur-로도 쓴다" },
  { id: "re", kind: "prefix", form: "re-", ko: "다시, 뒤로, 되받아" },
  { id: "sub", kind: "prefix", form: "sub-", ko: "아래, 뒤에", note: "suc·suf·sup·sus로 바뀐다" },
  { id: "super", kind: "prefix", form: "super-", ko: "위에, 넘어", note: "sur-로도 쓴다" },
  { id: "trans", kind: "prefix", form: "trans-", ko: "가로질러, 건너", note: "tra-로도 쓴다" },

  // ── 어근 ────────────────────────────────────────────────
  { id: "act", kind: "stem", form: "act", ko: "행하다" },
  { id: "acu", kind: "stem", form: "acu", ko: "뾰족한, 날카로운" },
  { id: "agger", kind: "stem", form: "agger", ko: "쌓다" },
  { id: "alt", kind: "stem", form: "alt", ko: "높은", note: "enhance의 -hance" },
  { id: "alter", kind: "stem", form: "alter", ko: "다른" },
  { id: "ampl", kind: "stem", form: "ampl", ko: "넓은" },
  { id: "apt", kind: "stem", form: "apt", ko: "알맞은" },
  { id: "arbitr", kind: "stem", form: "arbitr", ko: "심판, 중재인" },
  { id: "arch", kind: "stem", form: "arch", ko: "우두머리, 처음" },
  { id: "audi", kind: "stem", form: "audi", ko: "듣다" },
  { id: "auth", kind: "stem", form: "auth", ko: "스스로, 본인" },
  { id: "ban", kind: "stem", form: "ban", ko: "공표하여 내쫓다" },
  { id: "brac", kind: "stem", form: "brac", ko: "팔" },
  { id: "bureau", kind: "stem", form: "bureau", ko: "사무실 책상" },
  { id: "cant", kind: "stem", form: "cant", ko: "노래하다, 부추기다" },
  { id: "ceal", kind: "stem", form: "ceal", ko: "덮다, 숨기다" },
  { id: "ced", kind: "stem", form: "ced", ko: "가다, 물러나다", note: "cess·ceas로도 쓴다" },
  { id: "ceiv", kind: "stem", form: "ceiv", ko: "잡다", note: "cap·cip와 한 뿌리" },
  { id: "celer", kind: "stem", form: "celer", ko: "빠른" },
  { id: "cens", kind: "stem", form: "cens", ko: "세다, 평가하다" },
  { id: "cern", kind: "stem", form: "cern", ko: "가르다, 가려내다" },
  { id: "charg", kind: "stem", form: "charg", ko: "짐, 싣다" },
  { id: "chron", kind: "stem", form: "chron", ko: "시간" },
  { id: "cid", kind: "stem", form: "cid", ko: "떨어지다", note: "cad·cas로도 쓴다" },
  { id: "cip", kind: "stem", form: "cip", ko: "잡다" },
  { id: "circ", kind: "stem", form: "circ", ko: "둥근, 원" },
  { id: "cis", kind: "stem", form: "cis", ko: "자르다" },
  { id: "cit", kind: "stem", form: "cit", ko: "불러내다" },
  { id: "clam", kind: "stem", form: "clam", ko: "외치다", note: "claim으로도 쓴다" },
  { id: "clar", kind: "stem", form: "clar", ko: "맑은, 밝은" },
  { id: "clin", kind: "stem", form: "clin", ko: "기울다" },
  { id: "clud", kind: "stem", form: "clud", ko: "닫다", note: "clos·clus로도 쓴다" },
  { id: "concil", kind: "stem", form: "concil", ko: "불러 모으다" },
  { id: "corpor", kind: "stem", form: "corpor", ko: "몸, 덩어리" },
  { id: "crac", kind: "stem", form: "crac", ko: "지배, 힘" },
  { id: "cred", kind: "stem", form: "cred", ko: "믿다" },
  { id: "crep", kind: "stem", form: "crep", ko: "삐걱거리다" },
  { id: "cresc", kind: "stem", form: "cresc", ko: "자라다", note: "cru·cre로도 쓴다" },
  { id: "cruc", kind: "stem", form: "cruc", ko: "십자, 갈림길" },
  { id: "cumul", kind: "stem", form: "cumul", ko: "더미" },
  { id: "cup", kind: "stem", form: "cup", ko: "잡다, 차지하다" },
  { id: "curt", kind: "stem", form: "curt", ko: "짧은" },
  { id: "da", kind: "stem", form: "da", ko: "주다", note: "render의 -der" },
  { id: "damn", kind: "stem", form: "damn", ko: "해를 입히다, 유죄로 하다" },
  { id: "dec", kind: "stem", form: "dec", ko: "어울리는, 알맞은" },
  { id: "dem", kind: "stem", form: "dem", ko: "사람들, 민중" },
  { id: "deterior", kind: "stem", form: "deterior", ko: "더 나쁜" },
  { id: "dic", kind: "stem", form: "dic", ko: "말하다, 가리키다", note: "dict로도 쓴다" },
  { id: "domin", kind: "stem", form: "domin", ko: "주인" },
  { id: "dub", kind: "stem", form: "dub", ko: "둘로 갈려 의심하다" },
  { id: "duc", kind: "stem", form: "duc", ko: "이끌다", note: "duct로도 쓴다" },
  { id: "dur", kind: "stem", form: "dur", ko: "단단한, 오래가는" },
  { id: "empir", kind: "stem", form: "empir", ko: "경험, 시도" },
  { id: "empt", kind: "stem", form: "empt", ko: "취하다, 사다" },
  { id: "equ", kind: "stem", form: "equ", ko: "같은" },
  { id: "err", kind: "stem", form: "err", ko: "헤매다, 벗어나다" },
  { id: "evit", kind: "stem", form: "evit", ko: "피하다" },
  { id: "fabric", kind: "stem", form: "fabric", ko: "만들어 내다, 공작" },
  { id: "faci", kind: "stem", form: "faci", ko: "얼굴, 겉면" },
  { id: "facil", kind: "stem", form: "facil", ko: "쉬운" },
  { id: "fare", kind: "stem", form: "fare", ko: "가다, 지내다" },
  { id: "fect", kind: "stem", form: "fect", ko: "하다, 만들다", note: "fac·fic으로도 쓴다" },
  { id: "fer", kind: "stem", form: "fer", ko: "나르다" },
  { id: "fin", kind: "stem", form: "fin", ko: "끝, 경계" },
  { id: "flict", kind: "stem", form: "flict", ko: "치다, 부딪다" },
  { id: "fluct", kind: "stem", form: "fluct", ko: "흐르다, 물결치다" },
  { id: "form", kind: "stem", form: "form", ko: "모양" },
  { id: "fost", kind: "stem", form: "fost", ko: "먹여 기르다" },
  { id: "frag", kind: "stem", form: "frag", ko: "부수다", note: "fract로도 쓴다" },
  { id: "front", kind: "stem", form: "front", ko: "이마, 앞" },
  { id: "frug", kind: "stem", form: "frug", ko: "열매, 알뜰함" },
  { id: "fund", kind: "stem", form: "fund", ko: "바닥, 기초", note: "found로도 쓴다" },
  { id: "fut", kind: "stem", form: "fut", ko: "치다" },
  { id: "gen", kind: "stem", form: "gen", ko: "낳다, 생기다" },
  { id: "grad", kind: "stem", form: "grad", ko: "걸음, 단계" },
  { id: "grav", kind: "stem", form: "grav", ko: "무거운" },
  { id: "habit", kind: "stem", form: "habit", ko: "살다, 지니다" },
  { id: "haust", kind: "stem", form: "haust", ko: "퍼내다" },
  { id: "her", kind: "stem", form: "her", ko: "붙다", note: "hes로도 쓴다" },
  { id: "herit", kind: "stem", form: "herit", ko: "물려받다" },
  { id: "hibit", kind: "stem", form: "hibit", ko: "붙잡다", note: "habit(지니다)의 변형" },
  { id: "hier", kind: "stem", form: "hier", ko: "신성한" },
  { id: "hind", kind: "stem", form: "hind", ko: "뒤" },
  { id: "host", kind: "stem", form: "host", ko: "적, 낯선 이" },
  { id: "ident", kind: "stem", form: "ident", ko: "같은" },
  { id: "init", kind: "stem", form: "init", ko: "들어가다, 시작하다" },
  { id: "integr", kind: "stem", form: "integr", ko: "온전한, 손대지 않은" },
  { id: "it", kind: "stem", form: "it", ko: "가다" },
  { id: "jac", kind: "stem", form: "jac", ko: "눕다" },
  { id: "ject", kind: "stem", form: "ject", ko: "던지다" },
  { id: "journ", kind: "stem", form: "journ", ko: "날, 하루" },
  { id: "jur", kind: "stem", form: "jur", ko: "법, 맹세" },
  { id: "just", kind: "stem", form: "just", ko: "올바른, 법에 맞는" },
  { id: "know", kind: "stem", form: "know", ko: "알다", note: "영어 고유어 — acknowledge의 ac-는 라틴 ad-가 아니라 강조 접두사다" },
  { id: "labor", kind: "stem", form: "labor", ko: "노동, 공들임" },
  { id: "laps", kind: "stem", form: "laps", ko: "미끄러지다" },
  { id: "later", kind: "stem", form: "later", ko: "옆, 측면" },
  { id: "lect", kind: "stem", form: "lect", ko: "고르다, 모으다" },
  { id: "leg", kind: "stem", form: "leg", ko: "법 · 위임해 보내다" },
  { id: "lemma", kind: "stem", form: "lemma", ko: "전제, 내놓은 명제" },
  { id: "len", kind: "stem", form: "len", ko: "부드러운" },
  { id: "lev", kind: "stem", form: "lev", ko: "가벼운, 들어 올리다" },
  { id: "libr", kind: "stem", form: "libr", ko: "저울" },
  { id: "lig", kind: "stem", form: "lig", ko: "묶다", note: "li·ly로도 쓴다" },
  { id: "limin", kind: "stem", form: "limin", ko: "문지방" },
  { id: "linqu", kind: "stem", form: "linqu", ko: "남기다, 떠나다" },
  { id: "loc", kind: "stem", form: "loc", ko: "장소" },
  { id: "luc", kind: "stem", form: "luc", ko: "빛" },
  { id: "lucr", kind: "stem", form: "lucr", ko: "이익" },
  { id: "luct", kind: "stem", form: "luct", ko: "씨름하다" },
  { id: "lustr", kind: "stem", form: "lustr", ko: "빛, 비추다" },
  { id: "man", kind: "stem", form: "man", ko: "손", note: "main·mani로도 쓴다" },
  { id: "marg", kind: "stem", form: "marg", ko: "가장자리" },
  { id: "medi", kind: "stem", form: "medi", ko: "가운데" },
  { id: "memor", kind: "stem", form: "memor", ko: "기억" },
  { id: "mend", kind: "stem", form: "mend", ko: "흠, 결점" },
  { id: "mens", kind: "stem", form: "mens", ko: "재다" },
  { id: "merg", kind: "stem", form: "merg", ko: "잠기다" },
  { id: "metic", kind: "stem", form: "metic", ko: "두려움, 조심" },
  { id: "min-jut", kind: "stem", form: "min", ko: "튀어나오다", note: "아래 min(작은)과 철자가 같아 뜻으로 갈라 본다" },
  { id: "min-small", kind: "stem", form: "min", ko: "작은" },
  { id: "mine", kind: "stem", form: "mine", ko: "굴을 파다" },
  { id: "minister", kind: "stem", form: "minister", ko: "봉사하다, 시중들다" },
  { id: "mit", kind: "stem", form: "mit", ko: "보내다", note: "miss로도 쓴다" },
  { id: "miti", kind: "stem", form: "miti", ko: "부드러운" },
  { id: "mod", kind: "stem", form: "mod", ko: "알맞은 정도, 방식" },
  { id: "mon", kind: "stem", form: "mon", ko: "경고하다, 일깨우다" },
  { id: "monstr", kind: "stem", form: "monstr", ko: "보이다" },
  { id: "mort", kind: "stem", form: "mort", ko: "죽음" },
  { id: "mun", kind: "stem", form: "mun", ko: "공적 의무, 봉사" },
  { id: "mut", kind: "stem", form: "mut", ko: "바꾸다" },
  { id: "nat", kind: "stem", form: "nat", ko: "태어나다" },
  { id: "neg", kind: "stem", form: "neg", ko: "아닌, 부정하다" },
  { id: "nex", kind: "stem", form: "nex", ko: "묶다, 잇다" },
  { id: "nom", kind: "stem", form: "nom", ko: "법, 규칙" },
  { id: "nom-name", kind: "stem", form: "nom", ko: "이름", note: "위의 nom(법)과 철자가 같아 뜻으로 갈라 본다" },
  { id: "norm", kind: "stem", form: "norm", ko: "자, 기준" },
  { id: "not", kind: "stem", form: "not", ko: "표시, 적다" },
  { id: "nounc", kind: "stem", form: "nounc", ko: "알리다", note: "nunci로도 쓴다" },
  { id: "nov", kind: "stem", form: "nov", ko: "새로운" },
  { id: "null", kind: "stem", form: "null", ko: "없는, 영" },
  { id: "ol", kind: "stem", form: "ol", ko: "자라다" },
  { id: "oper", kind: "stem", form: "oper", ko: "일하다" },
  { id: "opt", kind: "stem", form: "opt", ko: "고르다" },
  { id: "optim", kind: "stem", form: "optim", ko: "가장 좋은" },
  { id: "oti", kind: "stem", form: "oti", ko: "여가, 한가함" },
  { id: "pan", kind: "stem", form: "pan", ko: "빵" },
  { id: "pand", kind: "stem", form: "pand", ko: "펼치다" },
  { id: "par-appear", kind: "stem", form: "par", ko: "나타나다" },
  { id: "par-equal", kind: "stem", form: "par", ko: "동등한", note: "위의 par(나타나다)와 철자가 같아 뜻으로 갈라 본다" },
  { id: "part", kind: "stem", form: "part", ko: "몫, 나누다" },
  { id: "pass", kind: "stem", form: "pass", ko: "걸음, 지나가다" },
  { id: "pauper", kind: "stem", form: "pauper", ko: "가난한" },
  { id: "pecu", kind: "stem", form: "pecu", ko: "사유 재산, 제 것" },
  { id: "ped", kind: "stem", form: "ped", ko: "발" },
  { id: "pejor", kind: "stem", form: "pejor", ko: "더 나쁜", note: "impair의 -pair" },
  { id: "pel", kind: "stem", form: "pel", ko: "밀다, 몰다", note: "puls로도 쓴다" },
  { id: "penetr", kind: "stem", form: "penetr", ko: "안으로 파고들다" },
  { id: "pens", kind: "stem", form: "pens", ko: "무게를 달다, 값을 치르다" },
  { id: "pet", kind: "stem", form: "pet", ko: "추구하다, 향해 가다" },
  { id: "phas", kind: "stem", form: "phas", ko: "보이다, 드러나다" },
  { id: "pict", kind: "stem", form: "pict", ko: "그리다" },
  { id: "pil", kind: "stem", form: "pil", ko: "쌓다, 다발" },
  { id: "plaus", kind: "stem", form: "plaus", ko: "박수치다" },
  { id: "ple", kind: "stem", form: "ple", ko: "채우다", note: "pli·plet로도 쓴다" },
  { id: "plic", kind: "stem", form: "plic", ko: "접다", note: "ply·ploit로도 쓴다" },
  { id: "plus", kind: "stem", form: "plus", ko: "더, 넘침" },
  { id: "pos", kind: "stem", form: "pos", ko: "놓다", note: "pon·pound로도 쓴다" },
  { id: "pot", kind: "stem", form: "pot", ko: "힘, 할 수 있다" },
  { id: "prag", kind: "stem", form: "prag", ko: "행하다, 일" },
  { id: "preci", kind: "stem", form: "preci", ko: "값, 가격" },
  { id: "prehend", kind: "stem", form: "prehend", ko: "붙잡다" },
  { id: "press", kind: "stem", form: "press", ko: "누르다" },
  { id: "pret", kind: "stem", form: "pret", ko: "중개하다, 값을 매기다" },
  { id: "priv", kind: "stem", form: "priv", ko: "떼어내다, 개인의" },
  { id: "prob", kind: "stem", form: "prob", ko: "좋다고 입증하다" },
  { id: "punct", kind: "stem", form: "punct", ko: "점, 찌르다" },
  { id: "put", kind: "stem", form: "put", ko: "셈하다, 생각하다" },
  { id: "quir", kind: "stem", form: "quir", ko: "구하다, 찾다", note: "quest·quis로도 쓴다" },
  { id: "quot", kind: "stem", form: "quot", ko: "얼마, 몇" },
  { id: "radic", kind: "stem", form: "radic", ko: "뿌리" },
  { id: "rat", kind: "stem", form: "rat", ko: "셈하다, 헤아리다" },
  { id: "reg", kind: "stem", form: "reg", ko: "규칙, 곧게 하다" },
  { id: "rig", kind: "stem", form: "rig", ko: "뻣뻣한" },
  { id: "riv", kind: "stem", form: "riv", ko: "강, 물줄기" },
  { id: "rob", kind: "stem", form: "rob", ko: "참나무, 힘" },
  { id: "rupt", kind: "stem", form: "rupt", ko: "깨다, 부수다" },
  { id: "rur", kind: "stem", form: "rur", ko: "시골, 들" },
  { id: "sanct", kind: "stem", form: "sanct", ko: "신성하게 정하다" },
  { id: "scal", kind: "stem", form: "scal", ko: "사다리, 계단" },
  { id: "scend", kind: "stem", form: "scend", ko: "오르다", note: "scens로도 쓴다" },
  { id: "scrib", kind: "stem", form: "scrib", ko: "쓰다", note: "script로도 쓴다" },
  { id: "scur", kind: "stem", form: "scur", ko: "덮다, 어둡게 하다" },
  { id: "secut", kind: "stem", form: "secut", ko: "따르다, 뒤쫓다", note: "sequ·su(e)로도 쓴다" },
  { id: "sed", kind: "stem", form: "sed", ko: "앉다", note: "sess·sid로도 쓴다" },
  { id: "sent", kind: "stem", form: "sent", ko: "느끼다", note: "sens로도 쓴다" },
  { id: "sert", kind: "stem", form: "sert", ko: "엮다, 잇다" },
  { id: "serv", kind: "stem", form: "serv", ko: "지키다, 보관하다" },
  { id: "sign", kind: "stem", form: "sign", ko: "표시" },
  { id: "simil", kind: "stem", form: "simil", ko: "같은 · 함께", note: "sembl로도 쓴다(assemble의 simul은 \"함께\")" },
  { id: "sist", kind: "stem", form: "sist", ko: "서다" },
  { id: "sol", kind: "stem", form: "sol", ko: "혼자" },
  { id: "solid", kind: "stem", form: "solid", ko: "단단한" },
  { id: "solv", kind: "stem", form: "solv", ko: "풀다", note: "solut로도 쓴다" },
  { id: "spect", kind: "stem", form: "spect", ko: "보다" },
  { id: "spond", kind: "stem", form: "spond", ko: "답하다, 약속하다" },
  { id: "staur", kind: "stem", form: "staur", ko: "세우다", note: "restore의 -stor" },
  { id: "still", kind: "stem", form: "still", ko: "방울, 떨어뜨리다" },
  { id: "stingu", kind: "stem", form: "stingu", ko: "찌르다" },
  { id: "stitut", kind: "stem", form: "stitut", ko: "세우다", note: "sta(서다)에서 왔다" },
  { id: "strain", kind: "stem", form: "strain", ko: "묶다, 조이다", note: "strict로도 쓴다" },
  { id: "struct", kind: "stem", form: "struct", ko: "세우다, 쌓다" },
  { id: "suad", kind: "stem", form: "suad", ko: "권하다" },
  { id: "sult", kind: "stem", form: "sult", ko: "의논하다" },
  { id: "sum", kind: "stem", form: "sum", ko: "취하다, 가지다", note: "sumpt로도 쓴다" },
  { id: "tail", kind: "stem", form: "tail", ko: "자르다" },
  { id: "tain", kind: "stem", form: "tain", ko: "잡다, 유지하다", note: "ten·tin으로도 쓴다" },
  { id: "tang", kind: "stem", form: "tang", ko: "닿다", note: "tact·ting으로도 쓴다 — tain(잡다)과는 다른 뿌리다" },
  { id: "tect", kind: "stem", form: "tect", ko: "덮다" },
  { id: "ted", kind: "stem", form: "ted", ko: "지겹게 하다" },
  { id: "tel", kind: "stem", form: "tel", ko: "천, 실" },
  { id: "templ", kind: "stem", form: "templ", ko: "신전, 살피는 구역" },
  { id: "tens", kind: "stem", form: "tens", ko: "팽팽히 당기다" },
  { id: "tent", kind: "stem", form: "tent", ko: "더듬다, 시도하다" },
  { id: "ter", kind: "stem", form: "ter", ko: "겁주다" },
  { id: "timid", kind: "stem", form: "timid", ko: "겁먹은" },
  { id: "tort", kind: "stem", form: "tort", ko: "비틀다" },
  { id: "tract", kind: "stem", form: "tract", ko: "끌다" },
  { id: "tri", kind: "stem", form: "tri", ko: "셋" },
  { id: "tribut", kind: "stem", form: "tribut", ko: "나누어 주다" },
  { id: "tric", kind: "stem", form: "tric", ko: "얽힘, 잔꾀" },
  { id: "trov", kind: "stem", form: "trov", ko: "찾아내다" },
  { id: "ubi", kind: "stem", form: "ubi", ko: "어디에나" },
  { id: "und", kind: "stem", form: "und", ko: "물결" },
  { id: "vac", kind: "stem", form: "vac", ko: "빈" },
  { id: "vad", kind: "stem", form: "vad", ko: "가다" },
  { id: "vail", kind: "stem", form: "vail", ko: "힘이 있다, 값어치가 있다" },
  { id: "valu", kind: "stem", form: "valu", ko: "가치" },
  { id: "vel", kind: "stem", form: "vel", ko: "베일, 덮개" },
  { id: "ven", kind: "stem", form: "ven", ko: "오다" },
  { id: "verb", kind: "stem", form: "verb", ko: "말" },
  { id: "vers", kind: "stem", form: "vers", ko: "돌다, 향하다", note: "vert로도 쓴다" },
  { id: "vestig", kind: "stem", form: "vestig", ko: "발자국" },
  { id: "via", kind: "stem", form: "via", ko: "길", note: "convey의 -vey" },
  { id: "vicin", kind: "stem", form: "vicin", ko: "이웃, 가까운" },
  { id: "vig", kind: "stem", form: "vig", ko: "활기, 생기" },
  { id: "vinc", kind: "stem", form: "vinc", ko: "이기다" },
  { id: "vis", kind: "stem", form: "vis", ko: "보다" },
  { id: "vit", kind: "stem", form: "vit", ko: "생명" },
  { id: "voc", kind: "stem", form: "voc", ko: "부르다, 목소리" },
  { id: "void", kind: "stem", form: "void", ko: "빈, 비우다" },
  { id: "vot", kind: "stem", form: "vot", ko: "맹세하다" },
  { id: "vulner", kind: "stem", form: "vulner", ko: "상처" },
];

// 화면·테스트가 id로 바로 찾을 수 있게 미리 색인해 둔다.
export const ROOT_BY_ID = new Map(ROOTS.map((r) => [r.id, r]));
