// DAY 2 — con·de·dis 계열 빈출 어휘. 파일 성격은 day-001.js 헤더 참고(동적 import 전용).
export const WORDS = [
  { id: "v002-01", word: "conserve", pos: "v.", ko: ["보존하다", "아껴 쓰다"], freq: 2,
    roots: ["com", "serv"], hint: "con(=com, 함께) + serv(지키다) → 함께 지켜 남겨 두다",
    ex: { en: "We must conserve water during the drought.", ko: "가뭄 동안 우리는 물을 아껴 써야 한다." },
    syn: ["preserve", "save"] },
  { id: "v002-02", word: "consolidate", pos: "v.", ko: ["강화하다", "통합하다"], freq: 2,
    roots: ["com", "solid"], hint: "con(=com, 함께) + solid(단단한) → 흩어진 것을 한 덩어리로 단단하게 만들다",
    ex: { en: "The firm consolidated its three branches into one.", ko: "그 회사는 세 지점을 하나로 통합했다." },
    syn: ["strengthen", "merge"] },
  { id: "v002-03", word: "constitute", pos: "v.", ko: ["구성하다", "~에 해당하다"], freq: 1,
    roots: ["com", "stitut"], hint: "con(=com, 함께) + stitut(세우다) → 함께 세워 하나를 이루다",
    ex: { en: "Women constitute half of the workforce.", ko: "여성이 노동력의 절반을 구성한다." },
    syn: ["make up", "form"] },
  { id: "v002-04", word: "constrain", pos: "v.", ko: ["제약하다", "억누르다"], freq: 2,
    roots: ["com", "strain"], hint: "con(=com, 함께) + strain(묶다) → 꽉 묶어 못 움직이게 하다",
    ex: { en: "A tight budget constrains our choices.", ko: "빠듯한 예산이 우리의 선택을 제약한다." },
    syn: ["restrict", "limit"] },
  { id: "v002-05", word: "consult", pos: "v.", ko: ["상의하다", "참고하다"], freq: 1,
    roots: ["com", "sult"], hint: "con(=com, 함께) + sult(의논하다) → 함께 머리를 맞대고 묻다",
    ex: { en: "You should consult a doctor before taking it.", ko: "복용 전에 의사와 상의해야 한다." },
    syn: ["seek advice", "refer to"] },
  { id: "v002-06", word: "consume", pos: "v.", ko: ["소비하다", "다 써버리다"], freq: 1,
    roots: ["com", "sum"], hint: "con(=com, 완전히) + sum(취하다) → 남김없이 취해 버리다",
    ex: { en: "Cars consume most of the imported oil.", ko: "자동차가 수입 석유의 대부분을 소비한다." },
    syn: ["use up", "devour"] },
  { id: "v002-07", word: "contradict", pos: "v.", ko: ["반박하다", "모순되다"], freq: 1,
    roots: ["contra", "dic"], hint: "contra(반대로) + dic(말하다) → 반대로 말하다",
    ex: { en: "The witness contradicted his earlier statement.", ko: "그 증인은 앞선 진술과 모순되는 말을 했다." },
    syn: ["deny", "oppose"] },
  { id: "v002-08", word: "convey", pos: "v.", ko: ["전달하다", "실어 나르다"], freq: 1,
    roots: ["com", "via"], hint: "con(=com, 함께) + vey(=via, 길) → 길을 따라 함께 실어 보내다",
    ex: { en: "Words alone cannot convey my gratitude.", ko: "말만으로는 내 고마움을 전할 수 없다." },
    syn: ["communicate", "transport"] },
  { id: "v002-09", word: "convince", pos: "v.", ko: ["확신시키다", "설득하다"], freq: 1,
    roots: ["com", "vinc"], hint: "con(=com, 완전히) + vinc(이기다) → 상대의 의심을 완전히 이겨 내다",
    ex: { en: "He convinced me to change my mind.", ko: "그가 나를 설득해 마음을 바꾸게 했다." },
    syn: ["persuade", "assure"] },
  { id: "v002-10", word: "cooperate", pos: "v.", ko: ["협력하다"], freq: 2,
    roots: ["com", "oper"], hint: "co(=com, 함께) + oper(일하다) → 함께 일하다",
    ex: { en: "The two agencies agreed to cooperate.", ko: "두 기관은 협력하기로 합의했다." },
    syn: ["collaborate", "work together"] },
  { id: "v002-11", word: "correspond", pos: "v.", ko: ["일치하다", "서신을 주고받다"], freq: 2,
    roots: ["com", "spond"], hint: "cor(=com, 서로) + spond(답하다) → 서로 응답하듯 맞아떨어지다",
    ex: { en: "His account does not correspond with the facts.", ko: "그의 설명은 사실과 일치하지 않는다." },
    syn: ["match", "communicate"] },
  { id: "v002-12", word: "declare", pos: "v.", ko: ["선언하다", "신고하다"], freq: 1,
    roots: ["de", "clar"], hint: "de(완전히) + clar(맑은) → 훤히 드러나게 밝히다",
    ex: { en: "The government declared a state of emergency.", ko: "정부는 비상사태를 선포했다." },
    syn: ["announce", "proclaim"] },
  { id: "v002-13", word: "decline", pos: "v./n.", ko: ["거절하다", "감소하다", "감소"], freq: 1,
    roots: ["de", "clin"], hint: "de(아래로) + clin(기울다) → 아래로 기울다 · 고개를 돌려 물리다",
    ex: { en: "Sales declined sharply last quarter.", ko: "지난 분기에 매출이 급감했다." },
    syn: ["refuse", "decrease"] },
  { id: "v002-14", word: "dedicate", pos: "v.", ko: ["헌신하다", "바치다"], freq: 2,
    roots: ["de", "dic"], hint: "de(완전히) + dic(선언하다) → 이건 네 것이라고 선언하며 바치다",
    ex: { en: "She dedicated her life to public service.", ko: "그녀는 평생을 공직에 바쳤다." },
    syn: ["devote", "commit"] },
  { id: "v002-15", word: "deduce", pos: "v.", ko: ["추론하다", "연역하다"], freq: 2,
    roots: ["de", "duc"], hint: "de(아래로) + duc(이끌다) → 사실에서 결론을 끌어내리다",
    ex: { en: "From the clues we can deduce the motive.", ko: "단서들로부터 동기를 추론할 수 있다." },
    syn: ["infer", "conclude"] },
  { id: "v002-16", word: "defect", pos: "n./v.", ko: ["결함", "망명하다"], freq: 2,
    roots: ["de", "fect"], hint: "de(모자라게) + fect(하다) → 덜 만들어진 부분",
    ex: { en: "The recall was caused by a design defect.", ko: "그 리콜은 설계 결함 때문이었다." },
    syn: ["flaw", "shortcoming"] },
  { id: "v002-17", word: "defer", pos: "v.", ko: ["연기하다", "따르다"], freq: 2,
    roots: ["de", "fer"], hint: "de(떨어져) + fer(나르다) → 뒤로 밀어 옮겨 두다",
    ex: { en: "They deferred the decision until next month.", ko: "그들은 결정을 다음 달로 미뤘다." },
    syn: ["postpone", "put off"] },
  { id: "v002-18", word: "deficient", pos: "adj.", ko: ["부족한", "결함이 있는"], freq: 2,
    roots: ["de", "fect"], hint: "de(모자라게) + fic(=fect, 하다) → 채워야 할 만큼 안 된 상태",
    ex: { en: "The diet is deficient in vitamin D.", ko: "그 식단은 비타민 D가 부족하다." },
    syn: ["lacking", "inadequate"] },
  { id: "v002-19", word: "define", pos: "v.", ko: ["정의하다", "규정하다"], freq: 1,
    roots: ["de", "fin"], hint: "de(완전히) + fin(경계) → 경계를 그어 뜻을 확정하다",
    ex: { en: "The law clearly defines the term.", ko: "그 법은 해당 용어를 명확히 정의한다." },
    syn: ["specify", "determine"] },
  { id: "v002-20", word: "degrade", pos: "v.", ko: ["저하시키다", "품위를 떨어뜨리다"], freq: 2,
    roots: ["de", "grad"], hint: "de(아래로) + grad(단계) → 등급을 한 칸 아래로 내리다",
    ex: { en: "Plastic waste degrades the soil.", ko: "플라스틱 쓰레기가 토양을 악화시킨다." },
    syn: ["worsen", "demean"] },
  { id: "v002-21", word: "delegate", pos: "v./n.", ko: ["위임하다", "대표"], freq: 2,
    roots: ["de", "leg"], hint: "de(떨어져) + leg(보내다) → 권한을 떼어 남에게 보내다",
    ex: { en: "Good leaders delegate tasks to their staff.", ko: "훌륭한 지도자는 직원에게 업무를 위임한다." },
    syn: ["entrust", "representative"] },
  { id: "v002-22", word: "deliberate", pos: "adj./v.", ko: ["고의의", "신중한", "숙고하다"], freq: 1,
    roots: ["de", "libr"], hint: "de(완전히) + libr(저울) → 저울에 충분히 달아 본 → 신중한·일부러 한",
    ex: { en: "The damage was clearly deliberate.", ko: "그 훼손은 명백히 고의적이었다." },
    syn: ["intentional", "consider"] },
  { id: "v002-23", word: "demonstrate", pos: "v.", ko: ["입증하다", "보여주다", "시위하다"], freq: 1,
    roots: ["de", "monstr"], hint: "de(완전히) + monstr(보이다) → 눈앞에 다 보여 주다",
    ex: { en: "The study demonstrates a clear link.", ko: "그 연구는 명확한 연관성을 입증한다." },
    syn: ["prove", "show"] },
  { id: "v002-24", word: "denote", pos: "v.", ko: ["나타내다", "의미하다"], freq: 3,
    roots: ["de", "not"], hint: "de(완전히) + not(표시) → 표시로 콕 집어 가리키다",
    ex: { en: "A red light denotes danger.", ko: "빨간 불은 위험을 나타낸다." },
    syn: ["indicate", "signify"] },
  { id: "v002-25", word: "deprive", pos: "v.", ko: ["박탈하다", "빼앗다"], freq: 1,
    roots: ["de", "priv"], hint: "de(떨어져) + priv(빼앗다) → 가진 것을 떼어 가져가다",
    ex: { en: "War deprived them of their homes.", ko: "전쟁이 그들에게서 집을 빼앗았다." },
    syn: ["strip", "dispossess"] },
  { id: "v002-26", word: "derive", pos: "v.", ko: ["유래하다", "얻다"], freq: 1,
    roots: ["de", "riv"], hint: "de(~로부터) + riv(강) → 강에서 물길을 끌어오다",
    ex: { en: "The word derives from Latin.", ko: "그 단어는 라틴어에서 유래한다." },
    syn: ["originate", "obtain"] },
  { id: "v002-27", word: "detect", pos: "v.", ko: ["발견하다", "감지하다"], freq: 1,
    roots: ["de", "tect"], hint: "de(반대로) + tect(덮다) → 덮개를 걷어 찾아내다",
    ex: { en: "The sensor detects even small leaks.", ko: "그 센서는 작은 누출까지 감지한다." },
    syn: ["discover", "sense"] },
  { id: "v002-28", word: "deter", pos: "v.", ko: ["단념시키다", "억제하다"], freq: 2,
    roots: ["de", "ter"], hint: "de(떨어져) + ter(겁주다) → 겁을 줘 물러나게 하다",
    ex: { en: "Heavy fines deter illegal parking.", ko: "높은 벌금이 불법 주차를 억제한다." },
    syn: ["discourage", "prevent"] },
  { id: "v002-29", word: "deteriorate", pos: "v.", ko: ["악화되다", "저하되다"], freq: 1,
    roots: ["deterior"], hint: "deterior(더 나쁜) → 더 나쁜 쪽으로 굴러가다",
    ex: { en: "His health deteriorated over the winter.", ko: "겨울 동안 그의 건강이 악화되었다." },
    syn: ["worsen", "decline"] },
  { id: "v002-30", word: "devote", pos: "v.", ko: ["바치다", "쏟다"], freq: 1,
    roots: ["de", "vot"], hint: "de(완전히) + vot(맹세) → 맹세하듯 통째로 바치다",
    ex: { en: "He devotes weekends to volunteer work.", ko: "그는 주말을 자원봉사에 쏟는다." },
    syn: ["dedicate", "commit"] },
  { id: "v002-31", word: "diminish", pos: "v.", ko: ["줄이다", "감소하다"], freq: 1,
    roots: ["de", "min-small"], hint: "di(=de, 아래로) + min(작은) → 조금씩 깎아 작게 만들다",
    ex: { en: "Interest in the sport has diminished.", ko: "그 종목에 대한 관심이 줄었다." },
    syn: ["reduce", "decrease"] },
  { id: "v002-32", word: "discard", pos: "v.", ko: ["버리다", "폐기하다"], freq: 2,
    roots: ["dis"], hint: "dis(떨어져) + card(카드) → 쓸모없는 카드를 손에서 던져 버리다",
    ex: { en: "Please discard any expired medicine.", ko: "유통기한이 지난 약은 폐기하세요." },
    syn: ["throw away", "dump"] },
  { id: "v002-33", word: "discern", pos: "v.", ko: ["식별하다", "분간하다"], freq: 2,
    roots: ["dis", "cern"], hint: "dis(따로) + cern(가르다) → 갈라놓고 어느 쪽인지 가려내다",
    ex: { en: "It is hard to discern the difference.", ko: "그 차이를 분간하기는 어렵다." },
    syn: ["distinguish", "perceive"] },
  { id: "v002-34", word: "discourage", pos: "v.", ko: ["낙담시키다", "단념시키다"], freq: 2,
    roots: ["dis"], hint: "dis(없애다) + courage(용기) → 용기를 빼앗다",
    ex: { en: "Do not let one failure discourage you.", ko: "한 번의 실패가 너를 낙담시키게 두지 마라." },
    syn: ["dishearten", "deter"] },
  { id: "v002-35", word: "dispose", pos: "v.", ko: ["처리하다", "배치하다"], freq: 1,
    roots: ["dis", "pos"], hint: "dis(따로) + pos(놓다) → 따로 놓아 치우다 · 자리를 잡아 놓다",
    ex: { en: "Please dispose of the batteries properly.", ko: "배터리는 올바르게 처리하세요." },
    syn: ["get rid of", "arrange"] },
  { id: "v002-36", word: "dispute", pos: "v./n.", ko: ["논쟁하다", "분쟁"], freq: 1,
    roots: ["dis", "put"], hint: "dis(따로) + put(셈하다·생각하다) → 서로 다르게 셈해 맞붙다",
    ex: { en: "The two nations dispute the border.", ko: "두 나라는 국경을 두고 다툰다." },
    syn: ["argue", "conflict"] },
  { id: "v002-37", word: "disrupt", pos: "v.", ko: ["방해하다", "지장을 주다"], freq: 1,
    roots: ["dis", "rupt"], hint: "dis(따로) + rupt(깨다) → 흐름을 깨뜨려 끊다",
    ex: { en: "The strike disrupted train services.", ko: "파업이 열차 운행에 지장을 주었다." },
    syn: ["interrupt", "upset"] },
  { id: "v002-38", word: "distinguish", pos: "v.", ko: ["구별하다", "두드러지게 하다"], freq: 1,
    roots: ["dis", "stingu"], hint: "dis(따로) + stingu(찌르다) → 찔러 표시해 따로 구분하다",
    ex: { en: "Can you distinguish the original from the copy?", ko: "원본과 사본을 구별할 수 있나요?" },
    syn: ["differentiate", "tell apart"] },
  { id: "v002-39", word: "distort", pos: "v.", ko: ["왜곡하다", "비틀다"], freq: 2,
    roots: ["dis", "tort"], hint: "dis(따로) + tort(비틀다) → 원래 모양에서 비틀어 놓다",
    ex: { en: "The article distorted his remarks.", ko: "그 기사는 그의 발언을 왜곡했다." },
    syn: ["twist", "misrepresent"] },
  { id: "v002-40", word: "distribute", pos: "v.", ko: ["분배하다", "유통시키다"], freq: 1,
    roots: ["dis", "tribut"], hint: "dis(따로) + tribut(나누어 주다) → 몫을 갈라 나눠 주다",
    ex: { en: "Volunteers distributed food to the victims.", ko: "자원봉사자들이 이재민에게 식량을 나눠 주었다." },
    syn: ["hand out", "allocate"] },
  { id: "v002-41", word: "diverse", pos: "adj.", ko: ["다양한", "상이한"], freq: 1,
    roots: ["dis", "vers"], hint: "di(=dis, 따로) + vers(돌다) → 제각기 다른 방향으로 돌아선",
    ex: { en: "The city has a diverse population.", ko: "그 도시는 인구 구성이 다양하다." },
    syn: ["varied", "different"] },
  { id: "v002-42", word: "dominate", pos: "v.", ko: ["지배하다", "우세하다"], freq: 1,
    roots: ["domin"], hint: "domin(주인) → 주인 노릇을 하다",
    ex: { en: "One firm dominates the entire market.", ko: "한 기업이 시장 전체를 지배한다." },
    syn: ["control", "prevail"] },
  { id: "v002-43", word: "elaborate", pos: "adj./v.", ko: ["정교한", "자세히 설명하다"], freq: 2,
    roots: ["ex", "labor"], hint: "e(=ex, 밖으로) + labor(노동) → 공을 들여 밖으로 다듬어 내다",
    ex: { en: "Could you elaborate on that point?", ko: "그 점을 좀 더 자세히 설명해 주시겠어요?" },
    syn: ["detailed", "expand on"] },
  { id: "v002-44", word: "eliminate", pos: "v.", ko: ["제거하다", "탈락시키다"], freq: 1,
    roots: ["ex", "limin"], hint: "e(=ex, 밖으로) + limin(문지방) → 문지방 밖으로 내보내다",
    ex: { en: "The new system eliminates paperwork.", ko: "새 시스템은 서류 작업을 없앤다." },
    syn: ["remove", "get rid of"] },
  { id: "v002-45", word: "emerge", pos: "v.", ko: ["나타나다", "드러나다"], freq: 1,
    roots: ["ex", "merg"], hint: "e(=ex, 밖으로) + merg(잠기다) → 잠겨 있던 것이 물 밖으로 솟아오르다",
    ex: { en: "New evidence emerged during the trial.", ko: "재판 중에 새로운 증거가 나타났다." },
    syn: ["appear", "come out"] },
  { id: "v002-46", word: "emphasize", pos: "v.", ko: ["강조하다"], freq: 1,
    roots: ["in", "phas"], hint: "em(=in, 안에) + phas(보이다) → 그 안에서 특히 보이게 만들다",
    ex: { en: "The report emphasizes the need for reform.", ko: "그 보고서는 개혁의 필요성을 강조한다." },
    syn: ["stress", "highlight"] },
  { id: "v002-47", word: "enact", pos: "v.", ko: ["제정하다", "시행하다"], freq: 2,
    roots: ["in", "act"], hint: "en(=in, ~하게 만들다) + act(행위) → 법을 실제 행위로 만들다",
    ex: { en: "Parliament enacted a new privacy law.", ko: "의회는 새로운 개인정보 보호법을 제정했다." },
    syn: ["legislate", "implement"] },
  { id: "v002-48", word: "endure", pos: "v.", ko: ["견디다", "지속되다"], freq: 1,
    roots: ["in", "dur"], hint: "en(=in, 안에서) + dur(단단한) → 단단하게 버텨 내다",
    ex: { en: "The refugees endured months of hardship.", ko: "난민들은 몇 달간의 고난을 견뎠다." },
    syn: ["bear", "last"] },
  { id: "v002-49", word: "enforce", pos: "v.", ko: ["시행하다", "집행하다"], freq: 1,
    roots: ["in"], hint: "en(=in, ~하게 만들다) + force(힘) → 힘을 실어 지키게 만들다",
    ex: { en: "Police strictly enforce the speed limit.", ko: "경찰은 속도 제한을 엄격히 집행한다." },
    syn: ["implement", "impose"] },
  { id: "v002-50", word: "enhance", pos: "v.", ko: ["향상시키다", "높이다"], freq: 1,
    roots: ["in", "alt"], hint: "en(=in, ~하게 만들다) + hance(=alt, 높은) → 수준을 한 단 높이다",
    ex: { en: "Training can enhance job performance.", ko: "교육은 업무 성과를 향상시킬 수 있다." },
    syn: ["improve", "boost"] },
];
