// DAY 6 — 빈출 명사 ①(제도·사회·경제). 파일 성격은 day-001.js 헤더 참고(동적 import 전용).
//
// 공무원 영어 지문은 행정·정책·통계가 소재라, 동사를 아무리 알아도 여기 명사를 모르면
// 주어와 목적어가 통째로 비어 버린다. 그래서 2단계에 한 DAY를 통으로 명사에 할당했다.
export const WORDS = [
  { id: "v006-01", word: "adversity", pos: "n.", ko: ["역경", "고난"], freq: 2,
    roots: ["ad", "vers"], hint: "ad(~쪽으로) + vers(돌다) → 세상이 나를 향해 맞돌아선 형편",
    ex: { en: "He kept his humor in the face of adversity.", ko: "그는 역경 앞에서도 유머를 잃지 않았다." },
    syn: ["hardship", "misfortune"] },
  { id: "v006-02", word: "alliance", pos: "n.", ko: ["동맹", "제휴"], freq: 1,
    roots: ["ad", "lig"], hint: "al(=ad, ~쪽으로) + lianc(=lig, 묶다) → 서로 묶여 한편이 된 사이",
    ex: { en: "The two parties formed an alliance.", ko: "두 정당은 동맹을 맺었다." },
    syn: ["coalition", "partnership"] },
  { id: "v006-03", word: "autonomy", pos: "n.", ko: ["자치권", "자율"], freq: 2,
    roots: ["auto", "nom"], hint: "auto(스스로) + nom(법, 규칙) → 제 규칙을 스스로 세움",
    ex: { en: "The region was granted greater autonomy.", ko: "그 지역은 더 큰 자치권을 받았다." },
    syn: ["self-rule", "independence"] },
  { id: "v006-04", word: "bias", pos: "n./v.", ko: ["편향", "선입견", "치우치게 하다"], freq: 1,
    roots: [], sound: "바이어스(bias) — 저울추가 한쪽으로 바짝 기울어 버린 모습",
    hint: "어원이 뚜렷하지 않은 단어라 소리로 잡는다 — 저울이 한쪽으로 바짝 기운 그림.",
    ex: { en: "The study found a clear bias in the sample.", ko: "그 연구는 표본에서 뚜렷한 편향을 발견했다." },
    syn: ["prejudice", "slant"] },
  { id: "v006-05", word: "bureaucracy", pos: "n.", ko: ["관료제", "번잡한 행정 절차"], freq: 2,
    roots: ["bureau", "crac"], hint: "bureau(사무실 책상) + crac(지배) → 책상이 지배하는 체제",
    ex: { en: "Applicants complain about excessive bureaucracy.", ko: "지원자들은 지나친 행정 절차에 불평한다." },
    syn: ["red tape", "officialdom"] },
  { id: "v006-06", word: "census", pos: "n.", ko: ["인구 조사"], freq: 2,
    roots: ["cens"], hint: "cens(세다, 평가하다) → 사람을 하나하나 세어 적는 일",
    ex: { en: "The census is taken every five years.", ko: "인구 조사는 5년마다 실시된다." },
    syn: ["headcount", "survey"] },
  { id: "v006-07", word: "coalition", pos: "n.", ko: ["연합", "연립"], freq: 2,
    roots: ["com", "ol"], hint: "co(=com, 함께) + al(=ol, 자라다) → 함께 자라 하나가 된 무리",
    ex: { en: "Three parties formed a coalition government.", ko: "세 정당이 연립 정부를 구성했다." },
    syn: ["alliance", "bloc"] },
  { id: "v006-08", word: "commodity", pos: "n.", ko: ["상품", "원자재"], freq: 2,
    roots: ["com", "mod"], hint: "com(함께) + mod(알맞은 정도) → 쓰기 알맞게 다듬어 내놓은 물건",
    ex: { en: "Rice is a basic commodity in Asia.", ko: "쌀은 아시아의 기초 상품이다." },
    syn: ["goods", "product"] },
  { id: "v006-09", word: "consensus", pos: "n.", ko: ["합의", "의견 일치"], freq: 1,
    roots: ["com", "sent"], hint: "con(=com, 함께) + sens(=sent, 느끼다) → 다 같이 똑같이 느낌",
    ex: { en: "The panel reached a consensus after long debate.", ko: "위원단은 긴 토론 끝에 합의에 이르렀다." },
    syn: ["agreement", "accord"] },
  { id: "v006-10", word: "deficit", pos: "n.", ko: ["적자", "부족분"], freq: 1,
    roots: ["de", "fect"], hint: "de(아래로) + fic(=fect, 하다) → 채웠어야 할 것에 못 미친 만큼",
    ex: { en: "The budget deficit widened last quarter.", ko: "지난 분기에 재정 적자가 커졌다." },
    syn: ["shortfall", "gap"] },
  { id: "v006-11", word: "dilemma", pos: "n.", ko: ["딜레마", "진퇴양난"], freq: 2,
    roots: ["di-two", "lemma"], hint: "di(둘) + lemma(전제) → 놓인 전제가 둘뿐이라 어느 쪽도 곤란한",
    ex: { en: "He faced a moral dilemma.", ko: "그는 도덕적 딜레마에 놓였다." },
    syn: ["quandary", "predicament"] },
  { id: "v006-12", word: "discrepancy", pos: "n.", ko: ["불일치", "차이"], freq: 2,
    roots: ["dis", "crep"], hint: "dis(따로) + crep(삐걱거리다) → 따로 놀며 삐걱대는 어긋남",
    ex: { en: "Auditors found a discrepancy in the accounts.", ko: "감사관들은 회계에서 불일치를 발견했다." },
    syn: ["inconsistency", "mismatch"] },
  { id: "v006-13", word: "disparity", pos: "n.", ko: ["격차", "불균형"], freq: 2,
    roots: ["dis", "par-equal"], hint: "dis(아닌) + par(동등한) → 동등하지 않은 상태",
    ex: { en: "There is a wide disparity in wages.", ko: "임금에 큰 격차가 있다." },
    syn: ["gap", "inequality"] },
  { id: "v006-14", word: "epidemic", pos: "n./adj.", ko: ["전염병", "유행병의"], freq: 2,
    roots: ["epi", "dem"], hint: "epi(~사이에) + dem(사람들) → 사람들 사이로 번져 도는 것",
    ex: { en: "The epidemic spread to three provinces.", ko: "그 전염병은 세 개 도로 번졌다." },
    syn: ["outbreak", "plague"] },
  { id: "v006-15", word: "equity", pos: "n.", ko: ["형평", "공정"], freq: 2,
    roots: ["equ"], hint: "equ(같은) → 저마다에게 같은 몫이 돌아가게 함",
    ex: { en: "The reform aims at greater equity in health care.", ko: "그 개혁은 의료의 형평성을 높이려는 것이다." },
    syn: ["fairness", "justice"] },
  { id: "v006-16", word: "heritage", pos: "n.", ko: ["문화유산", "전통"], freq: 1,
    roots: ["herit"], hint: "herit(물려받다) → 물려받아 내려온 것",
    ex: { en: "The temple is on the world heritage list.", ko: "그 사찰은 세계 유산 목록에 올라 있다." },
    syn: ["legacy", "tradition"] },
  { id: "v006-17", word: "hierarchy", pos: "n.", ko: ["위계", "서열"], freq: 2,
    roots: ["hier", "arch"], hint: "hier(신성한) + arch(우두머리) → 위에서 아래로 줄 세운 성직 서열",
    ex: { en: "The company has a strict hierarchy.", ko: "그 회사는 서열이 엄격하다." },
    syn: ["ranking", "pecking order"] },
  { id: "v006-18", word: "immunity", pos: "n.", ko: ["면역", "면제"], freq: 2,
    roots: ["in-neg", "mun"], hint: "im(=in, 아닌) + mun(공적 의무) → 져야 할 의무를 지지 않음",
    ex: { en: "Vaccination gives immunity to the disease.", ko: "백신 접종은 그 병에 대한 면역을 준다." },
    syn: ["resistance", "exemption"] },
  { id: "v006-19", word: "incentive", pos: "n.", ko: ["유인책", "동기"], freq: 1,
    roots: ["in", "cant"], hint: "in(안으로) + cent(=cant, 노래해 부추기다) → 마음을 부추겨 움직이게 하는 것",
    ex: { en: "Tax breaks act as an incentive to invest.", ko: "세금 감면은 투자 유인책으로 작용한다." },
    syn: ["inducement", "spur"] },
  { id: "v006-20", word: "infrastructure", pos: "n.", ko: ["기반 시설"], freq: 1,
    roots: ["infra", "struct"], hint: "infra(아래) + struct(세우다) → 아래에 깔아 세워 둔 것",
    ex: { en: "The city needs to repair its aging infrastructure.", ko: "그 도시는 노후한 기반 시설을 손봐야 한다." },
    syn: ["facilities", "base"] },
  { id: "v006-21", word: "initiative", pos: "n.", ko: ["주도권", "새 계획"], freq: 1,
    roots: ["init"], hint: "init(들어가다, 시작하다) → 남보다 먼저 발을 들여놓음",
    ex: { en: "She took the initiative and called a meeting.", ko: "그녀가 주도해서 회의를 소집했다." },
    syn: ["lead", "enterprise"] },
  { id: "v006-22", word: "integrity", pos: "n.", ko: ["진실성", "온전함"], freq: 1,
    roots: ["integr"], hint: "integr(온전한, 손대지 않은) → 어디도 손타지 않고 온전한 상태",
    ex: { en: "The audit questioned the integrity of the data.", ko: "감사는 그 자료의 진실성에 의문을 제기했다." },
    syn: ["honesty", "soundness"] },
  { id: "v006-23", word: "jurisdiction", pos: "n.", ko: ["관할권", "사법권"], freq: 2,
    roots: ["jur", "dic"], hint: "juris(=jur, 법) + dic(말하다) → 법을 말할 수 있는 범위",
    ex: { en: "The case falls outside our jurisdiction.", ko: "그 사건은 우리 관할 밖이다." },
    syn: ["authority", "remit"] },
  { id: "v006-24", word: "legacy", pos: "n.", ko: ["유산", "물려준 것"], freq: 1,
    roots: ["leg"], hint: "leg(위임해 보내다) → 뒤에 남겨 보낸 것",
    ex: { en: "The war left a bitter legacy.", ko: "그 전쟁은 쓰라린 유산을 남겼다." },
    syn: ["inheritance", "bequest"] },
  { id: "v006-25", word: "mandate", pos: "n./v.", ko: ["위임", "명령하다"], freq: 2,
    roots: ["man", "da"], hint: "man(손) + da(주다) → 손에 쥐여 주며 맡김",
    ex: { en: "The new government claimed a clear mandate.", ko: "새 정부는 분명한 위임을 받았다고 주장했다." },
    syn: ["authorization", "decree"] },
  { id: "v006-26", word: "margin", pos: "n.", ko: ["차이", "여백", "이윤"], freq: 1,
    roots: ["marg"], hint: "marg(가장자리) → 가장자리에 남은 폭",
    ex: { en: "The party won by a narrow margin.", ko: "그 정당은 근소한 차이로 이겼다." },
    syn: ["edge", "leeway"] },
  { id: "v006-27", word: "mortality", pos: "n.", ko: ["사망률", "죽을 운명"], freq: 2,
    roots: ["mort"], hint: "mort(죽음) → 죽음에 매인 정도",
    ex: { en: "Infant mortality has fallen sharply.", ko: "영아 사망률이 크게 떨어졌다." },
    syn: ["death rate", "fatality"] },
  { id: "v006-28", word: "norm", pos: "n.", ko: ["규범", "표준"], freq: 1,
    roots: ["norm"], hint: "norm(자, 기준) → 재는 자로 삼는 기준",
    ex: { en: "Social norms differ from country to country.", ko: "사회 규범은 나라마다 다르다." },
    syn: ["standard", "convention"] },
  { id: "v006-29", word: "obligation", pos: "n.", ko: ["의무", "책무"], freq: 1,
    roots: ["ob", "lig"], hint: "ob(~쪽으로) + lig(묶다) → 그쪽으로 묶여 벗어날 수 없는 것",
    ex: { en: "Employers have a legal obligation to report injuries.", ko: "고용주는 재해를 신고할 법적 의무가 있다." },
    syn: ["duty", "commitment"] },
  { id: "v006-30", word: "paradigm", pos: "n.", ko: ["틀", "전형"], freq: 2,
    roots: ["para"], hint: "para(나란히) + digm(본보기로 보임) → 나란히 놓고 따라 하는 본보기",
    ex: { en: "The discovery caused a paradigm shift in physics.", ko: "그 발견은 물리학의 틀을 바꿔 놓았다." },
    syn: ["model", "framework"] },
  { id: "v006-31", word: "perspective", pos: "n.", ko: ["관점", "시각"], freq: 1,
    roots: ["per", "spect"], hint: "per(통과해) + spect(보다) → 죽 꿰뚫어 보는 자리",
    ex: { en: "Try to see the issue from a different perspective.", ko: "그 문제를 다른 관점에서 보려고 해 보라." },
    syn: ["viewpoint", "outlook"] },
  { id: "v006-32", word: "petition", pos: "n./v.", ko: ["청원", "청원하다"], freq: 2,
    roots: ["pet"], hint: "pet(추구하다) → 구하는 바를 적어 올림",
    ex: { en: "Residents filed a petition against the plan.", ko: "주민들은 그 계획에 반대하는 청원을 냈다." },
    syn: ["appeal", "plea"] },
  { id: "v006-33", word: "poverty", pos: "n.", ko: ["빈곤", "가난"], freq: 1,
    roots: ["pauper"], hint: "pover(=pauper, 가난한) → 가난한 상태 그 자체",
    ex: { en: "Millions still live in extreme poverty.", ko: "수백만 명이 여전히 극빈 상태로 산다." },
    syn: ["destitution", "need"] },
  { id: "v006-34", word: "precedent", pos: "n.", ko: ["선례", "판례"], freq: 1,
    roots: ["pre", "ced"], hint: "pre(앞서) + ced(가다) → 앞서 지나가 남긴 자국",
    ex: { en: "The ruling set an important precedent.", ko: "그 판결은 중요한 선례를 남겼다." },
    syn: ["example", "model case"] },
  { id: "v006-35", word: "premise", pos: "n.", ko: ["전제"], freq: 2,
    roots: ["pre", "mit"], hint: "pre(미리) + mis(=mit, 보내다) → 논의 앞에 미리 내보낸 것",
    ex: { en: "The argument rests on a false premise.", ko: "그 주장은 틀린 전제 위에 서 있다." },
    syn: ["assumption", "postulate"] },
  { id: "v006-36", word: "privilege", pos: "n.", ko: ["특권", "특전"], freq: 1,
    roots: ["priv", "leg"], hint: "priv(개인의) + leg(법) → 특정한 개인에게만 주는 법",
    ex: { en: "Education should be a right, not a privilege.", ko: "교육은 특권이 아니라 권리여야 한다." },
    syn: ["prerogative", "perk"] },
  { id: "v006-37", word: "prospect", pos: "n.", ko: ["전망", "가능성"], freq: 1,
    roots: ["pro", "spect"], hint: "pro(앞을) + spect(보다) → 앞을 내다본 그림",
    ex: { en: "The prospect of a pay raise cheered the staff.", ko: "임금 인상 전망이 직원들을 기쁘게 했다." },
    syn: ["outlook", "likelihood"] },
  { id: "v006-38", word: "quota", pos: "n.", ko: ["할당량"], freq: 2,
    roots: ["quot"], hint: "quot(얼마, 몇) → 몇 개씩으로 잘라 준 몫",
    ex: { en: "Each region has a hiring quota.", ko: "지역마다 채용 할당량이 있다." },
    syn: ["allotment", "share"] },
  { id: "v006-39", word: "ratio", pos: "n.", ko: ["비율"], freq: 1,
    roots: ["rat"], hint: "rat(셈하다, 헤아리다) → 둘을 견줘 셈한 값",
    ex: { en: "The ratio of teachers to students is one to twenty.", ko: "교사 대 학생 비율은 1 대 20이다." },
    syn: ["proportion", "rate"] },
  { id: "v006-40", word: "recession", pos: "n.", ko: ["경기 침체"], freq: 1,
    roots: ["re", "ced"], hint: "re(뒤로) + cess(=ced, 가다) → 경기가 뒤로 물러남",
    ex: { en: "The country slipped into recession.", ko: "그 나라는 경기 침체에 빠졌다." },
    syn: ["downturn", "slump"] },
  { id: "v006-41", word: "reform", pos: "n./v.", ko: ["개혁", "개혁하다"], freq: 1,
    roots: ["re", "form"], hint: "re(다시) + form(모양) → 모양을 다시 잡다",
    ex: { en: "The government promised to reform the tax system.", ko: "정부는 조세 제도를 개혁하겠다고 약속했다." },
    syn: ["overhaul", "amend"] },
  { id: "v006-42", word: "residue", pos: "n.", ko: ["잔여물", "찌꺼기"], freq: 2,
    roots: ["re", "sed"], hint: "re(뒤에) + sid(=sed, 앉다) → 뒤에 앉은 채 남은 것",
    ex: { en: "A sticky residue was left on the surface.", ko: "표면에 끈적한 잔여물이 남았다." },
    syn: ["remnant", "leftover"] },
  { id: "v006-43", word: "revenue", pos: "n.", ko: ["세입", "수입"], freq: 1,
    roots: ["re", "ven"], hint: "re(되돌아) + ven(오다) → 나갔다가 되돌아 들어오는 돈",
    ex: { en: "Tax revenue fell for a third year.", ko: "세입이 3년째 줄었다." },
    syn: ["income", "proceeds"] },
  { id: "v006-44", word: "sanction", pos: "n./v.", ko: ["제재", "승인", "제재하다"], freq: 2,
    roots: ["sanct"], hint: "sanct(신성하게 정하다) → 위에서 정해 못 박은 조치",
    ex: { en: "The council imposed a sanction on the state.", ko: "이사회는 그 국가에 제재를 가했다." },
    syn: ["penalty", "approval"] },
  { id: "v006-45", word: "statute", pos: "n.", ko: ["법령", "성문법"], freq: 2,
    roots: ["stitut"], hint: "stat(=stitut, 세우다) → 문서로 세워 둔 규정",
    ex: { en: "The practice is banned by statute.", ko: "그 관행은 법령으로 금지돼 있다." },
    syn: ["law", "act"] },
  { id: "v006-46", word: "surplus", pos: "n./adj.", ko: ["잉여", "흑자", "남는"], freq: 2,
    roots: ["super", "plus"], hint: "sur(=super, 위로) + plus(더) → 필요분 위로 더 남은 몫",
    ex: { en: "The country ran a trade surplus last year.", ko: "그 나라는 작년에 무역 흑자를 냈다." },
    syn: ["excess", "overflow"] },
  { id: "v006-47", word: "transition", pos: "n.", ko: ["전환", "이행"], freq: 1,
    roots: ["trans", "it"], hint: "trans(건너) + it(가다) → 건너서 다른 상태로 가는 일",
    ex: { en: "The transition to clean energy will take decades.", ko: "청정 에너지로의 전환에는 수십 년이 걸릴 것이다." },
    syn: ["shift", "changeover"] },
  { id: "v006-48", word: "tribute", pos: "n.", ko: ["헌사", "공물"], freq: 2,
    roots: ["tribut"], hint: "tribut(나누어 주다) → 위로 바쳐 올린 몫",
    ex: { en: "The concert was a tribute to the late singer.", ko: "그 공연은 고인이 된 가수에게 바친 헌사였다." },
    syn: ["homage", "tariff"] },
  { id: "v006-49", word: "vicinity", pos: "n.", ko: ["인근", "부근"], freq: 2,
    roots: ["vicin"], hint: "vicin(이웃, 가까운) → 이웃해 있는 언저리",
    ex: { en: "Several schools are in the vicinity of the plant.", ko: "그 공장 인근에 학교가 여럿 있다." },
    syn: ["neighborhood", "proximity"] },
  { id: "v006-50", word: "welfare", pos: "n.", ko: ["복지", "안녕"], freq: 1,
    roots: ["fare"], hint: "well(잘) + fare(지내다) → 잘 지내게 해 주는 것",
    ex: { en: "The city expanded its welfare programs.", ko: "그 시는 복지 사업을 확대했다." },
    syn: ["well-being", "benefits"] },
];
