// DAY 7 — 빈출 동사 ②. 파일 성격은 day-001.js 헤더 참고(동적 import 전용).
//
// DAY 1~4에서 다루지 않은 접두사(ad·circ·sub·trans 계열과 그 밖의 어근)를 모았다.
// 같은 어근이 DAY를 넘나들며 되풀이되는 게 이 도구의 노림수라, 여기서 처음 보는 어근보다
// 앞 DAY에서 이미 만난 어근이 다시 나오는 쪽이 많다.
export const WORDS = [
  { id: "v007-01", word: "accompany", pos: "v.", ko: ["동행하다", "동반하다"], freq: 1,
    roots: ["ad", "com", "pan"], hint: "ac(=ad, ~쪽으로) + com(함께) + pan(빵) → 빵을 함께 먹으며 곁에 붙어 다니다",
    ex: { en: "An adult must accompany every child.", ko: "모든 아이는 어른이 동행해야 한다." },
    syn: ["escort", "go with"] },
  { id: "v007-02", word: "adjourn", pos: "v.", ko: ["휴정하다", "연기하다"], freq: 2,
    roots: ["ad", "journ"], hint: "ad(~로) + journ(날, 하루) → 다른 날로 미뤄 두다",
    ex: { en: "The judge adjourned the hearing until Tuesday.", ko: "판사는 심리를 화요일로 연기했다." },
    syn: ["suspend", "recess"] },
  { id: "v007-03", word: "allege", pos: "v.", ko: ["주장하다", "혐의를 제기하다"], freq: 2,
    roots: ["ad", "leg"], hint: "al(=ad, ~쪽으로) + leg(법) → 법정 쪽으로 내세워 말하다",
    ex: { en: "Prosecutors allege that he took bribes.", ko: "검찰은 그가 뇌물을 받았다고 주장한다." },
    syn: ["claim", "assert"] },
  { id: "v007-04", word: "amend", pos: "v.", ko: ["개정하다", "수정하다"], freq: 1,
    roots: ["ex", "mend"], hint: "a(=ex, 없애고) + mend(흠) → 흠을 걷어내다",
    ex: { en: "Congress voted to amend the law.", ko: "의회는 그 법을 개정하기로 표결했다." },
    syn: ["revise", "rectify"] },
  { id: "v007-05", word: "annex", pos: "v./n.", ko: ["병합하다", "부속 건물"], freq: 2,
    roots: ["ad", "nex"], hint: "an(=ad, ~쪽으로) + nex(묶다, 잇다) → 내 쪽에 갖다 붙여 매다",
    ex: { en: "The empire annexed the island in 1910.", ko: "그 제국은 1910년에 그 섬을 병합했다." },
    syn: ["absorb", "attach"] },
  { id: "v007-06", word: "appoint", pos: "v.", ko: ["임명하다", "정하다"], freq: 1,
    roots: ["ad", "punct"], hint: "ap(=ad, ~쪽으로) + point(=punct, 점) → 콕 집어 점을 찍다",
    ex: { en: "The mayor appointed a new chief.", ko: "시장은 새 국장을 임명했다." },
    syn: ["nominate", "designate"] },
  { id: "v007-07", word: "ascend", pos: "v.", ko: ["오르다", "상승하다"], freq: 2,
    roots: ["ad", "scend"], hint: "a(=ad, ~쪽으로) + scend(오르다) → 위쪽으로 올라가다",
    ex: { en: "The path ascends steeply from the river.", ko: "그 길은 강에서부터 가파르게 오른다." },
    syn: ["climb", "rise"] },
  { id: "v007-08", word: "assimilate", pos: "v.", ko: ["동화되다", "흡수하다"], freq: 2,
    roots: ["ad", "simil"], hint: "as(=ad, ~쪽으로) + simil(같은) → 주변과 같아지게 만들다",
    ex: { en: "Immigrants gradually assimilated into the local culture.", ko: "이민자들은 차츰 현지 문화에 동화됐다." },
    syn: ["absorb", "blend in"] },
  { id: "v007-09", word: "avert", pos: "v.", ko: ["막다", "피하다"], freq: 2,
    roots: ["ab", "vers"], hint: "a(=ab, 떨어져) + vert(=vers, 돌다) → 방향을 돌려 비껴가게 하다",
    ex: { en: "Quick action averted a disaster.", ko: "발 빠른 대응이 참사를 막았다." },
    syn: ["prevent", "ward off"] },
  { id: "v007-10", word: "circulate", pos: "v.", ko: ["순환하다", "유포되다"], freq: 1,
    roots: ["circ"], hint: "circ(둥근, 원) → 원을 그리며 돌고 돌다",
    ex: { en: "Rumors circulated quickly through the office.", ko: "소문이 사무실에 빠르게 퍼졌다." },
    syn: ["spread", "flow"] },
  { id: "v007-11", word: "coincide", pos: "v.", ko: ["일치하다", "동시에 일어나다"], freq: 2,
    roots: ["com", "in", "cid"], hint: "co(=com, 함께) + in(위에) + cid(떨어지다) → 같은 자리에 함께 떨어지다",
    ex: { en: "Her visit coincided with the festival.", ko: "그녀의 방문은 축제와 시기가 겹쳤다." },
    syn: ["agree", "overlap"] },
  { id: "v007-12", word: "commemorate", pos: "v.", ko: ["기념하다", "추모하다"], freq: 2,
    roots: ["com", "memor"], hint: "com(함께) + memor(기억) → 여럿이 함께 기억해 두다",
    ex: { en: "A statue commemorates the fallen soldiers.", ko: "동상 하나가 전사한 병사들을 기린다." },
    syn: ["honor", "observe"] },
  { id: "v007-13", word: "compile", pos: "v.", ko: ["편집하다", "모아 엮다"], freq: 2,
    roots: ["com", "pil"], hint: "com(함께) + pil(쌓다, 다발) → 여기저기서 모아 한 다발로 쌓다",
    ex: { en: "The team compiled a list of every complaint.", ko: "팀은 모든 민원을 모아 목록으로 만들었다." },
    syn: ["assemble", "collate"] },
  { id: "v007-14", word: "conceive", pos: "v.", ko: ["구상하다", "임신하다"], freq: 2,
    roots: ["com", "ceiv"], hint: "con(=com, 완전히) + ceiv(잡다) → 머릿속에 통째로 붙잡아 두다",
    ex: { en: "She conceived the idea while walking.", ko: "그녀는 걷다가 그 착상을 떠올렸다." },
    syn: ["devise", "imagine"] },
  { id: "v007-15", word: "confer", pos: "v.", ko: ["협의하다", "수여하다"], freq: 2,
    roots: ["com", "fer"], hint: "con(=com, 함께) + fer(나르다) → 서로 의견을 실어 나르다",
    ex: { en: "The judges conferred before announcing the winner.", ko: "심사위원들은 수상자 발표 전에 협의했다." },
    syn: ["consult", "bestow"] },
  { id: "v007-16", word: "contemplate", pos: "v.", ko: ["숙고하다", "응시하다"], freq: 2,
    roots: ["com", "templ"], hint: "con(=com, 완전히) + templ(신전, 살피는 구역) → 한자리에 서서 오래 살피다",
    ex: { en: "He contemplated leaving the job.", ko: "그는 일을 그만둘까 오래 고민했다." },
    syn: ["ponder", "gaze at"] },
  { id: "v007-17", word: "curtail", pos: "v.", ko: ["축소하다", "단축하다"], freq: 2,
    roots: ["curt"], hint: "curt(짧은) → 길이를 짧게 쳐내다",
    ex: { en: "The city curtailed bus service at night.", ko: "그 시는 야간 버스 운행을 축소했다." },
    syn: ["cut back", "trim"] },
  { id: "v007-18", word: "deplete", pos: "v.", ko: ["고갈시키다"], freq: 2,
    roots: ["de", "ple"], hint: "de(떨어져) + ple(채우다) → 채워 둔 것을 도로 빼내다",
    ex: { en: "Overfishing has depleted the stocks.", ko: "남획이 어족 자원을 고갈시켰다." },
    syn: ["exhaust", "drain"] },
  { id: "v007-19", word: "depict", pos: "v.", ko: ["묘사하다", "그리다"], freq: 1,
    roots: ["de", "pict"], hint: "de(완전히) + pict(그리다) → 낱낱이 그려 내다",
    ex: { en: "The mural depicts a harvest scene.", ko: "그 벽화는 추수 장면을 묘사한다." },
    syn: ["portray", "illustrate"] },
  { id: "v007-20", word: "discharge", pos: "v./n.", ko: ["방출하다", "퇴원시키다", "방출"], freq: 2,
    roots: ["dis", "charg"], hint: "dis(따로) + charg(짐, 싣다) → 실었던 짐을 내려놓다",
    ex: { en: "The patient was discharged on Friday.", ko: "그 환자는 금요일에 퇴원했다." },
    syn: ["release", "emit"] },
  { id: "v007-21", word: "disclose", pos: "v.", ko: ["공개하다", "밝히다"], freq: 1,
    roots: ["dis", "clud"], hint: "dis(반대로) + clos(=clud, 닫다) → 닫혀 있던 것을 열어 보이다",
    ex: { en: "The firm refused to disclose its donors.", ko: "그 회사는 기부자 공개를 거부했다." },
    syn: ["reveal", "divulge"] },
  { id: "v007-22", word: "dissolve", pos: "v.", ko: ["녹이다", "해산하다"], freq: 1,
    roots: ["dis", "solv"], hint: "dis(따로) + solv(풀다) → 뭉친 것을 풀어 흩어 놓다",
    ex: { en: "The king dissolved parliament.", ko: "왕은 의회를 해산했다." },
    syn: ["melt", "disband"] },
  { id: "v007-23", word: "embrace", pos: "v.", ko: ["받아들이다", "포옹하다"], freq: 1,
    roots: ["in", "brac"], hint: "em(=in, 안으로) + brac(팔) → 팔 안으로 끌어안다",
    ex: { en: "The company embraced the new standard.", ko: "그 회사는 새 표준을 받아들였다." },
    syn: ["adopt", "hug"] },
  { id: "v007-24", word: "encompass", pos: "v.", ko: ["아우르다", "포함하다"], freq: 2,
    roots: ["in", "com", "pass"], hint: "en(=in, 안에) + com(함께) + pass(걸음) → 빙 둘러 걸어 안에 넣다",
    ex: { en: "The survey encompasses all age groups.", ko: "그 조사는 모든 연령대를 아우른다." },
    syn: ["include", "span"] },
  { id: "v007-25", word: "entail", pos: "v.", ko: ["수반하다", "필요로 하다"], freq: 2,
    roots: ["in", "tail"], hint: "en(=in, 안으로) + tail(자르다) → 잘라 딸려 붙게 하다",
    ex: { en: "The job entails frequent travel.", ko: "그 일은 잦은 출장을 수반한다." },
    syn: ["involve", "require"] },
  { id: "v007-26", word: "eradicate", pos: "v.", ko: ["근절하다", "뿌리 뽑다"], freq: 2,
    roots: ["ex", "radic"], hint: "e(=ex, 밖으로) + radic(뿌리) → 뿌리째 뽑아내다",
    ex: { en: "The country eradicated the disease by 1980.", ko: "그 나라는 1980년까지 그 병을 근절했다." },
    syn: ["wipe out", "extirpate"] },
  { id: "v007-27", word: "escalate", pos: "v.", ko: ["악화되다", "확대되다"], freq: 1,
    roots: ["ex", "scal"], hint: "e(=ex, 위로) + scal(사다리) → 사다리를 타고 한 칸씩 올라가다",
    ex: { en: "The dispute escalated into violence.", ko: "그 분쟁은 폭력으로 번졌다." },
    syn: ["intensify", "mount"] },
  { id: "v007-28", word: "evacuate", pos: "v.", ko: ["대피시키다", "비우다"], freq: 1,
    roots: ["ex", "vac"], hint: "e(=ex, 밖으로) + vac(빈) → 안을 비우고 밖으로 내보내다",
    ex: { en: "Officials evacuated the village before dawn.", ko: "당국은 새벽 전에 마을 주민을 대피시켰다." },
    syn: ["clear", "vacate"] },
  { id: "v007-29", word: "exclaim", pos: "v.", ko: ["외치다", "소리치다"], freq: 2,
    roots: ["ex", "clam"], hint: "ex(밖으로) + clam(외치다) → 소리를 밖으로 내지르다",
    ex: { en: "He exclaimed in surprise at the news.", ko: "그는 그 소식에 놀라 소리쳤다." },
    syn: ["cry out", "shout"] },
  { id: "v007-30", word: "fabricate", pos: "v.", ko: ["날조하다", "제작하다"], freq: 2,
    roots: ["fabric"], hint: "fabric(만들어 내다) → 없던 것을 만들어 내다",
    ex: { en: "The witness fabricated the whole story.", ko: "그 증인은 이야기를 통째로 날조했다." },
    syn: ["invent", "forge"] },
  { id: "v007-31", word: "formulate", pos: "v.", ko: ["수립하다", "공식화하다"], freq: 1,
    roots: ["form"], hint: "form(모양) → 흩어진 생각에 모양을 잡아 주다",
    ex: { en: "The team formulated a new policy.", ko: "팀은 새 정책을 수립했다." },
    syn: ["devise", "frame"] },
  { id: "v007-32", word: "impart", pos: "v.", ko: ["전하다", "나눠 주다"], freq: 2,
    roots: ["in", "part"], hint: "im(=in, 안으로) + part(몫) → 제 몫을 떼어 상대 안에 넣어 주다",
    ex: { en: "Good teachers impart more than facts.", ko: "좋은 교사는 사실 이상을 전한다." },
    syn: ["convey", "transmit"] },
  { id: "v007-33", word: "impede", pos: "v.", ko: ["방해하다", "지연시키다"], freq: 2,
    roots: ["in", "ped"], hint: "im(=in, 안으로) + ped(발) → 발에 족쇄를 채우다",
    ex: { en: "Heavy snow impeded the rescue.", ko: "폭설이 구조를 방해했다." },
    syn: ["obstruct", "hamper"] },
  { id: "v007-34", word: "inflict", pos: "v.", ko: ["가하다", "입히다"], freq: 2,
    roots: ["in", "flict"], hint: "in(위로) + flict(치다) → 상대 위로 내리쳐 안기다",
    ex: { en: "The storm inflicted heavy damage on the port.", ko: "폭풍이 항구에 큰 피해를 입혔다." },
    syn: ["impose", "deal"] },
  { id: "v007-35", word: "instill", pos: "v.", ko: ["주입하다", "심어 주다"], freq: 2,
    roots: ["in", "still"], hint: "in(안으로) + still(방울) → 한 방울씩 안으로 떨어뜨려 스미게 하다",
    ex: { en: "Coaches try to instill discipline early.", ko: "코치들은 규율을 일찍부터 심어 주려 한다." },
    syn: ["implant", "infuse"] },
  { id: "v007-36", word: "invoke", pos: "v.", ko: ["발동하다", "불러내다"], freq: 2,
    roots: ["in", "voc"], hint: "in(안으로) + voc(부르다) → 필요한 것을 불러들이다",
    ex: { en: "The mayor invoked emergency powers.", ko: "시장은 비상 권한을 발동했다." },
    syn: ["cite", "summon"] },
  { id: "v007-37", word: "mitigate", pos: "v.", ko: ["완화하다", "누그러뜨리다"], freq: 1,
    roots: ["miti"], hint: "miti(부드러운) → 날 선 것을 부드럽게 만들다",
    ex: { en: "Trees help mitigate urban heat.", ko: "나무는 도시 열기를 누그러뜨리는 데 도움이 된다." },
    syn: ["ease", "alleviate"] },
  { id: "v007-38", word: "nullify", pos: "v.", ko: ["무효화하다"], freq: 2,
    roots: ["null"], hint: "null(없는, 영) → 없던 일로 만들다",
    ex: { en: "The court nullified the contract.", ko: "법원은 그 계약을 무효화했다." },
    syn: ["annul", "void"] },
  { id: "v007-39", word: "obstruct", pos: "v.", ko: ["가로막다", "방해하다"], freq: 2,
    roots: ["ob", "struct"], hint: "ob(맞은편에) + struct(세우다) → 앞을 가로질러 벽을 세우다",
    ex: { en: "The truck obstructed the entrance.", ko: "그 트럭이 입구를 가로막았다." },
    syn: ["block", "hinder"] },
  { id: "v007-40", word: "penetrate", pos: "v.", ko: ["관통하다", "침투하다"], freq: 2,
    roots: ["penetr"], hint: "penetr(안으로 파고들다) → 뚫고 안까지 들어가다",
    ex: { en: "Light barely penetrates the thick canopy.", ko: "빛이 두꺼운 나뭇잎 지붕을 거의 뚫지 못한다." },
    syn: ["pierce", "permeate"] },
  { id: "v007-41", word: "proclaim", pos: "v.", ko: ["선포하다", "공표하다"], freq: 2,
    roots: ["pro", "clam"], hint: "pro(앞으로) + clam(외치다) → 사람들 앞에 대고 외치다",
    ex: { en: "The council proclaimed a day of mourning.", ko: "의회는 애도의 날을 선포했다." },
    syn: ["declare", "announce"] },
  { id: "v007-42", word: "propel", pos: "v.", ko: ["추진하다", "나아가게 하다"], freq: 2,
    roots: ["pro", "pel"], hint: "pro(앞으로) + pel(밀다) → 앞으로 밀어 보내다",
    ex: { en: "Strong winds propelled the boat forward.", ko: "강풍이 배를 앞으로 밀어냈다." },
    syn: ["drive", "thrust"] },
  { id: "v007-43", word: "ratify", pos: "v.", ko: ["비준하다", "승인하다"], freq: 2,
    roots: ["rat"], hint: "rat(셈하다, 헤아리다) → 셈이 맞다고 도장을 찍다",
    ex: { en: "Parliament ratified the treaty in June.", ko: "의회는 6월에 그 조약을 비준했다." },
    syn: ["approve", "endorse"] },
  { id: "v007-44", word: "recruit", pos: "v./n.", ko: ["모집하다", "신입"], freq: 1,
    roots: ["re", "cresc"], hint: "re(다시) + cruit(=cresc, 자라다) → 빈자리를 다시 채워 키우다",
    ex: { en: "The agency recruits staff every spring.", ko: "그 기관은 매년 봄에 직원을 모집한다." },
    syn: ["enlist", "hire"] },
  { id: "v007-45", word: "relinquish", pos: "v.", ko: ["포기하다", "넘겨주다"], freq: 2,
    roots: ["re", "linqu"], hint: "re(뒤로) + linqu(남기다, 떠나다) → 뒤에 남겨 두고 손을 떼다",
    ex: { en: "He relinquished his claim to the estate.", ko: "그는 그 재산에 대한 권리를 포기했다." },
    syn: ["surrender", "cede"] },
  { id: "v007-46", word: "replicate", pos: "v.", ko: ["재현하다", "복제하다"], freq: 2,
    roots: ["re", "plic"], hint: "re(다시) + plic(접다) → 같은 모양으로 다시 접어 내다",
    ex: { en: "Other labs could not replicate the result.", ko: "다른 연구실들은 그 결과를 재현하지 못했다." },
    syn: ["reproduce", "duplicate"] },
  { id: "v007-47", word: "resume", pos: "v.", ko: ["재개하다", "다시 시작하다"], freq: 1,
    roots: ["re", "sum"], hint: "re(다시) + sum(취하다) → 놓았던 것을 다시 집어 들다",
    ex: { en: "Talks will resume on Monday.", ko: "회담은 월요일에 재개된다." },
    syn: ["restart", "continue"] },
  { id: "v007-48", word: "retrieve", pos: "v.", ko: ["회수하다", "되찾다"], freq: 2,
    roots: ["re", "trov"], hint: "re(다시) + triev(=trov, 찾아내다) → 잃었던 것을 다시 찾아내다",
    ex: { en: "Divers retrieved the black box.", ko: "잠수부들이 블랙박스를 회수했다." },
    syn: ["recover", "reclaim"] },
  { id: "v007-49", word: "suppress", pos: "v.", ko: ["진압하다", "억누르다"], freq: 1,
    roots: ["sub", "press"], hint: "sup(=sub, 아래로) + press(누르다) → 아래로 짓눌러 못 올라오게 하다",
    ex: { en: "The regime suppressed the protest.", ko: "그 정권은 시위를 진압했다." },
    syn: ["quash", "stifle"] },
  { id: "v007-50", word: "undermine", pos: "v.", ko: ["훼손하다", "약화시키다"], freq: 1,
    roots: ["mine"], hint: "under(아래를) + mine(굴을 파다) → 밑을 파내 서 있던 것을 무너뜨리다",
    ex: { en: "The scandal undermined public trust.", ko: "그 추문은 국민의 신뢰를 훼손했다." },
    syn: ["weaken", "erode"] },
];
