// DAY 3 — ex·in 계열 빈출 어휘. 파일 성격은 day-001.js 헤더 참고(동적 import 전용).
export const WORDS = [
  { id: "v003-01", word: "entitle", pos: "v.", ko: ["자격을 주다", "제목을 붙이다"], freq: 2,
    roots: ["in"], hint: "en(=in, ~하게 만들다) + title(칭호) → 그 칭호를 가질 자격을 주다",
    ex: { en: "This card entitles you to a discount.", ko: "이 카드가 있으면 할인을 받을 자격이 생긴다." },
    syn: ["qualify", "authorize"] },
  { id: "v003-02", word: "evaluate", pos: "v.", ko: ["평가하다", "가치를 매기다"], freq: 1,
    roots: ["ex", "valu"], hint: "e(=ex, 밖으로) + valu(가치) → 가치를 밖으로 끄집어내 재다",
    ex: { en: "We must evaluate the risks first.", ko: "우리는 먼저 위험을 평가해야 한다." },
    syn: ["assess", "appraise"] },
  { id: "v003-03", word: "evoke", pos: "v.", ko: ["불러일으키다", "환기시키다"], freq: 2,
    roots: ["ex", "voc"], hint: "e(=ex, 밖으로) + voc(부르다) → 기억이나 감정을 불러내다",
    ex: { en: "The song evokes memories of childhood.", ko: "그 노래는 어린 시절의 기억을 불러일으킨다." },
    syn: ["arouse", "bring up"] },
  { id: "v003-04", word: "exaggerate", pos: "v.", ko: ["과장하다"], freq: 2,
    roots: ["ex", "agger"], hint: "ex(밖으로) + agger(쌓다) → 실제보다 더 쌓아 부풀리다",
    ex: { en: "He tends to exaggerate his achievements.", ko: "그는 자기 업적을 과장하는 경향이 있다." },
    syn: ["overstate", "inflate"] },
  { id: "v003-05", word: "exceed", pos: "v.", ko: ["초과하다", "능가하다"], freq: 1,
    roots: ["ex", "ced"], hint: "ex(밖으로) + ced(가다) → 정해진 선 밖으로 나가다",
    ex: { en: "Costs must not exceed the budget.", ko: "비용이 예산을 초과해서는 안 된다." },
    syn: ["surpass", "go beyond"] },
  { id: "v003-06", word: "exclude", pos: "v.", ko: ["배제하다", "제외하다"], freq: 1,
    roots: ["ex", "clud"], hint: "ex(밖으로) + clud(닫다) → 밖에 두고 문을 닫다",
    ex: { en: "The price excludes tax and service charges.", ko: "그 가격은 세금과 봉사료를 제외한 것이다." },
    syn: ["leave out", "bar"] },
  { id: "v003-07", word: "execute", pos: "v.", ko: ["실행하다", "처형하다"], freq: 1,
    roots: ["ex", "secut"], hint: "ex(밖으로 끝까지) + secut(따르다) → 계획을 끝까지 따라 해내다",
    ex: { en: "The team executed the plan without delay.", ko: "그 팀은 지체 없이 계획을 실행했다." },
    syn: ["carry out", "perform"] },
  { id: "v003-08", word: "exempt", pos: "adj./v.", ko: ["면제된", "면제하다"], freq: 2,
    roots: ["ex", "empt"], hint: "ex(밖으로) + empt(취하다) → 의무 대상에서 빼내 가지다",
    ex: { en: "Small firms are exempt from the new tax.", ko: "소규모 기업은 새 세금이 면제된다." },
    syn: ["excused", "free from"] },
  { id: "v003-09", word: "exert", pos: "v.", ko: ["발휘하다", "행사하다"], freq: 2,
    roots: ["ex", "sert"], hint: "ex(밖으로) + sert(엮다·잇다) → 안에 있던 힘을 밖으로 뽑아내다",
    ex: { en: "The union exerted pressure on the company.", ko: "노조는 회사에 압력을 행사했다." },
    syn: ["apply", "wield"] },
  { id: "v003-10", word: "exhaust", pos: "v./n.", ko: ["고갈시키다", "지치게 하다", "배기가스"], freq: 1,
    roots: ["ex", "haust"], hint: "ex(밖으로) + haust(퍼내다) → 바닥까지 퍼내 비우다",
    ex: { en: "The country has exhausted its oil reserves.", ko: "그 나라는 석유 매장량을 고갈시켰다." },
    syn: ["use up", "tire out"] },
  { id: "v003-11", word: "expand", pos: "v.", ko: ["확장하다", "팽창하다"], freq: 1,
    roots: ["ex", "pand"], hint: "ex(밖으로) + pand(펼치다) → 밖으로 넓게 펼치다",
    ex: { en: "The company plans to expand overseas.", ko: "그 회사는 해외로 확장할 계획이다." },
    syn: ["enlarge", "extend"] },
  { id: "v003-12", word: "expel", pos: "v.", ko: ["쫓아내다", "추방하다"], freq: 2,
    roots: ["ex", "pel"], hint: "ex(밖으로) + pel(밀다) → 밖으로 밀어내다",
    ex: { en: "The student was expelled for cheating.", ko: "그 학생은 부정행위로 퇴학당했다." },
    syn: ["banish", "throw out"] },
  { id: "v003-13", word: "explicit", pos: "adj.", ko: ["명시적인", "노골적인"], freq: 1,
    roots: ["ex", "plic"], hint: "ex(밖으로) + plic(접다) → 접힌 걸 펴서 다 보이게 한",
    ex: { en: "The contract gives explicit instructions.", ko: "그 계약서는 명시적인 지시를 담고 있다." },
    syn: ["clear", "definite"] },
  { id: "v003-14", word: "exploit", pos: "v./n.", ko: ["착취하다", "활용하다", "위업"], freq: 1,
    roots: ["ex", "plic"], hint: "ex(밖으로) + ploit(=plic, 접다) → 접힌 것을 펴서 끝까지 써먹다",
    ex: { en: "Some firms exploit cheap foreign labor.", ko: "일부 기업은 값싼 외국인 노동력을 착취한다." },
    syn: ["take advantage of", "utilize"] },
  { id: "v003-15", word: "expose", pos: "v.", ko: ["노출시키다", "폭로하다"], freq: 1,
    roots: ["ex", "pos"], hint: "ex(밖으로) + pos(놓다) → 밖에 내놓아 드러내다",
    ex: { en: "The report exposed serious corruption.", ko: "그 보도는 심각한 부패를 폭로했다." },
    syn: ["reveal", "uncover"] },
  { id: "v003-16", word: "extract", pos: "v./n.", ko: ["추출하다", "발췌"], freq: 2,
    roots: ["ex", "tract"], hint: "ex(밖으로) + tract(끌다) → 밖으로 끌어내다",
    ex: { en: "They extract oil from the seeds.", ko: "그들은 씨앗에서 기름을 추출한다." },
    syn: ["draw out", "excerpt"] },
  { id: "v003-17", word: "facilitate", pos: "v.", ko: ["촉진하다", "쉽게 하다"], freq: 1,
    roots: ["facil"], hint: "facil(쉬운) → 일이 쉬워지도록 길을 터 주다",
    ex: { en: "The app facilitates communication between teams.", ko: "그 앱은 팀 간 소통을 원활하게 해 준다." },
    syn: ["ease", "promote"] },
  { id: "v003-18", word: "fluctuate", pos: "v.", ko: ["변동하다", "오르내리다"], freq: 2,
    roots: ["fluct"], hint: "fluct(흐르다·물결) → 물결처럼 오르락내리락하다",
    ex: { en: "Prices fluctuate with the season.", ko: "가격은 계절에 따라 변동한다." },
    syn: ["vary", "swing"] },
  { id: "v003-19", word: "foster", pos: "v.", ko: ["육성하다", "위탁 양육하다"], freq: 2,
    roots: ["fost"], hint: "fost(먹여 기르다) → 먹여 키우듯 자라게 돕다",
    ex: { en: "Schools should foster creative thinking.", ko: "학교는 창의적 사고를 길러야 한다." },
    syn: ["nurture", "encourage"] },
  { id: "v003-20", word: "generate", pos: "v.", ko: ["발생시키다", "창출하다"], freq: 1,
    roots: ["gen"], hint: "gen(낳다) → 없던 것을 낳아 만들어 내다",
    ex: { en: "The plant generates electricity from wind.", ko: "그 발전소는 바람으로 전기를 생산한다." },
    syn: ["produce", "create"] },
  { id: "v003-21", word: "hinder", pos: "v.", ko: ["방해하다", "저해하다"], freq: 2,
    roots: ["hind"], hint: "hind(뒤) → 뒤에서 붙잡아 앞으로 못 가게 하다",
    ex: { en: "Heavy snow hindered the rescue work.", ko: "폭설이 구조 작업을 방해했다." },
    syn: ["impede", "obstruct"] },
  { id: "v003-22", word: "identify", pos: "v.", ko: ["확인하다", "식별하다"], freq: 1,
    roots: ["ident"], hint: "ident(같은) → 같은 것인지 맞춰 보아 알아내다",
    ex: { en: "Police identified the suspect from the video.", ko: "경찰은 영상으로 용의자를 확인했다." },
    syn: ["recognize", "pinpoint"] },
  { id: "v003-23", word: "illustrate", pos: "v.", ko: ["설명하다", "예시하다"], freq: 2,
    roots: ["in", "lustr"], hint: "il(=in, 안으로) + lustr(빛) → 빛을 비춰 환히 보여 주다",
    ex: { en: "This case illustrates the problem well.", ko: "이 사례가 그 문제를 잘 보여 준다." },
    syn: ["demonstrate", "exemplify"] },
  { id: "v003-24", word: "impair", pos: "v.", ko: ["손상시키다", "약화시키다"], freq: 2,
    roots: ["in", "pejor"], hint: "im(=in, ~하게 만들다) + pair(=pejor, 더 나쁜) → 더 나쁜 상태로 만들다",
    ex: { en: "Lack of sleep impairs judgment.", ko: "수면 부족은 판단력을 손상시킨다." },
    syn: ["damage", "weaken"] },
  { id: "v003-25", word: "implement", pos: "v./n.", ko: ["시행하다", "도구"], freq: 1,
    roots: ["in", "ple"], hint: "im(=in, 안을) + ple(채우다) → 계획을 실제로 채워 넣다",
    ex: { en: "The city will implement the policy next year.", ko: "시는 내년에 그 정책을 시행할 것이다." },
    syn: ["carry out", "execute"] },
  { id: "v003-26", word: "imply", pos: "v.", ko: ["암시하다", "함축하다"], freq: 1,
    roots: ["in", "plic"], hint: "im(=in, 안으로) + ply(=plic, 접다) → 뜻을 안쪽에 접어 넣어 두다",
    ex: { en: "His silence implied disagreement.", ko: "그의 침묵은 반대를 암시했다." },
    syn: ["suggest", "hint at"] },
  { id: "v003-27", word: "impose", pos: "v.", ko: ["부과하다", "강요하다"], freq: 1,
    roots: ["in", "pos"], hint: "im(=in, 위에) + pos(놓다) → 상대 위에 얹어 놓다",
    ex: { en: "The state imposed a tax on sugary drinks.", ko: "주 정부는 설탕 음료에 세금을 부과했다." },
    syn: ["levy", "force on"] },
  { id: "v003-28", word: "incline", pos: "v./n.", ko: ["마음이 기울다", "경사"], freq: 2,
    roots: ["in", "clin"], hint: "in(~쪽으로) + clin(기울다) → 마음이 한쪽으로 기울다",
    ex: { en: "I am inclined to accept their offer.", ko: "나는 그들의 제안을 받아들이는 쪽으로 기운다." },
    syn: ["tend", "slope"] },
  { id: "v003-29", word: "incorporate", pos: "v.", ko: ["통합하다", "포함하다"], freq: 1,
    roots: ["in", "corpor"], hint: "in(안으로) + corpor(몸) → 한 몸 안으로 받아들이다",
    ex: { en: "The design incorporates local materials.", ko: "그 설계는 지역 자재를 포함하고 있다." },
    syn: ["include", "merge"] },
  { id: "v003-30", word: "indicate", pos: "v.", ko: ["나타내다", "가리키다"], freq: 1,
    roots: ["in", "dic"], hint: "in(~쪽으로) + dic(말하다·가리키다) → 이쪽이라고 짚어 말하다",
    ex: { en: "The survey indicates a shift in opinion.", ko: "그 조사는 여론의 변화를 나타낸다." },
    syn: ["show", "signal"] },
  { id: "v003-31", word: "induce", pos: "v.", ko: ["유도하다", "유발하다"], freq: 2,
    roots: ["in", "duc"], hint: "in(안으로) + duc(이끌다) → 마음을 안쪽으로 이끌어 들이다",
    ex: { en: "The drug may induce drowsiness.", ko: "그 약은 졸음을 유발할 수 있다." },
    syn: ["persuade", "bring about"] },
  { id: "v003-32", word: "inevitable", pos: "adj.", ko: ["불가피한", "필연적인"], freq: 1,
    roots: ["in-neg", "evit"], hint: "in(아닌) + evit(피하다) → 피할 수 없는",
    ex: { en: "Change is inevitable in any organization.", ko: "어느 조직에서든 변화는 불가피하다." },
    syn: ["unavoidable", "certain"] },
  { id: "v003-33", word: "infer", pos: "v.", ko: ["추론하다", "암시하다"], freq: 1,
    roots: ["in", "fer"], hint: "in(안으로) + fer(나르다) → 단서를 머릿속으로 날라 결론을 내다",
    ex: { en: "We can infer his motive from the letter.", ko: "그 편지에서 그의 동기를 추론할 수 있다." },
    syn: ["deduce", "conclude"] },
  { id: "v003-34", word: "inhabit", pos: "v.", ko: ["거주하다", "서식하다"], freq: 2,
    roots: ["in", "habit"], hint: "in(안에) + habit(살다·지니다) → 그 안에 자리 잡고 살다",
    ex: { en: "Few animals inhabit the desert.", ko: "그 사막에는 사는 동물이 거의 없다." },
    syn: ["live in", "occupy"] },
  { id: "v003-35", word: "inherent", pos: "adj.", ko: ["내재된", "타고난"], freq: 1,
    roots: ["in", "her"], hint: "in(안에) + her(붙다) → 안에 딱 붙어 떨어지지 않는",
    ex: { en: "Risk is inherent in any investment.", ko: "어떤 투자에도 위험은 내재해 있다." },
    syn: ["intrinsic", "innate"] },
  { id: "v003-36", word: "inhibit", pos: "v.", ko: ["억제하다", "저해하다"], freq: 2,
    roots: ["in", "hibit"], hint: "in(안에) + hibit(붙잡다) → 안에서 붙잡아 못 나오게 하다",
    ex: { en: "Cold weather inhibits plant growth.", ko: "추운 날씨는 식물의 성장을 억제한다." },
    syn: ["restrain", "hinder"] },
  { id: "v003-37", word: "initiate", pos: "v.", ko: ["착수하다", "시작하다"], freq: 1,
    roots: ["init"], hint: "init(들어가다) → 첫발을 들여 일을 열다",
    ex: { en: "The ministry initiated a pilot program.", ko: "그 부처는 시범 사업에 착수했다." },
    syn: ["begin", "launch"] },
  { id: "v003-38", word: "innovate", pos: "v.", ko: ["혁신하다"], freq: 2,
    roots: ["in", "nov"], hint: "in(안으로) + nov(새로운) → 새것을 안으로 들여 바꾸다",
    ex: { en: "Firms must innovate or fall behind.", ko: "기업은 혁신하지 않으면 뒤처진다." },
    syn: ["modernize", "reform"] },
  { id: "v003-39", word: "inquire", pos: "v.", ko: ["문의하다", "조사하다"], freq: 2,
    roots: ["in", "quir"], hint: "in(안으로) + quir(구하다) → 안쪽 사정을 캐어 묻다",
    ex: { en: "She inquired about the vacancy.", ko: "그녀는 공석에 대해 문의했다." },
    syn: ["ask", "investigate"] },
  { id: "v003-40", word: "insist", pos: "v.", ko: ["주장하다", "고집하다"], freq: 1,
    roots: ["in", "sist"], hint: "in(위에) + sist(서다) → 그 자리에 딱 버티고 서다",
    ex: { en: "He insisted on paying the bill.", ko: "그는 계산을 하겠다고 고집했다." },
    syn: ["demand", "maintain"] },
  { id: "v003-41", word: "inspect", pos: "v.", ko: ["점검하다", "검사하다"], freq: 2,
    roots: ["in", "spect"], hint: "in(안을) + spect(보다) → 속까지 들여다보다",
    ex: { en: "Officials inspect the facility every year.", ko: "당국은 매년 그 시설을 점검한다." },
    syn: ["examine", "check"] },
  { id: "v003-42", word: "integrate", pos: "v.", ko: ["통합하다", "융합하다"], freq: 1,
    roots: ["integr"], hint: "integr(온전한) → 조각들을 합쳐 온전한 하나로 만들다",
    ex: { en: "The school integrates art into every subject.", ko: "그 학교는 모든 과목에 예술을 통합한다." },
    syn: ["combine", "unify"] },
  { id: "v003-43", word: "interpret", pos: "v.", ko: ["해석하다", "통역하다"], freq: 1,
    roots: ["inter", "pret"], hint: "inter(사이에서) + pret(중개하다) → 둘 사이에 서서 뜻을 옮기다",
    ex: { en: "Judges interpret the law, not write it.", ko: "판사는 법을 만드는 것이 아니라 해석한다." },
    syn: ["explain", "translate"] },
  { id: "v003-44", word: "intervene", pos: "v.", ko: ["개입하다", "중재하다"], freq: 1,
    roots: ["inter", "ven"], hint: "inter(사이에) + ven(오다) → 둘 사이로 끼어들어 오다",
    ex: { en: "The government intervened to stop the strike.", ko: "정부가 파업을 멈추려고 개입했다." },
    syn: ["step in", "mediate"] },
  { id: "v003-45", word: "intimidate", pos: "v.", ko: ["위협하다", "겁주다"], freq: 2,
    roots: ["in", "timid"], hint: "in(~하게 만들다) + timid(겁먹은) → 상대를 겁먹게 만들다",
    ex: { en: "They tried to intimidate the witness.", ko: "그들은 증인을 위협하려 했다." },
    syn: ["threaten", "frighten"] },
  { id: "v003-46", word: "invade", pos: "v.", ko: ["침입하다", "침해하다"], freq: 2,
    roots: ["in", "vad"], hint: "in(안으로) + vad(가다) → 남의 영역 안으로 들어가다",
    ex: { en: "The press invaded her private life.", ko: "언론이 그녀의 사생활을 침해했다." },
    syn: ["intrude", "attack"] },
  { id: "v003-47", word: "investigate", pos: "v.", ko: ["조사하다", "수사하다"], freq: 1,
    roots: ["in", "vestig"], hint: "in(안으로) + vestig(발자국) → 발자국을 따라 안까지 뒤쫓다",
    ex: { en: "Police are investigating the accident.", ko: "경찰이 그 사고를 조사하고 있다." },
    syn: ["look into", "probe"] },
  { id: "v003-48", word: "justify", pos: "v.", ko: ["정당화하다", "옳음을 보이다"], freq: 1,
    roots: ["just"], hint: "just(올바른) + fy(만들다) → 올바른 것으로 만들어 보이다",
    ex: { en: "Nothing can justify such violence.", ko: "어떤 것도 그런 폭력을 정당화할 수 없다." },
    syn: ["defend", "warrant"] },
  { id: "v003-49", word: "legitimate", pos: "adj.", ko: ["합법적인", "정당한"], freq: 1,
    roots: ["leg"], hint: "leg(법) → 법에 맞는",
    ex: { en: "They raised a legitimate concern.", ko: "그들은 정당한 우려를 제기했다." },
    syn: ["lawful", "valid"] },
  { id: "v003-50", word: "maintain", pos: "v.", ko: ["유지하다", "주장하다", "정비하다"], freq: 1,
    roots: ["man", "tain"], hint: "main(=man, 손) + tain(잡다) → 손에 계속 쥐고 있다",
    ex: { en: "It is hard to maintain such a pace.", ko: "그런 속도를 유지하기는 어렵다." },
    syn: ["keep up", "assert"] },
];
