// DAY 4 — per·pre·pro·re 계열 빈출 어휘. 파일 성격은 day-001.js 헤더 참고(동적 import 전용).
export const WORDS = [
  { id: "v004-01", word: "manipulate", pos: "v.", ko: ["조작하다", "다루다"], freq: 2,
    roots: ["man", "ple"], hint: "mani(=man, 손) + pul(=ple, 채우다) → 손에 쥐고 마음대로 주무르다",
    ex: { en: "He manipulated the data to fit his theory.", ko: "그는 자기 이론에 맞게 자료를 조작했다." },
    syn: ["control", "rig"] },
  { id: "v004-02", word: "mediate", pos: "v.", ko: ["중재하다", "조정하다"], freq: 2,
    roots: ["medi"], hint: "medi(가운데) → 가운데 서서 양쪽을 맞춰 주다",
    ex: { en: "A third country mediated the talks.", ko: "제3국이 그 회담을 중재했다." },
    syn: ["arbitrate", "reconcile"] },
  { id: "v004-03", word: "modify", pos: "v.", ko: ["수정하다", "변경하다"], freq: 1,
    roots: ["mod"], hint: "mod(알맞은 정도) + fy(만들다) → 알맞게 손보다",
    ex: { en: "We modified the plan after the feedback.", ko: "우리는 피드백을 받고 계획을 수정했다." },
    syn: ["alter", "adjust"] },
  { id: "v004-04", word: "monitor", pos: "v./n.", ko: ["감시하다", "관찰하다", "화면"], freq: 1,
    roots: ["mon"], hint: "mon(경고하다) → 지켜보다가 이상하면 알려 주다",
    ex: { en: "Nurses monitor the patient overnight.", ko: "간호사들이 밤새 환자를 관찰한다." },
    syn: ["watch", "track"] },
  { id: "v004-05", word: "negotiate", pos: "v.", ko: ["협상하다", "타결하다"], freq: 1,
    roots: ["neg", "oti"], hint: "neg(아닌) + oti(여가) → 쉬지 않고 붙어 앉아 흥정하다",
    ex: { en: "The union negotiated a pay raise.", ko: "노조는 임금 인상을 협상해 냈다." },
    syn: ["bargain", "settle"] },
  { id: "v004-06", word: "neglect", pos: "v./n.", ko: ["방치하다", "소홀히 하다", "태만"], freq: 1,
    roots: ["neg", "lect"], hint: "neg(아닌) + lect(고르다) → 고르지 않고 내버려 두다",
    ex: { en: "He neglected his duties for months.", ko: "그는 몇 달간 직무를 소홀히 했다." },
    syn: ["ignore", "disregard"] },
  { id: "v004-07", word: "obscure", pos: "adj./v.", ko: ["모호한", "잘 알려지지 않은", "가리다"], freq: 2,
    roots: ["ob", "scur"], hint: "ob(위에) + scur(덮다) → 위를 덮어 흐릿하게 만든",
    ex: { en: "The meaning of the poem remains obscure.", ko: "그 시의 의미는 여전히 모호하다." },
    syn: ["unclear", "vague"] },
  { id: "v004-08", word: "obtain", pos: "v.", ko: ["얻다", "획득하다"], freq: 1,
    roots: ["ob", "tain"], hint: "ob(~쪽으로) + tain(잡다) → 손을 뻗어 붙잡아 가지다",
    ex: { en: "You must obtain permission in advance.", ko: "사전에 허가를 받아야 한다." },
    syn: ["acquire", "get"] },
  { id: "v004-09", word: "occupy", pos: "v.", ko: ["차지하다", "점령하다"], freq: 1,
    roots: ["ob", "cup"], hint: "oc(=ob, ~쪽으로) + cup(잡다) → 자리를 붙잡아 차지하다",
    ex: { en: "Protesters occupied the main square.", ko: "시위대가 중앙 광장을 점거했다." },
    syn: ["take up", "seize"] },
  { id: "v004-10", word: "oppose", pos: "v.", ko: ["반대하다", "맞서다"], freq: 1,
    roots: ["ob", "pos"], hint: "op(=ob, 맞은편에) + pos(놓다) → 상대 앞에 맞세워 놓다",
    ex: { en: "Residents oppose the new landfill.", ko: "주민들은 새 매립지에 반대한다." },
    syn: ["resist", "object to"] },
  { id: "v004-11", word: "oppress", pos: "v.", ko: ["억압하다", "탄압하다"], freq: 2,
    roots: ["ob", "press"], hint: "op(=ob, 위에서) + press(누르다) → 위에서 짓눌러 놓다",
    ex: { en: "The regime oppressed religious minorities.", ko: "그 정권은 종교적 소수자를 탄압했다." },
    syn: ["subjugate", "persecute"] },
  { id: "v004-12", word: "overwhelm", pos: "v.", ko: ["압도하다", "휩싸다"], freq: 1,
    roots: ["over"], hint: "over(위로) + whelm(뒤엎다) → 위에서 통째로 뒤덮어 버리다",
    ex: { en: "The scale of the disaster overwhelmed rescuers.", ko: "재난의 규모가 구조대를 압도했다." },
    syn: ["overpower", "swamp"] },
  { id: "v004-13", word: "perceive", pos: "v.", ko: ["인지하다", "여기다"], freq: 1,
    roots: ["per", "ceiv"], hint: "per(완전히) + ceiv(잡다) → 감각으로 온전히 붙잡다",
    ex: { en: "Voters perceive him as honest.", ko: "유권자들은 그를 정직하다고 여긴다." },
    syn: ["notice", "regard"] },
  { id: "v004-14", word: "permit", pos: "v./n.", ko: ["허가하다", "허가증"], freq: 1,
    roots: ["per", "mit"], hint: "per(통과해) + mit(보내다) → 통과시켜 보내 주다",
    ex: { en: "The rules do not permit late entry.", ko: "규정상 지각 입장은 허용되지 않는다." },
    syn: ["allow", "license"] },
  { id: "v004-15", word: "persist", pos: "v.", ko: ["지속하다", "고집하다"], freq: 1,
    roots: ["per", "sist"], hint: "per(끝까지) + sist(서다) → 끝까지 버티고 서 있다",
    ex: { en: "The problem persists despite the repairs.", ko: "수리를 했는데도 문제가 계속된다." },
    syn: ["continue", "persevere"] },
  { id: "v004-16", word: "persuade", pos: "v.", ko: ["설득하다"], freq: 1,
    roots: ["per", "suad"], hint: "per(완전히) + suad(권하다) → 끝까지 권해 마음을 돌리다",
    ex: { en: "She persuaded him to apply again.", ko: "그녀는 그를 설득해 다시 지원하게 했다." },
    syn: ["convince", "coax"] },
  { id: "v004-17", word: "pertain", pos: "v.", ko: ["관련되다", "속하다"], freq: 3,
    roots: ["per", "tain"], hint: "per(완전히) + tain(잡다) → 그쪽에 딱 붙어 매여 있다",
    ex: { en: "These rules pertain only to full-time staff.", ko: "이 규정은 정규직에게만 해당된다." },
    syn: ["relate to", "belong to"] },
  { id: "v004-18", word: "possess", pos: "v.", ko: ["소유하다", "지니다"], freq: 1,
    roots: ["pot", "sed"], hint: "pos(=pot, 힘) + sess(=sed, 앉다) → 힘을 갖고 그 위에 앉아 있다",
    ex: { en: "He possesses rare technical skills.", ko: "그는 보기 드문 기술을 지니고 있다." },
    syn: ["own", "hold"] },
  { id: "v004-19", word: "postpone", pos: "v.", ko: ["연기하다", "미루다"], freq: 1,
    roots: ["post", "pos"], hint: "post(뒤에) + pon(=pos, 놓다) → 뒤쪽에 놓아 두다",
    ex: { en: "The match was postponed because of rain.", ko: "비 때문에 경기가 연기되었다." },
    syn: ["delay", "put off"] },
  { id: "v004-20", word: "precede", pos: "v.", ko: ["선행하다", "앞서다"], freq: 2,
    roots: ["pre", "ced"], hint: "pre(먼저) + ced(가다) → 남보다 먼저 가다",
    ex: { en: "A short speech preceded the ceremony.", ko: "짧은 연설이 식에 앞서 있었다." },
    syn: ["come before", "lead"] },
  { id: "v004-21", word: "predict", pos: "v.", ko: ["예측하다", "예언하다"], freq: 1,
    roots: ["pre", "dic"], hint: "pre(미리) + dic(말하다) → 일어나기 전에 미리 말하다",
    ex: { en: "No one could predict the outcome.", ko: "아무도 결과를 예측할 수 없었다." },
    syn: ["forecast", "foresee"] },
  { id: "v004-22", word: "prescribe", pos: "v.", ko: ["처방하다", "규정하다"], freq: 2,
    roots: ["pre", "scrib"], hint: "pre(미리) + scrib(쓰다) → 미리 적어 정해 주다",
    ex: { en: "The doctor prescribed a mild painkiller.", ko: "의사는 순한 진통제를 처방했다." },
    syn: ["order", "stipulate"] },
  { id: "v004-23", word: "preserve", pos: "v.", ko: ["보존하다", "지키다"], freq: 1,
    roots: ["pre", "serv"], hint: "pre(미리) + serv(지키다) → 상하기 전에 미리 지켜 두다",
    ex: { en: "The city preserves its old buildings.", ko: "그 도시는 오래된 건물들을 보존한다." },
    syn: ["conserve", "protect"] },
  { id: "v004-24", word: "presume", pos: "v.", ko: ["추정하다", "주제넘게 굴다"], freq: 2,
    roots: ["pre", "sum"], hint: "pre(미리) + sum(취하다) → 확인 전에 미리 그렇다고 취하다",
    ex: { en: "The law presumes innocence until proven guilty.", ko: "법은 유죄가 입증될 때까지 무죄로 추정한다." },
    syn: ["assume", "suppose"] },
  { id: "v004-25", word: "prevail", pos: "v.", ko: ["우세하다", "만연하다"], freq: 2,
    roots: ["pre", "vail"], hint: "pre(앞서) + vail(힘) → 힘에서 앞서 이기다",
    ex: { en: "Common sense finally prevailed.", ko: "결국 상식이 이겼다." },
    syn: ["triumph", "predominate"] },
  { id: "v004-26", word: "prohibit", pos: "v.", ko: ["금지하다"], freq: 1,
    roots: ["pro", "hibit"], hint: "pro(앞에서) + hibit(붙잡다) → 앞을 가로막아 못 하게 하다",
    ex: { en: "The law prohibits smoking in parks.", ko: "법은 공원에서의 흡연을 금지한다." },
    syn: ["ban", "forbid"] },
  { id: "v004-27", word: "prominent", pos: "adj.", ko: ["저명한", "두드러진"], freq: 1,
    roots: ["pro", "min-jut"], hint: "pro(앞으로) + min(튀어나오다) → 앞으로 튀어나와 눈에 띄는",
    ex: { en: "She is a prominent scholar in the field.", ko: "그녀는 그 분야의 저명한 학자다." },
    syn: ["notable", "outstanding"] },
  { id: "v004-28", word: "prompt", pos: "adj./v.", ko: ["신속한", "촉발하다"], freq: 1,
    roots: ["pro", "empt"], hint: "pro(앞으로) + empt(취하다) → 앞서 집어 드는 → 재빠른",
    ex: { en: "Thank you for your prompt reply.", ko: "신속한 답변 감사합니다." },
    syn: ["quick", "trigger"] },
  { id: "v004-29", word: "propose", pos: "v.", ko: ["제안하다", "청혼하다"], freq: 1,
    roots: ["pro", "pos"], hint: "pro(앞에) + pos(놓다) → 상대 앞에 내놓다",
    ex: { en: "The mayor proposed a new bus route.", ko: "시장은 새 버스 노선을 제안했다." },
    syn: ["suggest", "put forward"] },
  { id: "v004-30", word: "prosecute", pos: "v.", ko: ["기소하다", "수행하다"], freq: 2,
    roots: ["pro", "secut"], hint: "pro(앞으로) + secut(따르다) → 끝까지 쫓아가 법정에 세우다",
    ex: { en: "Offenders will be prosecuted to the full extent of the law.", ko: "위반자는 법에 따라 끝까지 기소된다." },
    syn: ["charge", "sue"] },
  { id: "v004-31", word: "provoke", pos: "v.", ko: ["자극하다", "유발하다"], freq: 1,
    roots: ["pro", "voc"], hint: "pro(앞으로) + voc(부르다) → 반응을 앞으로 불러내다",
    ex: { en: "The remark provoked an angry response.", ko: "그 발언은 성난 반응을 불러일으켰다." },
    syn: ["incite", "trigger"] },
  { id: "v004-32", word: "pursue", pos: "v.", ko: ["추구하다", "뒤쫓다"], freq: 1,
    roots: ["pro", "secut"], hint: "pur(=pro, 앞으로) + sue(=secut, 따르다) → 앞을 향해 계속 따라가다",
    ex: { en: "She decided to pursue a career in law.", ko: "그녀는 법조계 진로를 추구하기로 했다." },
    syn: ["chase", "seek"] },
  { id: "v004-33", word: "recall", pos: "v./n.", ko: ["상기하다", "회수하다", "리콜"], freq: 1,
    roots: ["re"], hint: "re(다시) + call(부르다) → 기억을 다시 불러내다 · 제품을 도로 부르다",
    ex: { en: "I cannot recall his exact words.", ko: "그의 정확한 말이 기억나지 않는다." },
    syn: ["remember", "withdraw"] },
  { id: "v004-34", word: "reconcile", pos: "v.", ko: ["화해시키다", "조화시키다"], freq: 2,
    roots: ["re", "concil"], hint: "re(다시) + concil(모으다) → 갈라선 것을 다시 한자리에 모으다",
    ex: { en: "It is hard to reconcile the two accounts.", ko: "두 진술을 조화시키기는 어렵다." },
    syn: ["settle", "harmonize"] },
  { id: "v004-35", word: "refute", pos: "v.", ko: ["반박하다", "논파하다"], freq: 2,
    roots: ["re", "fut"], hint: "re(되받아) + fut(치다) → 상대 주장을 되받아 쳐 내다",
    ex: { en: "The data refutes his main claim.", ko: "그 자료는 그의 핵심 주장을 반박한다." },
    syn: ["disprove", "rebut"] },
  { id: "v004-36", word: "regulate", pos: "v.", ko: ["규제하다", "조절하다"], freq: 1,
    roots: ["reg"], hint: "reg(규칙·곧게 하다) → 규칙에 맞게 곧게 잡다",
    ex: { en: "The agency regulates food safety.", ko: "그 기관은 식품 안전을 규제한다." },
    syn: ["control", "govern"] },
  { id: "v004-37", word: "reinforce", pos: "v.", ko: ["강화하다", "보강하다"], freq: 1,
    roots: ["re", "in"], hint: "re(다시) + in(~하게) + force(힘) → 힘을 다시 실어 더 단단하게 하다",
    ex: { en: "The results reinforce our earlier findings.", ko: "그 결과는 우리의 이전 발견을 뒷받침한다." },
    syn: ["strengthen", "bolster"] },
  { id: "v004-38", word: "reject", pos: "v.", ko: ["거부하다", "기각하다"], freq: 1,
    roots: ["re", "ject"], hint: "re(뒤로) + ject(던지다) → 받지 않고 도로 던져 버리다",
    ex: { en: "The court rejected the appeal.", ko: "법원은 그 항소를 기각했다." },
    syn: ["refuse", "turn down"] },
  { id: "v004-39", word: "relieve", pos: "v.", ko: ["완화하다", "덜어주다", "교대하다"], freq: 1,
    roots: ["re", "lev"], hint: "re(다시) + lev(가벼운) → 무거운 것을 다시 가볍게 해 주다",
    ex: { en: "The new road relieved traffic congestion.", ko: "새 도로가 교통 혼잡을 완화했다." },
    syn: ["ease", "alleviate"] },
  { id: "v004-40", word: "reluctant", pos: "adj.", ko: ["꺼리는", "마지못한"], freq: 1,
    roots: ["re", "luct"], hint: "re(반대로) + luct(씨름하다) → 속으로 씨름하며 안 하려는",
    ex: { en: "He was reluctant to answer the question.", ko: "그는 그 질문에 답하기를 꺼렸다." },
    syn: ["unwilling", "hesitant"] },
  { id: "v004-41", word: "render", pos: "v.", ko: ["~하게 만들다", "제공하다", "표현하다"], freq: 2,
    roots: ["re", "da"], hint: "re(되돌려) + der(=da, 주다) → 되돌려 주다 → 어떤 상태로 만들어 주다",
    ex: { en: "The injury rendered him unable to work.", ko: "그 부상으로 그는 일을 할 수 없게 되었다." },
    syn: ["make", "provide"] },
  { id: "v004-42", word: "renounce", pos: "v.", ko: ["포기하다", "단념하다"], freq: 3,
    roots: ["re", "nounc"], hint: "re(반대로) + nounc(알리다) → 이제 아니라고 공표하다",
    ex: { en: "He renounced his claim to the throne.", ko: "그는 왕위 계승권을 포기했다." },
    syn: ["give up", "disown"] },
  { id: "v004-43", word: "resemble", pos: "v.", ko: ["닮다", "비슷하다"], freq: 2,
    roots: ["re", "simil"], hint: "re(다시) + simil(같은) → 다시 봐도 같아 보이다",
    ex: { en: "The copy closely resembles the original.", ko: "그 사본은 원본과 매우 닮았다." },
    syn: ["look like", "take after"] },
  { id: "v004-44", word: "resent", pos: "v.", ko: ["분개하다", "억울해하다"], freq: 2,
    roots: ["re", "sent"], hint: "re(되받아) + sent(느끼다) → 당한 것을 되씹으며 느끼다",
    ex: { en: "She resented being left out of the decision.", ko: "그녀는 결정에서 배제된 것에 분개했다." },
    syn: ["begrudge", "take offense at"] },
  { id: "v004-45", word: "reside", pos: "v.", ko: ["거주하다", "존재하다"], freq: 2,
    roots: ["re", "sed"], hint: "re(뒤에) + sid(=sed, 앉다) → 한자리에 계속 앉아 있다",
    ex: { en: "About half the staff reside in the city.", ko: "직원의 약 절반이 그 도시에 거주한다." },
    syn: ["live", "dwell"] },
  { id: "v004-46", word: "restore", pos: "v.", ko: ["복원하다", "회복시키다"], freq: 1,
    roots: ["re", "staur"], hint: "re(다시) + stor(=staur, 세우다) → 무너진 것을 다시 세우다",
    ex: { en: "Workers restored the damaged temple.", ko: "인부들이 훼손된 사원을 복원했다." },
    syn: ["repair", "reinstate"] },
  { id: "v004-47", word: "restrain", pos: "v.", ko: ["억제하다", "제지하다"], freq: 1,
    roots: ["re", "strain"], hint: "re(뒤로) + strain(묶다) → 뒤로 묶어 못 나가게 하다",
    ex: { en: "Guards restrained the angry crowd.", ko: "경비원들이 성난 군중을 제지했다." },
    syn: ["hold back", "curb"] },
  { id: "v004-48", word: "retain", pos: "v.", ko: ["유지하다", "보유하다"], freq: 1,
    roots: ["re", "tain"], hint: "re(계속) + tain(잡다) → 놓지 않고 계속 쥐고 있다",
    ex: { en: "The soil retains water for weeks.", ko: "그 토양은 몇 주간 물을 머금는다." },
    syn: ["keep", "hold on to"] },
  { id: "v004-49", word: "reveal", pos: "v.", ko: ["드러내다", "폭로하다"], freq: 1,
    roots: ["re", "vel"], hint: "re(반대로) + veal(=vel, 베일) → 씌운 베일을 벗기다",
    ex: { en: "The audit revealed several errors.", ko: "감사에서 여러 오류가 드러났다." },
    syn: ["disclose", "expose"] },
  { id: "v004-50", word: "revise", pos: "v.", ko: ["개정하다", "수정하다"], freq: 1,
    roots: ["re", "vis"], hint: "re(다시) + vis(보다) → 다시 보며 고치다",
    ex: { en: "The ministry revised the guidelines.", ko: "그 부처는 지침을 개정했다." },
    syn: ["amend", "update"] },
];
