// DAY 1 — 9급 공무원 최빈출 어휘(동사 중심).
//
// 이 파일은 **정적으로 import되지 않는다**(loader.js의 동적 import로만 불린다) —
// 단어가 8000개까지 늘어날 예정이라 전부 부팅에 실으면 첫 화면이 무거워진다.
// 규칙이 조용히 깨지지 않도록 test/learning.vocab.test.js가 정적 import를 금지한다.
//
// 뜻(ko)은 시험에서 실제로 묻는 뜻만 앞에 둔다. hint는 **어원 우선**(사용자 지시) —
// 어원이 뚜렷하지 않은 단어만 소리연상(sound)을 쓰고, 억지로 지어내지 않는다(D-94의
// "억지 정규식은 신호가 없는 것보다 나쁘다"와 같은 판단).
export const WORDS = [
  { id: "v001-01", word: "abolish", pos: "v.", ko: ["폐지하다", "없애다"], freq: 1,
    roots: ["ab", "ol"], hint: "ab(떨어져) + ol(자라다) → 자라 있던 제도를 뿌리째 떼어내다",
    ex: { en: "The government decided to abolish the outdated law.", ko: "정부는 낡은 법을 폐지하기로 했다." },
    syn: ["repeal", "eliminate"] },
  { id: "v001-02", word: "abandon", pos: "v.", ko: ["버리다", "포기하다"], freq: 1,
    roots: ["ban"], hint: "a + ban(공표해 내주다) → 남의 손에 넘겨 버리고 손을 떼다 · banish와 한 뿌리",
    ex: { en: "They had to abandon the plan due to a lack of funds.", ko: "그들은 자금 부족으로 그 계획을 포기해야 했다." },
    syn: ["desert", "give up"] },
  { id: "v001-03", word: "accelerate", pos: "v.", ko: ["가속하다", "촉진하다"], freq: 2,
    roots: ["ad", "celer"], hint: "ac(=ad, ~쪽으로) + celer(빠른) → 빠른 쪽으로 밀어붙이다",
    ex: { en: "New policies may accelerate economic growth.", ko: "새 정책이 경제 성장을 가속할 수 있다." },
    syn: ["speed up", "hasten"] },
  { id: "v001-04", word: "accommodate", pos: "v.", ko: ["수용하다", "숙박시키다", "맞추어 주다"], freq: 1,
    roots: ["ad", "com", "mod"], hint: "ac(=ad) + com(함께) + mod(알맞게) → 함께 있도록 알맞게 맞춰 받아들이다",
    ex: { en: "The hall can accommodate up to five hundred people.", ko: "그 강당은 500명까지 수용할 수 있다." },
    syn: ["house", "adjust to"] },
  { id: "v001-05", word: "accomplish", pos: "v.", ko: ["성취하다", "완수하다"], freq: 1,
    roots: ["ad", "com", "ple"], hint: "ac(=ad) + com(완전히) + ple(채우다) → 끝까지 채워 이루다",
    ex: { en: "She accomplished the task ahead of schedule.", ko: "그녀는 예정보다 빨리 그 일을 완수했다." },
    syn: ["achieve", "fulfill"] },
  { id: "v001-06", word: "accumulate", pos: "v.", ko: ["축적하다", "모으다"], freq: 2,
    roots: ["ad", "cumul"], hint: "ac(=ad) + cumul(더미) → 더미 쪽으로 계속 쌓다",
    ex: { en: "Dust had accumulated on the old files.", ko: "오래된 서류에 먼지가 쌓여 있었다." },
    syn: ["pile up", "amass"] },
  { id: "v001-07", word: "acknowledge", pos: "v.", ko: ["인정하다", "감사를 표하다"], freq: 1,
    roots: ["know"], hint: "ac(강조) + knowledge(앎) → 안다는 것을 겉으로 드러내 인정하다",
    ex: { en: "He refused to acknowledge his mistake.", ko: "그는 자기 잘못을 인정하기를 거부했다." },
    syn: ["admit", "recognize"] },
  { id: "v001-08", word: "acquire", pos: "v.", ko: ["획득하다", "습득하다"], freq: 1,
    roots: ["ad", "quir"], hint: "ac(=ad) + quir(구하다) → 구해서 내 쪽으로 가져오다",
    ex: { en: "Children acquire language surprisingly fast.", ko: "아이들은 놀랄 만큼 빠르게 언어를 습득한다." },
    syn: ["obtain", "gain"] },
  { id: "v001-09", word: "adapt", pos: "v.", ko: ["적응하다", "개작하다"], freq: 1,
    roots: ["ad", "apt"], hint: "ad(~로) + apt(알맞은) → 그 상황에 알맞게 자기를 맞추다",
    ex: { en: "Immigrants must adapt to a new culture.", ko: "이민자들은 새로운 문화에 적응해야 한다." },
    syn: ["adjust", "modify"] },
  { id: "v001-10", word: "adhere", pos: "v.", ko: ["고수하다", "들러붙다"], freq: 2,
    roots: ["ad", "her"], hint: "ad(~에) + her(붙다) → 원칙에 딱 붙어 떨어지지 않다",
    ex: { en: "All members must adhere to the rules.", ko: "모든 회원은 규칙을 준수해야 한다." },
    syn: ["stick to", "comply with"] },
  { id: "v001-11", word: "administer", pos: "v.", ko: ["관리하다", "집행하다", "투여하다"], freq: 2,
    roots: ["ad", "minister"], hint: "ad(~에게) + minister(봉사하다) → 남을 위해 일을 맡아 처리하다",
    ex: { en: "The agency administers the welfare program.", ko: "그 기관이 복지 사업을 관리한다." },
    syn: ["manage", "oversee"] },
  { id: "v001-12", word: "admit", pos: "v.", ko: ["인정하다", "입장을 허락하다"], freq: 1,
    roots: ["ad", "mit"], hint: "ad(~로) + mit(보내다) → 안으로 들여보내다 · 사실을 들여놓다",
    ex: { en: "He finally admitted that he was wrong.", ko: "그는 마침내 자기가 틀렸음을 인정했다." },
    syn: ["confess", "concede"] },
  { id: "v001-13", word: "advocate", pos: "v./n.", ko: ["옹호하다", "지지자"], freq: 1,
    roots: ["ad", "voc"], hint: "ad(~쪽으로) + voc(부르다) → 그 편을 들어 목소리를 내다",
    ex: { en: "She advocates stronger environmental rules.", ko: "그녀는 더 강한 환경 규제를 옹호한다." },
    syn: ["support", "champion"] },
  { id: "v001-14", word: "affect", pos: "v.", ko: ["영향을 미치다", "~인 척하다"], freq: 1,
    roots: ["ad", "fect"], hint: "af(=ad, ~에) + fect(하다) → 상대에게 무언가를 해서 변화를 주다",
    ex: { en: "The drought will affect food prices.", ko: "가뭄이 식료품 가격에 영향을 미칠 것이다." },
    syn: ["influence", "impact"] },
  { id: "v001-15", word: "aggravate", pos: "v.", ko: ["악화시키다", "짜증나게 하다"], freq: 2,
    roots: ["ad", "grav"], hint: "ag(=ad) + grav(무거운) → 상황을 더 무겁게 만들다",
    ex: { en: "Stress can aggravate the symptoms.", ko: "스트레스는 증상을 악화시킬 수 있다." },
    syn: ["worsen", "exacerbate"] },
  { id: "v001-16", word: "allocate", pos: "v.", ko: ["할당하다", "배분하다"], freq: 1,
    roots: ["ad", "loc"], hint: "al(=ad) + loc(장소) → 각자의 자리로 몫을 보내다",
    ex: { en: "The city will allocate more funds to public transit.", ko: "시는 대중교통에 더 많은 예산을 배분할 것이다." },
    syn: ["assign", "distribute"] },
  { id: "v001-17", word: "alleviate", pos: "v.", ko: ["완화하다", "덜어주다"], freq: 1,
    roots: ["ad", "lev"], hint: "al(=ad) + lev(가벼운) → 무게를 덜어 가볍게 해주다",
    ex: { en: "The medicine helped alleviate the pain.", ko: "그 약이 통증을 완화하는 데 도움이 되었다." },
    syn: ["relieve", "ease"] },
  { id: "v001-18", word: "alter", pos: "v.", ko: ["바꾸다", "변경하다"], freq: 2,
    roots: ["alter"], hint: "alter(다른) → 다른 것으로 만들다",
    ex: { en: "You cannot alter the terms of the contract.", ko: "계약 조건을 임의로 바꿀 수는 없다." },
    syn: ["change", "modify"] },
  { id: "v001-19", word: "anticipate", pos: "v.", ko: ["예상하다", "기대하다"], freq: 1,
    roots: ["ante", "cip"], hint: "anti(=ante, 미리) + cip(잡다) → 오기 전에 미리 붙잡아 두다",
    ex: { en: "We anticipate a rise in applications this year.", ko: "우리는 올해 지원자 증가를 예상한다." },
    syn: ["expect", "foresee"] },
  { id: "v001-20", word: "appeal", pos: "v./n.", ko: ["호소하다", "항소하다", "매력"], freq: 1,
    roots: ["ad", "pel"], hint: "ap(=ad, ~에게) + pel(밀다) → 상대 마음을 향해 밀어붙이다",
    ex: { en: "The charity appealed for donations.", ko: "그 자선단체는 기부를 호소했다." },
    syn: ["plead", "attract"] },
  { id: "v001-21", word: "apply", pos: "v.", ko: ["적용하다", "지원하다", "바르다"], freq: 1,
    roots: ["ad", "plic"], hint: "ap(=ad, ~에) + plic(접다) → 대상에 착 접어 붙이다",
    ex: { en: "The same rule applies to everyone.", ko: "같은 규칙이 모두에게 적용된다." },
    syn: ["use", "request"] },
  { id: "v001-22", word: "appreciate", pos: "v.", ko: ["진가를 알아보다", "감사하다", "가치가 오르다"], freq: 1,
    roots: ["ad", "preci"], hint: "ap(=ad) + preci(값) → 값을 제대로 매겨 알아주다",
    ex: { en: "I appreciate your help with the report.", ko: "보고서를 도와주셔서 감사합니다." },
    syn: ["value", "be grateful for"] },
  { id: "v001-23", word: "approve", pos: "v.", ko: ["승인하다", "찬성하다"], freq: 1,
    roots: ["ad", "prob"], hint: "ap(=ad) + prob(좋다고 입증하다) → 좋다고 도장을 찍어주다",
    ex: { en: "The committee approved the new budget.", ko: "위원회는 새 예산을 승인했다." },
    syn: ["authorize", "endorse"] },
  { id: "v001-24", word: "assemble", pos: "v.", ko: ["모으다", "조립하다"], freq: 2,
    roots: ["ad", "simil"], hint: "as(=ad) + simil(같은) → 같은 것들을 한자리로 모으다",
    ex: { en: "Workers assemble the parts by hand.", ko: "작업자들이 부품을 손으로 조립한다." },
    syn: ["gather", "put together"] },
  { id: "v001-25", word: "assert", pos: "v.", ko: ["주장하다", "단언하다"], freq: 1,
    roots: ["ad", "sert"], hint: "as(=ad) + sert(엮다) → 내 말을 단단히 엮어 내놓다",
    ex: { en: "He asserted that the data was accurate.", ko: "그는 그 자료가 정확하다고 주장했다." },
    syn: ["claim", "declare"] },
  { id: "v001-26", word: "assess", pos: "v.", ko: ["평가하다", "산정하다"], freq: 1,
    roots: ["ad", "sed"], hint: "as(=ad, 옆에) + sed(앉다) → 옆에 앉아 값을 매기다(세금을 매기던 말)",
    ex: { en: "Teachers assess students twice a year.", ko: "교사들은 일 년에 두 번 학생을 평가한다." },
    syn: ["evaluate", "appraise"] },
  { id: "v001-27", word: "assign", pos: "v.", ko: ["배정하다", "맡기다"], freq: 1,
    roots: ["ad", "sign"], hint: "as(=ad) + sign(표시) → 누구 몫인지 표시해 주다",
    ex: { en: "The manager assigned me a new project.", ko: "관리자가 나에게 새 프로젝트를 맡겼다." },
    syn: ["allot", "appoint"] },
  { id: "v001-28", word: "assume", pos: "v.", ko: ["가정하다", "떠맡다"], freq: 1,
    roots: ["ad", "sum"], hint: "as(=ad) + sum(취하다) → 확인 전에 먼저 취해 놓다 · 역할을 떠안다",
    ex: { en: "Let us assume that the report is correct.", ko: "그 보고서가 맞다고 가정해 보자." },
    syn: ["suppose", "take on"] },
  { id: "v001-29", word: "attain", pos: "v.", ko: ["달성하다", "이르다"], freq: 2,
    roots: ["ad", "tang"], hint: "at(=ad, ~에) + tang(닿다) → 목표에 손이 닿다",
    ex: { en: "She attained the highest score in the exam.", ko: "그녀는 시험에서 최고 점수를 달성했다." },
    syn: ["achieve", "reach"] },
  { id: "v001-30", word: "attribute", pos: "v./n.", ko: ["~의 탓으로 돌리다", "속성"], freq: 1,
    roots: ["ad", "tribut"], hint: "at(=ad, ~에게) + tribut(나누어 주다) → 원인을 그쪽 몫으로 나눠 주다",
    ex: { en: "He attributes his success to hard work.", ko: "그는 자신의 성공을 노력 덕분으로 돌린다." },
    syn: ["ascribe", "credit"] },
  { id: "v001-31", word: "avoid", pos: "v.", ko: ["피하다", "막다"], freq: 1,
    roots: ["ex", "void"], hint: "a(=ex, 밖으로) + void(빈) → 자리를 비우고 빠져나가다",
    ex: { en: "Try to avoid unnecessary conflict.", ko: "불필요한 갈등은 피하려고 해라." },
    syn: ["evade", "prevent"] },
  { id: "v001-32", word: "banish", pos: "v.", ko: ["추방하다", "쫓아내다"], freq: 3,
    roots: ["ban"], hint: "ban(공표하여 내쫓다) → 공식적으로 밖으로 내보내다",
    ex: { en: "The king banished the rebel from the country.", ko: "왕은 그 반역자를 나라 밖으로 추방했다." },
    syn: ["expel", "exile"] },
  { id: "v001-33", word: "boost", pos: "v./n.", ko: ["신장시키다", "촉진하다", "증가"], freq: 2,
    roots: [], sound: "부스트(boost) — 밑에서 부스터를 달아 위로 밀어 올린다",
    hint: "어원이 뚜렷하지 않은 단어라 소리로 잡는다 — 부스터를 달아 위로 밀어 올리는 그림.",
    ex: { en: "The tax cut is expected to boost consumption.", ko: "감세가 소비를 촉진할 것으로 예상된다." },
    syn: ["increase", "promote"] },
  { id: "v001-34", word: "cease", pos: "v.", ko: ["중단하다", "그치다"], freq: 2,
    roots: ["ced"], hint: "ced(가다) → 하던 것이 가 버리다, 즉 멈추다",
    ex: { en: "The factory ceased operations last year.", ko: "그 공장은 작년에 가동을 중단했다." },
    syn: ["stop", "halt"] },
  { id: "v001-35", word: "cite", pos: "v.", ko: ["인용하다", "언급하다"], freq: 2,
    roots: ["cit"], hint: "cit(불러내다) → 남의 말을 불러내 가져오다",
    ex: { en: "The author cites several recent studies.", ko: "저자는 최근 연구 몇 편을 인용한다." },
    syn: ["quote", "refer to"] },
  { id: "v001-36", word: "collapse", pos: "v./n.", ko: ["붕괴하다", "무너짐"], freq: 2,
    roots: ["com", "laps"], hint: "col(=com, 함께) + laps(미끄러지다) → 통째로 함께 미끄러져 내려앉다",
    ex: { en: "The old bridge collapsed after the flood.", ko: "낡은 다리가 홍수 뒤에 무너졌다." },
    syn: ["fall down", "break down"] },
  { id: "v001-37", word: "commence", pos: "v.", ko: ["시작하다", "개시하다"], freq: 3,
    roots: ["com", "init"], hint: "com(함께) + init(들어가다) → 다 같이 첫발을 들이다",
    ex: { en: "The trial will commence next Monday.", ko: "재판은 다음 주 월요일에 시작된다." },
    syn: ["begin", "start"] },
  { id: "v001-38", word: "commit", pos: "v.", ko: ["저지르다", "전념하다", "맡기다"], freq: 1,
    roots: ["com", "mit"], hint: "com(함께) + mit(보내다) → 자신을 그쪽으로 함께 보내 버리다",
    ex: { en: "The company committed itself to reducing waste.", ko: "그 회사는 폐기물 감축에 전념하기로 했다." },
    syn: ["dedicate", "perpetrate"] },
  { id: "v001-39", word: "compel", pos: "v.", ko: ["강요하다", "억지로 ~하게 하다"], freq: 1,
    roots: ["com", "pel"], hint: "com(강조) + pel(밀다) → 세게 밀어붙여 하게 만들다",
    ex: { en: "Bad weather compelled us to cancel the trip.", ko: "악천후 때문에 우리는 여행을 취소해야 했다." },
    syn: ["force", "oblige"] },
  { id: "v001-40", word: "compensate", pos: "v.", ko: ["보상하다", "상쇄하다"], freq: 1,
    roots: ["com", "pens"], hint: "com(함께) + pens(무게를 달다) → 저울 양쪽 무게를 맞춰 주다",
    ex: { en: "The firm compensated workers for the delay.", ko: "회사는 지연에 대해 근로자들에게 보상했다." },
    syn: ["repay", "offset"] },
  { id: "v001-41", word: "comply", pos: "v.", ko: ["따르다", "준수하다"], freq: 1,
    roots: ["com", "ple"], hint: "com(완전히) + ple(채우다) → 요구를 빠짐없이 채워 주다",
    ex: { en: "All firms must comply with the safety rules.", ko: "모든 기업은 안전 규정을 준수해야 한다." },
    syn: ["obey", "conform"] },
  { id: "v001-42", word: "comprehend", pos: "v.", ko: ["이해하다", "포함하다"], freq: 2,
    roots: ["com", "prehend"], hint: "com(완전히) + prehend(붙잡다) → 뜻을 통째로 붙잡다",
    ex: { en: "Few readers fully comprehend the theory.", ko: "그 이론을 온전히 이해하는 독자는 드물다." },
    syn: ["understand", "grasp"] },
  { id: "v001-43", word: "conceal", pos: "v.", ko: ["숨기다", "감추다"], freq: 1,
    roots: ["com", "ceal"], hint: "con(=com, 완전히) + ceal(덮다) → 완전히 덮어 안 보이게 하다",
    ex: { en: "He tried to conceal the truth from us.", ko: "그는 우리에게 진실을 감추려 했다." },
    syn: ["hide", "cover up"] },
  { id: "v001-44", word: "concede", pos: "v.", ko: ["인정하다", "양보하다"], freq: 2,
    roots: ["com", "ced"], hint: "con(=com, 함께) + ced(가다) → 상대 쪽으로 한 걸음 물러나 주다",
    ex: { en: "She conceded that the plan had flaws.", ko: "그녀는 그 계획에 결함이 있음을 인정했다." },
    syn: ["admit", "yield"] },
  { id: "v001-45", word: "condemn", pos: "v.", ko: ["비난하다", "선고하다"], freq: 1,
    roots: ["com", "damn"], hint: "con(=com, 강조) + damn(해를 입히다·유죄로 하다) → 강하게 유죄를 찍다",
    ex: { en: "World leaders condemned the attack.", ko: "세계 지도자들은 그 공격을 규탄했다." },
    syn: ["denounce", "criticize"] },
  { id: "v001-46", word: "conduct", pos: "v./n.", ko: ["수행하다", "지휘하다", "행동"], freq: 1,
    roots: ["com", "duc"], hint: "con(=com, 함께) + duc(이끌다) → 사람들을 이끌어 일을 이끌어 가다",
    ex: { en: "The team conducted a nationwide survey.", ko: "그 팀은 전국적인 조사를 실시했다." },
    syn: ["carry out", "behavior"] },
  { id: "v001-47", word: "confine", pos: "v.", ko: ["제한하다", "가두다"], freq: 2,
    roots: ["com", "fin"], hint: "con(=com, 함께) + fin(경계) → 경계 안에 함께 묶어 두다",
    ex: { en: "The discussion was confined to budget issues.", ko: "논의는 예산 문제로 국한되었다." },
    syn: ["restrict", "limit"] },
  { id: "v001-48", word: "conform", pos: "v.", ko: ["순응하다", "따르다"], freq: 2,
    roots: ["com", "form"], hint: "con(=com, 함께) + form(모양) → 남들과 같은 모양이 되다",
    ex: { en: "Products must conform to national standards.", ko: "제품은 국가 표준에 부합해야 한다." },
    syn: ["comply", "adapt"] },
  { id: "v001-49", word: "confront", pos: "v.", ko: ["직면하다", "맞서다"], freq: 1,
    roots: ["com", "front"], hint: "con(=com, 마주) + front(이마·앞) → 이마를 맞대고 마주 서다",
    ex: { en: "The city confronts a serious housing shortage.", ko: "그 도시는 심각한 주택 부족에 직면해 있다." },
    syn: ["face", "encounter"] },
  { id: "v001-50", word: "consent", pos: "v./n.", ko: ["동의하다", "동의"], freq: 1,
    roots: ["com", "sent"], hint: "con(=com, 함께) + sent(느끼다) → 같이 느끼다, 즉 뜻을 같이하다",
    ex: { en: "The patient gave written consent to the surgery.", ko: "환자는 수술에 서면으로 동의했다." },
    syn: ["agree", "approval"] },
];
