// DAY 5 — 빈출 형용사 ①. 파일 성격은 day-001.js 헤더 참고(동적 import 전용).
//
// 1단계(DAY 1~4)가 동사에 몰려 있어 2단계는 형용사부터 연다 — 독해에서 정답을 가르는 건
// 대개 동사가 아니라 수식어라서, 동사만 500개 아는 상태보다 균형이 낫다.
export const WORDS = [
  { id: "v005-01", word: "abundant", pos: "adj.", ko: ["풍부한", "많은"], freq: 1,
    roots: ["ab", "und"], hint: "ab(멀리) + und(물결) → 물결이 멀리까지 넘칠 만큼 많은",
    ex: { en: "The region has abundant rainfall in summer.", ko: "그 지역은 여름에 강수량이 풍부하다." },
    syn: ["plentiful", "ample"] },
  { id: "v005-02", word: "adequate", pos: "adj.", ko: ["충분한", "적절한"], freq: 1,
    roots: ["ad", "equ"], hint: "ad(~에) + equ(같은) → 필요한 만큼과 같은, 즉 모자라지 않은",
    ex: { en: "The budget is adequate for a one-year study.", ko: "그 예산은 1년짜리 연구에 충분하다." },
    syn: ["sufficient", "enough"] },
  { id: "v005-03", word: "ambiguous", pos: "adj.", ko: ["모호한", "두 가지로 읽히는"], freq: 1,
    roots: ["ambi"], hint: "ambi(양쪽) + ig(몰다) → 양쪽 어디로든 몰고 갈 수 있는",
    ex: { en: "The wording of the clause is ambiguous.", ko: "그 조항의 표현은 모호하다." },
    syn: ["unclear", "equivocal"] },
  { id: "v005-04", word: "apparent", pos: "adj.", ko: ["명백한", "겉보기의"], freq: 1,
    roots: ["ad", "par-appear"], hint: "ap(=ad, ~쪽으로) + par(나타나다) → 눈앞으로 나타나 보이는",
    ex: { en: "It became apparent that the plan would fail.", ko: "그 계획이 실패하리라는 게 명백해졌다." },
    syn: ["evident", "seeming"] },
  { id: "v005-05", word: "arbitrary", pos: "adj.", ko: ["자의적인", "제멋대로인"], freq: 1,
    roots: ["arbitr"], hint: "arbitr(심판) → 심판 한 사람 마음대로 정해 버린",
    ex: { en: "The fine seemed arbitrary and unfair.", ko: "그 벌금은 자의적이고 부당해 보였다." },
    syn: ["random", "high-handed"] },
  { id: "v005-06", word: "authentic", pos: "adj.", ko: ["진품인", "진짜의"], freq: 1,
    roots: ["auto"], hint: "auth(=auto, 스스로) → 본인에게서 곧장 나온, 베낀 게 아닌",
    ex: { en: "Experts confirmed the painting is authentic.", ko: "전문가들은 그 그림이 진품임을 확인했다." },
    syn: ["real", "bona fide"] },
  { id: "v005-07", word: "coherent", pos: "adj.", ko: ["일관된", "조리 있는"], freq: 1,
    roots: ["com", "her"], hint: "co(=com, 함께) + her(붙다) → 조각들이 서로 붙어 흩어지지 않는",
    ex: { en: "She gave a coherent account of the accident.", ko: "그녀는 사고를 조리 있게 진술했다." },
    syn: ["consistent", "logical"] },
  { id: "v005-08", word: "competent", pos: "adj.", ko: ["유능한", "능력을 갖춘"], freq: 1,
    roots: ["com", "pet"], hint: "com(함께) + pet(향해 가다) → 요구되는 수준까지 함께 따라가는",
    ex: { en: "He is a competent administrator.", ko: "그는 유능한 행정가다." },
    syn: ["capable", "qualified"] },
  { id: "v005-09", word: "comprehensive", pos: "adj.", ko: ["포괄적인", "종합적인"], freq: 1,
    roots: ["com", "prehend"], hint: "com(전부) + prehend(붙잡다) → 빠짐없이 한꺼번에 붙잡은",
    ex: { en: "The report gives a comprehensive review of the policy.", ko: "그 보고서는 정책을 종합적으로 검토한다." },
    syn: ["thorough", "wide-ranging"] },
  { id: "v005-10", word: "conspicuous", pos: "adj.", ko: ["눈에 띄는", "뚜렷한"], freq: 2,
    roots: ["com", "spect"], hint: "con(=com, 완전히) + spic(=spect, 보다) → 눈에 완전히 들어오는",
    ex: { en: "His absence was conspicuous at the meeting.", ko: "회의에서 그의 부재가 눈에 띄었다." },
    syn: ["noticeable", "striking"] },
  { id: "v005-11", word: "controversial", pos: "adj.", ko: ["논란이 되는"], freq: 1,
    roots: ["contra", "vers"], hint: "contra(맞서) + vers(돌다) → 서로 반대로 돌아서서 맞붙는",
    ex: { en: "The bill remains highly controversial.", ko: "그 법안은 여전히 크게 논란이 된다." },
    syn: ["disputed", "contentious"] },
  { id: "v005-12", word: "crucial", pos: "adj.", ko: ["결정적인", "중대한"], freq: 1,
    roots: ["cruc"], hint: "cruc(십자, 갈림길) → 길이 갈리는 지점에 놓인",
    ex: { en: "Timing is crucial in this operation.", ko: "이 작전에서는 시점이 결정적이다." },
    syn: ["critical", "vital"] },
  { id: "v005-13", word: "cumulative", pos: "adj.", ko: ["누적되는"], freq: 2,
    roots: ["cumul"], hint: "cumul(더미) → 더미로 차곡차곡 쌓여 가는",
    ex: { en: "The cumulative effect of the tax is large.", ko: "그 세금의 누적 효과는 크다." },
    syn: ["accruing", "aggregate"] },
  { id: "v005-14", word: "diligent", pos: "adj.", ko: ["부지런한", "성실한"], freq: 1,
    roots: ["dis", "leg"], hint: "di(=dis, 따로) + lig(=leg, 고르다) → 하나하나 따로 골라 챙기는",
    ex: { en: "She is a diligent and careful worker.", ko: "그녀는 부지런하고 꼼꼼한 직원이다." },
    syn: ["industrious", "assiduous"] },
  { id: "v005-15", word: "eligible", pos: "adj.", ko: ["자격이 있는"], freq: 1,
    roots: ["ex", "leg"], hint: "e(=ex, 밖으로) + lig(=leg, 고르다) → 뽑아낼 만한",
    ex: { en: "Only residents are eligible for the subsidy.", ko: "거주자만 그 보조금을 받을 자격이 있다." },
    syn: ["qualified", "entitled"] },
  { id: "v005-16", word: "eminent", pos: "adj.", ko: ["저명한", "탁월한"], freq: 2,
    roots: ["ex", "min-jut"], hint: "e(=ex, 밖으로) + min(튀어나오다) → 무리 밖으로 튀어나온",
    ex: { en: "An eminent scholar chaired the panel.", ko: "저명한 학자가 그 패널을 주재했다." },
    syn: ["distinguished", "renowned"] },
  { id: "v005-17", word: "equivalent", pos: "adj.", ko: ["동등한", "맞먹는"], freq: 1,
    roots: ["equ", "valu"], hint: "equ(같은) + valu(가치) → 가치가 같은",
    ex: { en: "One mile is equivalent to about 1.6 kilometers.", ko: "1마일은 약 1.6킬로미터에 해당한다." },
    syn: ["equal", "comparable"] },
  { id: "v005-18", word: "feasible", pos: "adj.", ko: ["실현 가능한"], freq: 1,
    roots: ["fect"], hint: "feas(=fect, 하다) + ible(할 수 있는) → 해낼 수 있는",
    ex: { en: "The committee found the plan feasible.", ko: "위원회는 그 계획이 실현 가능하다고 봤다." },
    syn: ["workable", "practicable"] },
  { id: "v005-19", word: "fragile", pos: "adj.", ko: ["깨지기 쉬운", "허약한"], freq: 1,
    roots: ["frag"], hint: "frag(부수다) → 조금만 건드려도 부서지는",
    ex: { en: "The peace deal is still fragile.", ko: "그 평화 협정은 여전히 허약하다." },
    syn: ["brittle", "delicate"] },
  { id: "v005-20", word: "genuine", pos: "adj.", ko: ["진심의", "꾸밈없는"], freq: 1,
    roots: ["gen"], hint: "gen(낳다) → 태어난 그대로라 꾸밈이 없는",
    ex: { en: "He showed genuine concern for the victims.", ko: "그는 피해자들에게 진심 어린 걱정을 보였다." },
    syn: ["sincere", "heartfelt"] },
  { id: "v005-21", word: "hostile", pos: "adj.", ko: ["적대적인"], freq: 1,
    roots: ["host"], hint: "host(적, 낯선 이) → 적을 대하듯 날을 세운",
    ex: { en: "The crowd turned hostile after the ruling.", ko: "판결 뒤 군중은 적대적으로 변했다." },
    syn: ["antagonistic", "unfriendly"] },
  { id: "v005-22", word: "imminent", pos: "adj.", ko: ["임박한"], freq: 1,
    roots: ["in", "min-jut"], hint: "im(=in, 위로) + min(튀어나오다) → 머리 위로 튀어나올 만큼 코앞에 온",
    ex: { en: "A storm is imminent along the coast.", ko: "해안에 폭풍이 임박했다." },
    syn: ["impending", "looming"] },
  { id: "v005-23", word: "indifferent", pos: "adj.", ko: ["무관심한"], freq: 1,
    roots: ["in-neg", "dis", "fer"], hint: "in(아닌) + dif(=dis, 따로) + fer(나르다) → 이쪽저쪽 갈릴 게 없는, 관심이 안 가는",
    ex: { en: "Voters seemed indifferent to the debate.", ko: "유권자들은 그 토론에 무관심해 보였다." },
    syn: ["apathetic", "unconcerned"] },
  { id: "v005-24", word: "intact", pos: "adj.", ko: ["온전한", "손상되지 않은"], freq: 1,
    roots: ["in-neg", "tang"], hint: "in(아닌) + tact(=tang, 닿다) → 아무도 손대지 않은",
    ex: { en: "The seal on the box was still intact.", ko: "상자의 봉인은 여전히 온전했다." },
    syn: ["undamaged", "whole"] },
  { id: "v005-25", word: "intense", pos: "adj.", ko: ["강렬한", "극심한"], freq: 1,
    roots: ["in", "tens"], hint: "in(안으로) + tens(팽팽히 당기다) → 안으로 팽팽히 당겨진",
    ex: { en: "The heat grew intense by noon.", ko: "정오가 되자 더위가 극심해졌다." },
    syn: ["fierce", "severe"] },
  { id: "v005-26", word: "intricate", pos: "adj.", ko: ["얽히고설킨", "정교한"], freq: 2,
    roots: ["in", "tric"], hint: "in(안에) + tric(얽힘) → 안이 얽히고설킨",
    ex: { en: "The carving shows an intricate pattern.", ko: "그 조각은 정교한 무늬를 보여 준다." },
    syn: ["complicated", "elaborate"] },
  { id: "v005-27", word: "lucrative", pos: "adj.", ko: ["수익성 좋은"], freq: 2,
    roots: ["lucr"], hint: "lucr(이익) → 이익이 붙어 나오는",
    ex: { en: "Consulting proved a lucrative side business.", ko: "컨설팅은 수익성 좋은 부업으로 드러났다." },
    syn: ["profitable", "well-paid"] },
  { id: "v005-28", word: "mutual", pos: "adj.", ko: ["서로의", "상호 간의"], freq: 1,
    roots: ["mut"], hint: "mut(바꾸다) → 서로 주고받아 맞바꾸는",
    ex: { en: "The two sides reached a mutual understanding.", ko: "양측은 상호 이해에 도달했다." },
    syn: ["reciprocal", "shared"] },
  { id: "v005-29", word: "notable", pos: "adj.", ko: ["주목할 만한"], freq: 1,
    roots: ["not"], hint: "not(표시, 적다) → 따로 적어 둘 만한",
    ex: { en: "There was a notable rise in applications.", ko: "지원자 수가 주목할 만큼 늘었다." },
    syn: ["remarkable", "noteworthy"] },
  { id: "v005-30", word: "obsolete", pos: "adj.", ko: ["한물간", "구식의"], freq: 2,
    roots: ["ob"], hint: "ob(완전히) + solete(늘 하던 대로 함) → 늘 쓰이던 것이 다 낡아 더는 안 쓰이는",
    ex: { en: "The system became obsolete within five years.", ko: "그 시스템은 5년 만에 구식이 됐다." },
    syn: ["outdated", "antiquated"] },
  { id: "v005-31", word: "optimal", pos: "adj.", ko: ["최적의"], freq: 2,
    roots: ["optim"], hint: "optim(가장 좋은) → 고를 수 있는 것 중 가장 좋은",
    ex: { en: "We searched for the optimal route.", ko: "우리는 최적의 경로를 찾았다." },
    syn: ["ideal", "best"] },
  { id: "v005-32", word: "perpetual", pos: "adj.", ko: ["끊임없는", "영구적인"], freq: 2,
    roots: ["per", "pet"], hint: "per(끝까지) + pet(향해 가다) → 끝까지 멈추지 않고 나아가는",
    ex: { en: "He lives in perpetual fear of failure.", ko: "그는 실패에 대한 끊임없는 두려움 속에 산다." },
    syn: ["ceaseless", "everlasting"] },
  { id: "v005-33", word: "plausible", pos: "adj.", ko: ["그럴듯한"], freq: 1,
    roots: ["plaus"], hint: "plaus(박수치다) → 박수를 받을 만큼 그럴싸해 보이는",
    ex: { en: "That sounds like a plausible explanation.", ko: "그건 그럴듯한 설명으로 들린다." },
    syn: ["credible", "believable"] },
  { id: "v005-34", word: "precise", pos: "adj.", ko: ["정확한", "정밀한"], freq: 1,
    roots: ["pre", "cis"], hint: "pre(미리) + cis(자르다) → 미리 딱 잘라 두어 어긋남이 없는",
    ex: { en: "We need the precise number of applicants.", ko: "우리는 지원자의 정확한 수가 필요하다." },
    syn: ["exact", "accurate"] },
  { id: "v005-35", word: "profound", pos: "adj.", ko: ["깊은", "심오한"], freq: 1,
    roots: ["pro", "fund"], hint: "pro(앞으로 깊이) + found(=fund, 바닥) → 바닥까지 닿을 만큼 깊은",
    ex: { en: "The war had a profound effect on the economy.", ko: "그 전쟁은 경제에 깊은 영향을 미쳤다." },
    syn: ["deep", "far-reaching"] },
  { id: "v005-36", word: "redundant", pos: "adj.", ko: ["불필요한", "남아도는"], freq: 2,
    roots: ["re", "und"], hint: "re(다시) + und(물결) → 물결이 되풀이돼 넘쳐 남는",
    ex: { en: "The second paragraph is redundant.", ko: "두 번째 문단은 불필요하다." },
    syn: ["superfluous", "excess"] },
  { id: "v005-37", word: "rigid", pos: "adj.", ko: ["융통성 없는", "뻣뻣한"], freq: 1,
    roots: ["rig"], hint: "rig(뻣뻣한) → 굽힐 줄 모르게 뻣뻣한",
    ex: { en: "The school has rigid rules about uniforms.", ko: "그 학교는 교복에 관해 융통성 없는 규칙을 둔다." },
    syn: ["inflexible", "stiff"] },
  { id: "v005-38", word: "robust", pos: "adj.", ko: ["튼튼한", "탄탄한"], freq: 2,
    roots: ["rob"], hint: "rob(참나무, 힘) → 참나무처럼 단단한",
    ex: { en: "The economy remains robust despite the shock.", ko: "충격에도 경제는 탄탄하다." },
    syn: ["sturdy", "hardy"] },
  { id: "v005-39", word: "rural", pos: "adj.", ko: ["시골의", "농촌의"], freq: 1,
    roots: ["rur"], hint: "rur(시골, 들) → 들이 펼쳐진 곳의",
    ex: { en: "Many rural towns are losing population.", ko: "많은 농촌 마을이 인구를 잃고 있다." },
    syn: ["rustic", "country"] },
  { id: "v005-40", word: "subsequent", pos: "adj.", ko: ["그 뒤의", "이어지는"], freq: 1,
    roots: ["sub", "secut"], hint: "sub(뒤에) + sequ(=secut, 따르다) → 뒤에 따라오는",
    ex: { en: "Subsequent tests confirmed the result.", ko: "이후의 검사들이 그 결과를 확인해 줬다." },
    syn: ["following", "later"] },
  { id: "v005-41", word: "subtle", pos: "adj.", ko: ["미묘한", "포착하기 힘든"], freq: 1,
    roots: ["sub", "tel"], hint: "sub(아래로) + tle(=tel, 천) → 천 올 사이로 빠져나갈 만큼 가느다란",
    ex: { en: "There is a subtle difference between the two words.", ko: "그 두 단어 사이에는 미묘한 차이가 있다." },
    syn: ["slight", "delicate"] },
  { id: "v005-42", word: "superficial", pos: "adj.", ko: ["피상적인", "겉핥기의"], freq: 2,
    roots: ["super", "faci"], hint: "super(위) + fici(=faci, 겉면) → 겉면 위만 훑고 마는",
    ex: { en: "His knowledge of the topic is superficial.", ko: "그 주제에 대한 그의 지식은 피상적이다." },
    syn: ["shallow", "cursory"] },
  { id: "v005-43", word: "susceptible", pos: "adj.", ko: ["영향받기 쉬운", "잘 걸리는"], freq: 2,
    roots: ["sub", "cip"], hint: "sus(=sub, 아래에서) + cept(=cip, 잡다) → 아래에서 덥석 받아들이는",
    ex: { en: "Young children are susceptible to the virus.", ko: "어린아이들은 그 바이러스에 잘 걸린다." },
    syn: ["prone", "liable"] },
  { id: "v005-44", word: "tedious", pos: "adj.", ko: ["지루한", "싫증 나는"], freq: 2,
    roots: ["ted"], hint: "ted(지겹게 하다) → 지겨워 한없이 늘어지는",
    ex: { en: "Copying the list was tedious work.", ko: "목록을 옮겨 적는 건 지루한 일이었다." },
    syn: ["boring", "tiresome"] },
  { id: "v005-45", word: "tentative", pos: "adj.", ko: ["잠정적인", "머뭇거리는"], freq: 2,
    roots: ["tent"], hint: "tent(더듬다, 시도하다) → 손으로 한번 더듬어 본 정도의",
    ex: { en: "They reached a tentative agreement.", ko: "그들은 잠정적 합의에 이르렀다." },
    syn: ["provisional", "hesitant"] },
  { id: "v005-46", word: "transparent", pos: "adj.", ko: ["투명한", "숨김없는"], freq: 1,
    roots: ["trans", "par-appear"], hint: "trans(건너) + par(나타나다) → 건너편이 그대로 나타나 보이는",
    ex: { en: "The process must be transparent to the public.", ko: "그 절차는 국민에게 투명해야 한다." },
    syn: ["clear", "open"] },
  { id: "v005-47", word: "trivial", pos: "adj.", ko: ["사소한", "하찮은"], freq: 1,
    roots: ["tri", "via"], hint: "tri(셋) + via(길) → 세 갈래 길목에서 오가는 흔해 빠진 이야깃거리",
    ex: { en: "Do not waste time on trivial details.", ko: "사소한 세부 사항에 시간을 낭비하지 마라." },
    syn: ["petty", "insignificant"] },
  { id: "v005-48", word: "ubiquitous", pos: "adj.", ko: ["어디에나 있는"], freq: 2,
    roots: ["ubi"], hint: "ubi(어디에나) → 안 가는 데가 없는",
    ex: { en: "Smartphones are ubiquitous in daily life.", ko: "스마트폰은 일상 어디에나 있다." },
    syn: ["omnipresent", "pervasive"] },
  { id: "v005-49", word: "vulnerable", pos: "adj.", ko: ["상처받기 쉬운", "취약한"], freq: 1,
    roots: ["vulner"], hint: "vulner(상처) → 상처를 그대로 입게 되는",
    ex: { en: "The elderly are vulnerable to heat waves.", ko: "노인들은 폭염에 취약하다." },
    syn: ["exposed", "defenseless"] },
  { id: "v005-50", word: "adverse", pos: "adj.", ko: ["불리한", "부정적인"], freq: 1,
    roots: ["ad", "vers"], hint: "ad(~쪽으로) + vers(돌다) → 나를 향해 맞돌아선",
    ex: { en: "The ruling was adverse to the company.", ko: "그 판결은 회사에 불리했다." },
    syn: ["unfavorable", "harmful"] },
];
