// DAY 8 — 빈출 형용사 ②(판단·정도·태도). 파일 성격은 day-001.js 헤더 참고(동적 import 전용).
//
// DAY 5와 짝을 이룬다. 여기 단어들은 뜻보다 **어울리는 짝**이 함정이라(acute pain,
// stringent rules처럼) 예문을 실제로 붙어 다니는 조합으로 골랐다.
export const WORDS = [
  { id: "v008-01", word: "acute", pos: "adj.", ko: ["극심한", "예리한"], freq: 1,
    roots: ["acu"], hint: "acu(뾰족한, 날카로운) → 끝이 뾰족하게 파고드는",
    ex: { en: "The patient has acute chest pain.", ko: "그 환자는 극심한 흉통을 앓고 있다." },
    syn: ["severe", "keen"] },
  { id: "v008-02", word: "adjacent", pos: "adj.", ko: ["인접한", "이웃한"], freq: 1,
    roots: ["ad", "jac"], hint: "ad(~에) + jac(눕다) → 바로 옆에 누워 붙어 있는",
    ex: { en: "The park is adjacent to the library.", ko: "그 공원은 도서관에 인접해 있다." },
    syn: ["neighboring", "abutting"] },
  { id: "v008-03", word: "ample", pos: "adj.", ko: ["충분한", "널찍한"], freq: 2,
    roots: ["ampl"], hint: "ampl(넓은) → 남을 만큼 넓게 잡아 둔",
    ex: { en: "The hall has ample space for two hundred guests.", ko: "그 홀은 손님 200명이 들어갈 만큼 널찍하다." },
    syn: ["abundant", "spacious"] },
  { id: "v008-04", word: "benign", pos: "adj.", ko: ["양성의", "온화한"], freq: 2,
    roots: ["bene", "gen"], hint: "bene(좋은) + gn(=gen, 낳다) → 좋게 태어나 해를 끼치지 않는",
    ex: { en: "The tumor turned out to be benign.", ko: "그 종양은 양성으로 밝혀졌다." },
    syn: ["harmless", "kindly"] },
  { id: "v008-05", word: "chronic", pos: "adj.", ko: ["만성적인"], freq: 1,
    roots: ["chron"], hint: "chron(시간) → 오랜 시간에 걸쳐 눌어붙은",
    ex: { en: "He suffers from chronic back pain.", ko: "그는 만성 요통을 앓는다." },
    syn: ["persistent", "long-standing"] },
  { id: "v008-06", word: "compulsory", pos: "adj.", ko: ["의무적인", "강제적인"], freq: 1,
    roots: ["com", "pel"], hint: "com(완전히) + puls(=pel, 밀다) → 끝까지 떠밀어 하게 만드는",
    ex: { en: "Military service is compulsory in that country.", ko: "그 나라에서 병역은 의무다." },
    syn: ["mandatory", "obligatory"] },
  { id: "v008-07", word: "concise", pos: "adj.", ko: ["간결한"], freq: 1,
    roots: ["com", "cis"], hint: "con(=com, 완전히) + cis(자르다) → 군더더기를 다 잘라낸",
    ex: { en: "Keep the summary short and concise.", ko: "요약은 짧고 간결하게 하라." },
    syn: ["succinct", "terse"] },
  { id: "v008-08", word: "consecutive", pos: "adj.", ko: ["연속적인", "잇따른"], freq: 1,
    roots: ["com", "secut"], hint: "con(=com, 함께) + secut(따르다) → 끊기지 않고 잇달아 따라오는",
    ex: { en: "It rained for five consecutive days.", ko: "닷새 연속으로 비가 왔다." },
    syn: ["successive", "back-to-back"] },
  { id: "v008-09", word: "credible", pos: "adj.", ko: ["믿을 만한"], freq: 1,
    roots: ["cred"], hint: "cred(믿다) → 믿어 줄 만한",
    ex: { en: "The witness gave a credible account.", ko: "그 증인은 믿을 만한 진술을 했다." },
    syn: ["trustworthy", "convincing"] },
  { id: "v008-10", word: "decent", pos: "adj.", ko: ["괜찮은", "품위 있는"], freq: 1,
    roots: ["dec"], hint: "dec(어울리는, 알맞은) → 남 앞에 내놓아도 어울리는",
    ex: { en: "They pay a decent wage.", ko: "그들은 괜찮은 임금을 준다." },
    syn: ["respectable", "fair"] },
  { id: "v008-11", word: "destitute", pos: "adj.", ko: ["궁핍한", "빈털터리의"], freq: 2,
    roots: ["de", "stitut"], hint: "de(떨어져) + stitut(세우다) → 세워 뒀던 것이 다 치워진",
    ex: { en: "The fire left the family destitute.", ko: "그 화재로 그 가족은 빈털터리가 됐다." },
    syn: ["impoverished", "penniless"] },
  { id: "v008-12", word: "discreet", pos: "adj.", ko: ["입이 무거운", "조심스러운"], freq: 2,
    roots: ["dis", "cern"], hint: "dis(따로) + creet(=cern, 가려내다) → 할 말과 안 할 말을 가려내는",
    ex: { en: "Be discreet about the salary talks.", ko: "임금 협상에 대해서는 입조심하라." },
    syn: ["prudent", "tactful"] },
  { id: "v008-13", word: "dubious", pos: "adj.", ko: ["의심스러운", "미심쩍은"], freq: 2,
    roots: ["dub"], hint: "dub(둘로 갈려 의심하다) → 마음이 둘로 갈려 못 미더운",
    ex: { en: "The evidence looks dubious to me.", ko: "그 증거는 내게 의심스러워 보인다." },
    syn: ["doubtful", "questionable"] },
  { id: "v008-14", word: "empirical", pos: "adj.", ko: ["실증적인", "경험에 근거한"], freq: 2,
    roots: ["empir"], hint: "empir(경험, 시도) → 직접 해 보고 얻은",
    ex: { en: "The claim lacks empirical support.", ko: "그 주장은 실증적 근거가 부족하다." },
    syn: ["experimental", "observed"] },
  { id: "v008-15", word: "erroneous", pos: "adj.", ko: ["잘못된", "틀린"], freq: 2,
    roots: ["err"], hint: "err(헤매다, 벗어나다) → 길을 벗어나 헤맨",
    ex: { en: "The report drew an erroneous conclusion.", ko: "그 보고서는 잘못된 결론을 냈다." },
    syn: ["mistaken", "false"] },
  { id: "v008-16", word: "exquisite", pos: "adj.", ko: ["정교한", "더없이 훌륭한"], freq: 2,
    roots: ["ex", "quir"], hint: "ex(밖까지) + quis(=quir, 찾다) → 샅샅이 찾아내 골라낸",
    ex: { en: "The museum holds exquisite jade carvings.", ko: "그 박물관은 정교한 옥 조각을 소장하고 있다." },
    syn: ["delicate", "superb"] },
  { id: "v008-17", word: "fertile", pos: "adj.", ko: ["비옥한", "다산의"], freq: 1,
    roots: ["fer"], hint: "fer(나르다) → 열매를 실어 내는",
    ex: { en: "The valley has fertile soil.", ko: "그 계곡은 토양이 비옥하다." },
    syn: ["productive", "rich"] },
  { id: "v008-18", word: "frugal", pos: "adj.", ko: ["검소한", "알뜰한"], freq: 2,
    roots: ["frug"], hint: "frug(열매, 알뜰함) → 열매 하나도 허투루 안 쓰는",
    ex: { en: "My grandmother was frugal with money.", ko: "우리 할머니는 돈에 알뜰하셨다." },
    syn: ["thrifty", "sparing"] },
  { id: "v008-19", word: "immense", pos: "adj.", ko: ["막대한", "엄청난"], freq: 1,
    roots: ["in-neg", "mens"], hint: "im(=in, 아닌) + mens(재다) → 잴 수 없을 만큼 큰",
    ex: { en: "The project required an immense effort.", ko: "그 사업에는 막대한 노력이 들었다." },
    syn: ["vast", "enormous"] },
  { id: "v008-20", word: "impartial", pos: "adj.", ko: ["공정한", "편들지 않는"], freq: 1,
    roots: ["in-neg", "part"], hint: "im(=in, 아닌) + part(몫) → 어느 한쪽 몫으로도 기울지 않는",
    ex: { en: "A judge must remain impartial.", ko: "판사는 공정해야 한다." },
    syn: ["unbiased", "neutral"] },
  { id: "v008-21", word: "incessant", pos: "adj.", ko: ["끊임없는"], freq: 2,
    roots: ["in-neg", "ced"], hint: "in(아닌) + cess(=ced, 물러나다) → 물러날 줄 모르고 계속되는",
    ex: { en: "The incessant noise kept everyone awake.", ko: "끊임없는 소음이 모두를 깨어 있게 했다." },
    syn: ["nonstop", "constant"] },
  { id: "v008-22", word: "indispensable", pos: "adj.", ko: ["없어서는 안 될"], freq: 1,
    roots: ["in-neg", "dis", "pens"], hint: "in(아닌) + dis(따로) + pens(무게를 달다) → 따로 덜어내 저울에서 뺄 수 없는",
    ex: { en: "Water is indispensable to life.", ko: "물은 생명에 없어서는 안 된다." },
    syn: ["essential", "vital"] },
  { id: "v008-23", word: "innate", pos: "adj.", ko: ["타고난", "선천적인"], freq: 2,
    roots: ["in", "nat"], hint: "in(안에) + nat(태어나다) → 태어날 때부터 안에 있던",
    ex: { en: "Children have an innate sense of fairness.", ko: "아이들에겐 타고난 공정 감각이 있다." },
    syn: ["inborn", "inherent"] },
  { id: "v008-24", word: "lateral", pos: "adj.", ko: ["옆의", "측면의"], freq: 2,
    roots: ["later"], hint: "later(옆, 측면) → 옆으로 난",
    ex: { en: "He made a lateral move to another team.", ko: "그는 다른 팀으로 수평 이동했다." },
    syn: ["sideways", "side"] },
  { id: "v008-25", word: "lenient", pos: "adj.", ko: ["관대한", "너그러운"], freq: 2,
    roots: ["len"], hint: "len(부드러운) → 부드럽게 봐주는",
    ex: { en: "The court was lenient with first offenders.", ko: "법원은 초범에게 관대했다." },
    syn: ["mild", "forgiving"] },
  { id: "v008-26", word: "lucid", pos: "adj.", ko: ["명료한", "또렷한"], freq: 2,
    roots: ["luc"], hint: "luc(빛) → 빛이 들어 환히 보이는",
    ex: { en: "She gave a lucid explanation of the rule.", ko: "그녀는 그 규칙을 명료하게 설명했다." },
    syn: ["clear", "intelligible"] },
  { id: "v008-27", word: "malicious", pos: "adj.", ko: ["악의적인"], freq: 2,
    roots: ["mal"], hint: "mal(나쁜) → 나쁜 마음을 품은",
    ex: { en: "The email contained malicious code.", ko: "그 이메일에는 악성 코드가 들어 있었다." },
    syn: ["spiteful", "vicious"] },
  { id: "v008-28", word: "meticulous", pos: "adj.", ko: ["꼼꼼한", "세심한"], freq: 2,
    roots: ["metic"], hint: "metic(두려움, 조심) → 틀릴까 겁날 만큼 조심스러운",
    ex: { en: "He keeps meticulous records.", ko: "그는 기록을 꼼꼼하게 남긴다." },
    syn: ["painstaking", "scrupulous"] },
  { id: "v008-29", word: "moderate", pos: "adj./v.", ko: ["적당한", "온건한", "완화하다"], freq: 1,
    roots: ["mod"], hint: "mod(알맞은 정도) → 알맞은 선을 넘지 않는",
    ex: { en: "The forecast calls for moderate winds.", ko: "예보는 적당한 바람을 예상한다." },
    syn: ["mild", "temper"] },
  { id: "v008-30", word: "nominal", pos: "adj.", ko: ["이름뿐인", "명목상의"], freq: 2,
    roots: ["nom-name"], hint: "nom(이름) → 이름만 걸려 있을 뿐인",
    ex: { en: "He paid a nominal fee for the license.", ko: "그는 명목상의 수수료만 내고 면허를 받았다." },
    syn: ["token", "in name only"] },
  { id: "v008-31", word: "obedient", pos: "adj.", ko: ["순종적인", "말을 잘 듣는"], freq: 2,
    roots: ["ob", "audi"], hint: "ob(~에게) + edi(=audi, 듣다) → 시키는 말을 그대로 듣는",
    ex: { en: "The dog is quiet and obedient.", ko: "그 개는 조용하고 순종적이다." },
    syn: ["compliant", "dutiful"] },
  { id: "v008-32", word: "optional", pos: "adj.", ko: ["선택적인"], freq: 1,
    roots: ["opt"], hint: "opt(고르다) → 골라도 되고 안 골라도 되는",
    ex: { en: "The evening session is optional.", ko: "저녁 세션은 선택 사항이다." },
    syn: ["voluntary", "elective"] },
  { id: "v008-33", word: "peculiar", pos: "adj.", ko: ["기이한", "특유의"], freq: 1,
    roots: ["pecu"], hint: "pecu(사유 재산, 제 것) → 저만 가진 탓에 남 눈엔 낯선",
    ex: { en: "The soup had a peculiar taste.", ko: "그 수프에서는 기이한 맛이 났다." },
    syn: ["odd", "distinctive"] },
  { id: "v008-34", word: "pertinent", pos: "adj.", ko: ["적절한", "관련 있는"], freq: 2,
    roots: ["per", "tain"], hint: "per(끝까지) + tin(=tain, 잡다) → 주제를 끝까지 붙잡고 있는",
    ex: { en: "Please keep your questions pertinent.", ko: "질문은 주제에 맞게 해 주세요." },
    syn: ["relevant", "apposite"] },
  { id: "v008-35", word: "plentiful", pos: "adj.", ko: ["풍족한", "넉넉한"], freq: 2,
    roots: ["ple"], hint: "ple(채우다) + ful(가득) → 가득 채워질 만큼 있는",
    ex: { en: "Fish were plentiful in these waters.", ko: "이 해역에는 물고기가 넉넉했다." },
    syn: ["ample", "copious"] },
  { id: "v008-36", word: "potent", pos: "adj.", ko: ["강력한", "효력이 센"], freq: 2,
    roots: ["pot"], hint: "pot(힘) → 힘이 세게 든",
    ex: { en: "The drug is potent in small doses.", ko: "그 약은 소량으로도 효력이 세다." },
    syn: ["powerful", "strong"] },
  { id: "v008-37", word: "pragmatic", pos: "adj.", ko: ["실용적인", "현실적인"], freq: 1,
    roots: ["prag"], hint: "prag(행하다, 일) → 실제로 되는지부터 보는",
    ex: { en: "She took a pragmatic view of the budget.", ko: "그녀는 예산을 현실적으로 봤다." },
    syn: ["practical", "down-to-earth"] },
  { id: "v008-38", word: "prevalent", pos: "adj.", ko: ["널리 퍼진", "만연한"], freq: 1,
    roots: ["pre", "vail"], hint: "pre(앞서) + val(=vail, 힘이 있다) → 앞서 힘을 떨쳐 두루 퍼진",
    ex: { en: "The habit is prevalent among teenagers.", ko: "그 습관은 십 대 사이에 널리 퍼져 있다." },
    syn: ["widespread", "rife"] },
  { id: "v008-39", word: "prudent", pos: "adj.", ko: ["신중한", "분별 있는"], freq: 1,
    roots: ["pro", "vis"], hint: "pru(=pro, 미리) + dent(=vis, 보다) → 미리 내다보고 조심하는",
    ex: { en: "It would be prudent to save more.", ko: "더 저축하는 편이 신중할 것이다." },
    syn: ["cautious", "judicious"] },
  { id: "v008-40", word: "rational", pos: "adj.", ko: ["합리적인", "이성적인"], freq: 1,
    roots: ["rat"], hint: "rat(셈하다, 헤아리다) → 하나하나 헤아려 따진",
    ex: { en: "There is a rational explanation for the noise.", ko: "그 소리에는 합리적인 설명이 있다." },
    syn: ["logical", "reasoned"] },
  { id: "v008-41", word: "reciprocal", pos: "adj.", ko: ["상호 간의", "호혜적인"], freq: 2,
    roots: ["re", "pro"], hint: "reci(=re, 되받아) + proc(=pro, 앞으로) → 주고 되받으며 오가는",
    ex: { en: "The two states signed a reciprocal agreement.", ko: "두 주는 호혜 협정에 서명했다." },
    syn: ["mutual", "give-and-take"] },
  { id: "v008-42", word: "rigorous", pos: "adj.", ko: ["엄격한", "철저한"], freq: 1,
    roots: ["rig"], hint: "rig(뻣뻣한) → 조금도 봐주지 않고 뻣뻣하게 미는",
    ex: { en: "The drug went through rigorous testing.", ko: "그 약은 철저한 시험을 거쳤다." },
    syn: ["strict", "exacting"] },
  { id: "v008-43", word: "sensible", pos: "adj.", ko: ["분별 있는", "현명한"], freq: 1,
    roots: ["sent"], hint: "sens(=sent, 느끼다) → 상황을 제대로 느껴 아는",
    ex: { en: "That is a sensible way to spend the money.", ko: "그건 돈을 쓰는 현명한 방법이다." },
    syn: ["wise", "sound"] },
  { id: "v008-44", word: "simultaneous", pos: "adj.", ko: ["동시의"], freq: 2,
    roots: ["simil"], hint: "simul(=simil, 같은 때) → 같은 때에 나란히 일어나는",
    ex: { en: "The channel offers simultaneous interpretation.", ko: "그 채널은 동시통역을 제공한다." },
    syn: ["concurrent", "at once"] },
  { id: "v008-45", word: "sole", pos: "adj.", ko: ["유일한", "단독의"], freq: 1,
    roots: ["sol"], hint: "sol(혼자) → 딱 하나뿐인",
    ex: { en: "She is the sole owner of the building.", ko: "그녀가 그 건물의 유일한 소유주다." },
    syn: ["only", "exclusive"] },
  { id: "v008-46", word: "stringent", pos: "adj.", ko: ["엄중한", "까다로운"], freq: 2,
    roots: ["strain"], hint: "string(=strain, 조이다) → 바짝 조여 놓은",
    ex: { en: "The rules on food safety are stringent.", ko: "식품 안전 규정은 엄중하다." },
    syn: ["tight", "severe"] },
  { id: "v008-47", word: "tangible", pos: "adj.", ko: ["실체가 있는", "만질 수 있는"], freq: 1,
    roots: ["tang"], hint: "tang(닿다) → 손에 닿아 만져지는",
    ex: { en: "The talks produced no tangible result.", ko: "그 회담은 실체 있는 결과를 내지 못했다." },
    syn: ["concrete", "palpable"] },
  { id: "v008-48", word: "verbal", pos: "adj.", ko: ["구두의", "말의"], freq: 1,
    roots: ["verb"], hint: "verb(말) → 글이 아니라 말로 이뤄진",
    ex: { en: "They had only a verbal agreement.", ko: "그들에게는 구두 합의만 있었다." },
    syn: ["oral", "spoken"] },
  { id: "v008-49", word: "viable", pos: "adj.", ko: ["실행 가능한", "생존 가능한"], freq: 1,
    roots: ["vit"], hint: "vi(=vit, 생명) + able(할 수 있는) → 살아남을 수 있는",
    ex: { en: "Solar power is now a viable option.", ko: "태양광은 이제 실행 가능한 선택지다." },
    syn: ["workable", "sustainable"] },
  { id: "v008-50", word: "vigorous", pos: "adj.", ko: ["활기찬", "격렬한"], freq: 1,
    roots: ["vig"], hint: "vig(활기, 생기) → 생기가 뻗쳐 나오는",
    ex: { en: "He is still vigorous at eighty.", ko: "그는 여든에도 여전히 활기차다." },
    syn: ["energetic", "robust"] },
];
